// =====================================================================
//  js/data-en.js — АНГЛІЙСЬКА МОВА (ПОВНИЙ НАБІР)
//  Повністю сумісний з js/data.js для норвезької.
//  Містить VOCAB, GRAMMAR, NORSKPROVE_TASKS, LEVEL_TEST.
// =====================================================================
(function () {

    // =====================================================================
    //  VOCAB – СЛОВНИК ЗА РІВНЯМИ (A1-C2)
    // =====================================================================
    const VOCAB = {
        // -------------------- A1 --------------------
        A1: [
            // Привітання та базові фрази
            { t: "Привітання", no: "hello", uk: "привіт", en: "hello", ru: "привет", ex_no: "Hello, how are you?", ex_uk: "Привіт, як справи?", en_ex: "Hello, how are you?", ru_ex: "Привет, как дела?" },
            { t: "Привітання", no: "good morning", uk: "добрий ранок", en: "good morning", ru: "доброе утро", ex_no: "Good morning, did you sleep well?", ex_uk: "Добрий ранок, ти добре спав?", en_ex: "Good morning, did you sleep well?", ru_ex: "Доброе утро, ты хорошо спал?" },
            { t: "Привітання", no: "good evening", uk: "добрий вечір", en: "good evening", ru: "добрый вечер", ex_no: "Good evening, welcome home.", ex_uk: "Добрий вечір, ласкаво просимо додому.", en_ex: "Good evening, welcome home.", ru_ex: "Добрый вечер, добро пожаловать домой." },
            { t: "Привітання", no: "good night", uk: "на добраніч", en: "good night", ru: "спокойной ночи", ex_no: "Good night, sleep well!", ex_uk: "На добраніч, солодких снів!", en_ex: "Good night, sleep well!", ru_ex: "Спокойной ночи, сладких снов!" },
            { t: "Привітання", no: "goodbye", uk: "до побачення", en: "goodbye", ru: "до свидания", ex_no: "Goodbye, see you tomorrow.", ex_uk: "До побачення, побачимось завтра.", en_ex: "Goodbye, see you tomorrow.", ru_ex: "До свидания, увидимся завтра." },
            { t: "Привітання", no: "thank you", uk: "дякую", en: "thank you", ru: "спасибо", ex_no: "Thank you for your help.", ex_uk: "Дякую за допомогу.", en_ex: "Thank you for your help.", ru_ex: "Спасибо за помощь." },
            { t: "Привітання", no: "please", uk: "будь ласка", en: "please", ru: "пожалуйста", ex_no: "Can you help me, please?", ex_uk: "Можеш допомогти мені, будь ласка?", en_ex: "Can you help me, please?", ru_ex: "Можешь помочь мне, пожалуйста?" },
            { t: "Привітання", no: "sorry", uk: "вибачте", en: "sorry", ru: "извините", ex_no: "Sorry, where is the station?", ex_uk: "Вибачте, де вокзал?", en_ex: "Sorry, where is the station?", ru_ex: "Извините, где вокзал?" },
            { t: "Привітання", no: "yes", uk: "так", en: "yes", ru: "да", ex_no: "Yes, that's right.", ex_uk: "Так, це правда.", en_ex: "Yes, that's right.", ru_ex: "Да, это правда." },
            { t: "Привітання", no: "no", uk: "ні", en: "no", ru: "нет", ex_no: "No, I don't know.", ex_uk: "Ні, я не знаю.", en_ex: "No, I don't know.", ru_ex: "Нет, я не знаю." },
            // Числа
            { t: "Числа", no: "zero", uk: "нуль", en: "zero", ru: "ноль", ex_no: "We start from zero.", ex_uk: "Ми починаємо з нуля.", en_ex: "We start from zero.", ru_ex: "Мы начинаем с нуля." },
            { t: "Числа", no: "one", uk: "один", en: "one", ru: "один", ex_no: "I have one cat.", ex_uk: "У мене є один кіт.", en_ex: "I have one cat.", ru_ex: "У меня есть один кот." },
            { t: "Числа", no: "two", uk: "два", en: "two", ru: "два", ex_no: "It's two o'clock.", ex_uk: "Зараз друга година.", en_ex: "It's two o'clock.", ru_ex: "Сейчас два часа." },
            { t: "Числа", no: "three", uk: "три", en: "three", ru: "три", ex_no: "I have three brothers.", ex_uk: "У мене три брати.", en_ex: "I have three brothers.", ru_ex: "У меня три брата." },
            { t: "Числа", no: "four", uk: "чотири", en: "four", ru: "четыре", ex_no: "The table has four legs.", ex_uk: "У стола чотири ноги.", en_ex: "The table has four legs.", ru_ex: "У стола четыре ноги." },
            { t: "Числа", no: "five", uk: "п'ять", en: "five", ru: "пять", ex_no: "I finish work at five.", ex_uk: "Я закінчую роботу о п'ятій.", en_ex: "I finish work at five.", ru_ex: "Я заканчиваю работу в пять." },
            { t: "Числа", no: "six", uk: "шість", en: "six", ru: "шесть", ex_no: "We wake up at six.", ex_uk: "Ми прокидаємось о шостій.", en_ex: "We wake up at six.", ru_ex: "Мы просыпаемся в шесть." },
            { t: "Числа", no: "seven", uk: "сім", en: "seven", ru: "семь", ex_no: "There are seven days in a week.", ex_uk: "У тижні сім днів.", en_ex: "There are seven days in a week.", ru_ex: "В неделе семь дней." },
            { t: "Числа", no: "eight", uk: "вісім", en: "eight", ru: "восемь", ex_no: "The shop opens at eight.", ex_uk: "Магазин відкривається о восьмій.", en_ex: "The shop opens at eight.", ru_ex: "Магазин открывается в восемь." },
            { t: "Числа", no: "nine", uk: "дев'ять", en: "nine", ru: "девять", ex_no: "School starts at nine.", ex_uk: "Школа починається о дев'ятій.", en_ex: "School starts at nine.", ru_ex: "Школа начинается в девять." },
            { t: "Числа", no: "ten", uk: "десять", en: "ten", ru: "десять", ex_no: "I count to ten.", ex_uk: "Я рахую до десяти.", en_ex: "I count to ten.", ru_ex: "Я считаю до десяти." },
            { t: "Числа", no: "twenty", uk: "двадцять", en: "twenty", ru: "двадцать", ex_no: "She is twenty years old.", ex_uk: "Їй двадцять років.", en_ex: "She is twenty years old.", ru_ex: "Ей двадцать лет." },
            { t: "Числа", no: "hundred", uk: "сто", en: "hundred", ru: "сто", ex_no: "There are a hundred people here.", ex_uk: "Тут сто людей.", en_ex: "There are a hundred people here.", ru_ex: "Здесь сто человек." },
            // Родина
            { t: "Родина", no: "family", uk: "родина", en: "family", ru: "семья", ex_no: "I love my family.", ex_uk: "Я люблю свою родину.", en_ex: "I love my family.", ru_ex: "Я люблю свою семью." },
            { t: "Родина", no: "mother", uk: "мама", en: "mother", ru: "мама", ex_no: "My mother cooks dinner.", ex_uk: "Моя мама готує вечерю.", en_ex: "My mother cooks dinner.", ru_ex: "Моя мама готовит ужин." },
            { t: "Родина", no: "father", uk: "тато", en: "father", ru: "папа", ex_no: "My father works in the city.", ex_uk: "Мій тато працює в місті.", en_ex: "My father works in the city.", ru_ex: "Мой папа работает в городе." },
            { t: "Родина", no: "sister", uk: "сестра", en: "sister", ru: "сестра", ex_no: "My sister is younger than me.", ex_uk: "Моя сестра молодша за мене.", en_ex: "My sister is younger than me.", ru_ex: "Моя сестра младше меня." },
            { t: "Родина", no: "brother", uk: "брат", en: "brother", ru: "брат", ex_no: "My brother lives in London.", ex_uk: "Мій брат живе в Лондоні.", en_ex: "My brother lives in London.", ru_ex: "Мой брат живёт в Лондоне." },
            { t: "Родина", no: "child", uk: "дитина", en: "child", ru: "ребёнок", ex_no: "The child is playing outside.", ex_uk: "Дитина грається надворі.", en_ex: "The child is playing outside.", ru_ex: "Ребёнок играет на улице." },
            { t: "Родина", no: "grandmother", uk: "бабуся", en: "grandmother", ru: "бабушка", ex_no: "My grandmother bakes bread every week.", ex_uk: "Моя бабуся пече хліб щотижня.", en_ex: "My grandmother bakes bread every week.", ru_ex: "Моя бабушка печёт хлеб каждую неделю." },
            { t: "Родина", no: "grandfather", uk: "дідусь", en: "grandfather", ru: "дедушка", ex_no: "My grandfather tells great stories.", ex_uk: "Мій дідусь розповідає чудові історії.", en_ex: "My grandfather tells great stories.", ru_ex: "Мой дедушка рассказывает отличные истории." },
            // Кольори
            { t: "Кольори", no: "red", uk: "червоний", en: "red", ru: "красный", ex_no: "The apple is red.", ex_uk: "Яблуко червоне.", en_ex: "The apple is red.", ru_ex: "Яблоко красное." },
            { t: "Кольори", no: "blue", uk: "синій", en: "blue", ru: "синий", ex_no: "The sky is blue today.", ex_uk: "Сьогодні небо синє.", en_ex: "The sky is blue today.", ru_ex: "Сегодня небо синее." },
            { t: "Кольори", no: "green", uk: "зелений", en: "green", ru: "зелёный", ex_no: "The grass is green.", ex_uk: "Трава зелена.", en_ex: "The grass is green.", ru_ex: "Трава зелёная." },
            { t: "Кольори", no: "yellow", uk: "жовтий", en: "yellow", ru: "жёлтый", ex_no: "The sun is yellow.", ex_uk: "Сонце жовте.", en_ex: "The sun is yellow.", ru_ex: "Солнце жёлтое." },
            { t: "Кольори", no: "black", uk: "чорний", en: "black", ru: "чёрный", ex_no: "She has a black cat.", ex_uk: "У неї чорний кіт.", en_ex: "She has a black cat.", ru_ex: "У неё чёрный кот." },
            { t: "Кольори", no: "white", uk: "білий", en: "white", ru: "белый", ex_no: "The snow is white.", ex_uk: "Сніг білий.", en_ex: "The snow is white.", ru_ex: "Снег белый." },
            // Дні тижня
            { t: "Дні тижня", no: "Monday", uk: "понеділок", en: "Monday", ru: "понедельник", ex_no: "I start work on Monday.", ex_uk: "Я починаю роботу в понеділок.", en_ex: "I start work on Monday.", ru_ex: "Я начинаю работу в понедельник." },
            { t: "Дні тижня", no: "Tuesday", uk: "вівторок", en: "Tuesday", ru: "вторник", ex_no: "We have a meeting on Tuesday.", ex_uk: "У нас зустріч у вівторок.", en_ex: "We have a meeting on Tuesday.", ru_ex: "У нас встреча во вторник." },
            { t: "Дні тижня", no: "Wednesday", uk: "середа", en: "Wednesday", ru: "среда", ex_no: "I go to the gym on Wednesday.", ex_uk: "Я ходжу в спортзал у середу.", en_ex: "I go to the gym on Wednesday.", ru_ex: "Я хожу в спортзал в среду." },
            { t: "Дні тижня", no: "Thursday", uk: "четвер", en: "Thursday", ru: "четверг", ex_no: "The exam is on Thursday.", ex_uk: "Іспит у четвер.", en_ex: "The exam is on Thursday.", ru_ex: "Экзамен в четверг." },
            { t: "Дні тижня", no: "Friday", uk: "п'ятниця", en: "Friday", ru: "пятница", ex_no: "We celebrate on Friday.", ex_uk: "Ми святкуємо в п'ятницю.", en_ex: "We celebrate on Friday.", ru_ex: "Мы празднуем в пятницу." },
            { t: "Дні тижня", no: "Saturday", uk: "субота", en: "Saturday", ru: "суббота", ex_no: "I clean the house on Saturday.", ex_uk: "Я прибираю в суботу.", en_ex: "I clean the house on Saturday.", ru_ex: "Я убираюсь в субботу." },
            { t: "Дні тижня", no: "Sunday", uk: "неділя", en: "Sunday", ru: "воскресенье", ex_no: "We rest on Sunday.", ex_uk: "Ми відпочиваємо в неділю.", en_ex: "We rest on Sunday.", ru_ex: "Мы отдыхаем в воскресенье." },
            // Дієслова
            { t: "Дієслова", no: "to be", uk: "бути", en: "to be", ru: "быть", ex_no: "I am a student.", ex_uk: "Я студент.", en_ex: "I am a student.", ru_ex: "Я студент." },
            { t: "Дієслова", no: "to have", uk: "мати", en: "to have", ru: "иметь", ex_no: "I have a car.", ex_uk: "У мене є машина.", en_ex: "I have a car.", ru_ex: "У меня есть машина." },
            { t: "Дієслова", no: "to go", uk: "йти", en: "to go", ru: "идти", ex_no: "I go to work every day.", ex_uk: "Я йду на роботу щодня.", en_ex: "I go to work every day.", ru_ex: "Я иду на работу каждый день." },
            { t: "Дієслова", no: "to eat", uk: "їсти", en: "to eat", ru: "есть", ex_no: "We eat breakfast at seven.", ex_uk: "Ми снідаємо о сьомій.", en_ex: "We eat breakfast at seven.", ru_ex: "Мы завтракаем в семь." },
            { t: "Дієслова", no: "to drink", uk: "пити", en: "to drink", ru: "пить", ex_no: "I drink water every morning.", ex_uk: "Я п'ю воду щоранку.", en_ex: "I drink water every morning.", ru_ex: "Я пью воду каждое утро." },
            { t: "Дієслова", no: "to see", uk: "бачити", en: "to see", ru: "видеть", ex_no: "I can see the mountains.", ex_uk: "Я бачу гори.", en_ex: "I can see the mountains.", ru_ex: "Я вижу горы." },
            { t: "Дієслова", no: "to speak", uk: "говорити", en: "to speak", ru: "говорить", ex_no: "She speaks three languages.", ex_uk: "Вона говорить трьома мовами.", en_ex: "She speaks three languages.", ru_ex: "Она говорит на трёх языках." },
            { t: "Дієслова", no: "to want", uk: "хотіти", en: "to want", ru: "хотеть", ex_no: "I want a coffee, please.", ex_uk: "Я хочу каву, будь ласка.", en_ex: "I want a coffee, please.", ru_ex: "Я хочу кофе, пожалуйста." },
            // Їжа
            { t: "Їжа", no: "bread", uk: "хліб", en: "bread", ru: "хлеб", ex_no: "I buy fresh bread every day.", ex_uk: "Я купую свіжий хліб щодня.", en_ex: "I buy fresh bread every day.", ru_ex: "Я покупаю свежий хлеб каждый день." },
            { t: "Їжа", no: "water", uk: "вода", en: "water", ru: "вода", ex_no: "Can I have some water?", ex_uk: "Можна мені трохи води?", en_ex: "Can I have some water?", ru_ex: "Можно мне немного воды?" },
            { t: "Їжа", no: "milk", uk: "молоко", en: "milk", ru: "молоко", ex_no: "I drink milk with breakfast.", ex_uk: "Я п'ю молоко зі сніданком.", en_ex: "I drink milk with breakfast.", ru_ex: "Я пью молоко с завтраком." },
            { t: "Їжа", no: "egg", uk: "яйце", en: "egg", ru: "яйцо", ex_no: "I eat an egg every morning.", ex_uk: "Я їм яйце щоранку.", en_ex: "I eat an egg every morning.", ru_ex: "Я ем яйцо каждое утро." },
            { t: "Їжа", no: "apple", uk: "яблуко", en: "apple", ru: "яблоко", ex_no: "She eats an apple for lunch.", ex_uk: "Вона їсть яблуко на обід.", en_ex: "She eats an apple for lunch.", ru_ex: "Она ест яблоко на обед." },
            { t: "Їжа", no: "meat", uk: "м'ясо", en: "meat", ru: "мясо", ex_no: "We don't eat meat on Fridays.", ex_uk: "Ми не їмо м'ясо по п'ятницях.", en_ex: "We don't eat meat on Fridays.", ru_ex: "Мы не едим мясо по пятницам." },
            // Прикметники
            { t: "Прикметники", no: "big", uk: "великий", en: "big", ru: "большой", ex_no: "This is a big house.", ex_uk: "Це великий будинок.", en_ex: "This is a big house.", ru_ex: "Это большой дом." },
            { t: "Прикметники", no: "small", uk: "маленький", en: "small", ru: "маленький", ex_no: "The cat is very small.", ex_uk: "Кіт дуже маленький.", en_ex: "The cat is very small.", ru_ex: "Кот очень маленький." },
            { t: "Прикметники", no: "good", uk: "добрий", en: "good", ru: "хороший", ex_no: "This is a good idea.", ex_uk: "Це добра ідея.", en_ex: "This is a good idea.", ru_ex: "Это хорошая идея." },
            { t: "Прикметники", no: "bad", uk: "поганий", en: "bad", ru: "плохой", ex_no: "The weather is bad today.", ex_uk: "Сьогодні погана погода.", en_ex: "The weather is bad today.", ru_ex: "Сегодня плохая погода." },
            // Тіло
            { t: "Тіло", no: "head", uk: "голова", en: "head", ru: "голова", ex_no: "My head hurts.", ex_uk: "У мене болить голова.", en_ex: "My head hurts.", ru_ex: "У меня болит голова." },
            { t: "Тіло", no: "hand", uk: "рука", en: "hand", ru: "рука", ex_no: "Give me your hand.", ex_uk: "Дай мені руку.", en_ex: "Give me your hand.", ru_ex: "Дай мне руку." },
            { t: "Тіло", no: "eye", uk: "око", en: "eye", ru: "глаз", ex_no: "She has blue eyes.", ex_uk: "У неї блакитні очі.", en_ex: "She has blue eyes.", ru_ex: "У неё голубые глаза." },
            { t: "Тіло", no: "ear", uk: "вухо", en: "ear", ru: "ухо", ex_no: "I have an ear infection.", ex_uk: "У мене інфекція вуха.", en_ex: "I have an ear infection.", ru_ex: "У меня инфекция уха." },
            { t: "Тіло", no: "nose", uk: "ніс", en: "nose", ru: "нос", ex_no: "Her nose is red.", ex_uk: "Її ніс червоний.", en_ex: "Her nose is red.", ru_ex: "У неё красный нос." },
            // Дім
            { t: "Дім", no: "house", uk: "будинок", en: "house", ru: "дом", ex_no: "We live in a small house.", ex_uk: "Ми живемо в маленькому будинку.", en_ex: "We live in a small house.", ru_ex: "Мы живём в маленьком доме." },
            { t: "Дім", no: "room", uk: "кімната", en: "room", ru: "комната", ex_no: "My room is upstairs.", ex_uk: "Моя кімната нагорі.", en_ex: "My room is upstairs.", ru_ex: "Моя комната наверху." },
            { t: "Дім", no: "door", uk: "двері", en: "door", ru: "дверь", ex_no: "Please close the door.", ex_uk: "Будь ласка, зачини двері.", en_ex: "Please close the door.", ru_ex: "Пожалуйста, закрой дверь." },
            { t: "Дім", no: "table", uk: "стіл", en: "table", ru: "стол", ex_no: "The book is on the table.", ex_uk: "Книга на столі.", en_ex: "The book is on the table.", ru_ex: "Книга на столе." },
            { t: "Дім", no: "chair", uk: "стілець", en: "chair", ru: "стул", ex_no: "Sit on the chair.", ex_uk: "Сідай на стілець.", en_ex: "Sit on the chair.", ru_ex: "Садись на стул." },
            // Транспорт
            { t: "Транспорт", no: "car", uk: "машина", en: "car", ru: "машина", ex_no: "We drive a car to work.", ex_uk: "Ми їздимо на роботу машиною.", en_ex: "We drive a car to work.", ru_ex: "Мы ездим на работу на машине." },
            { t: "Транспорт", no: "bus", uk: "автобус", en: "bus", ru: "автобус", ex_no: "I take the bus to school.", ex_uk: "Я їду автобусом до школи.", en_ex: "I take the bus to school.", ru_ex: "Я еду автобусом в школу." },
            { t: "Транспорт", no: "train", uk: "поїзд", en: "train", ru: "поезд", ex_no: "The train leaves at eight.", ex_uk: "Поїзд відправляється о восьмій.", en_ex: "The train leaves at eight.", ru_ex: "Поезд отправляется в восемь." },
            { t: "Транспорт", no: "bicycle", uk: "велосипед", en: "bicycle", ru: "велосипед", ex_no: "I ride my bicycle to work.", ex_uk: "Я їду на велосипеді на роботу.", en_ex: "I ride my bicycle to work.", ru_ex: "Я еду на велосипеде на работу." },
        ],

        // -------------------- A2 --------------------
        A2: [
            { t: "Покупки", no: "shop", uk: "магазин", en: "shop", ru: "магазин", ex_no: "The shop opens at nine.", ex_uk: "Магазин відкривається о дев'ятій.", en_ex: "The shop opens at nine.", ru_ex: "Магазин открывается в девять." },
            { t: "Покупки", no: "buy", uk: "купувати", en: "buy", ru: "покупать", ex_no: "I buy fresh bread every day.", ex_uk: "Я купую свіжий хліб щодня.", en_ex: "I buy fresh bread every day.", ru_ex: "Я покупаю свежий хлеб каждый день." },
            { t: "Покупки", no: "price", uk: "ціна", en: "price", ru: "цена", ex_no: "What is the price of this?", ex_uk: "Яка ціна на це?", en_ex: "What is the price of this?", ru_ex: "Какая цена на это?" },
            { t: "Покупки", no: "money", uk: "гроші", en: "money", ru: "деньги", ex_no: "I don't have enough money.", ex_uk: "У мене недостатньо грошей.", en_ex: "I don't have enough money.", ru_ex: "У меня недостаточно денег." },
            { t: "Напрямки", no: "left", uk: "ліворуч", en: "left", ru: "налево", ex_no: "Turn left at the corner.", ex_uk: "Поверни ліворуч на розі.", en_ex: "Turn left at the corner.", ru_ex: "Поверни налево на углу." },
            { t: "Напрямки", no: "right", uk: "праворуч", en: "right", ru: "направо", ex_no: "The station is on your right.", ex_uk: "Станція праворуч від тебе.", en_ex: "The station is on your right.", ru_ex: "Станция справа от тебя." },
            { t: "Напрямки", no: "straight", uk: "прямо", en: "straight", ru: "прямо", ex_no: "Go straight ahead.", ex_uk: "Іди прямо.", en_ex: "Go straight ahead.", ru_ex: "Иди прямо." },
            { t: "Напрямки", no: "map", uk: "карта", en: "map", ru: "карта", ex_no: "Can you show me on the map?", ex_uk: "Можеш показати мені на карті?", en_ex: "Can you show me on the map?", ru_ex: "Можешь показать мне на карте?" },
            { t: "Робота", no: "job", uk: "робота", en: "job", ru: "работа", ex_no: "She found a new job.", ex_uk: "Вона знайшла нову роботу.", en_ex: "She found a new job.", ru_ex: "Она нашла новую работу." },
            { t: "Робота", no: "office", uk: "офіс", en: "office", ru: "офис", ex_no: "I work in an office.", ex_uk: "Я працюю в офісі.", en_ex: "I work in an office.", ru_ex: "Я работаю в офисе." },
            { t: "Робота", no: "meeting", uk: "зустріч", en: "meeting", ru: "встреча", ex_no: "We have a meeting at ten.", ex_uk: "У нас зустріч о десятій.", en_ex: "We have a meeting at ten.", ru_ex: "У нас встреча в десять." },
            { t: "Робота", no: "salary", uk: "зарплата", en: "salary", ru: "зарплата", ex_no: "My salary is good.", ex_uk: "Моя зарплата хороша.", en_ex: "My salary is good.", ru_ex: "Моя зарплата хорошая." },
            { t: "Хобі", no: "hobby", uk: "хобі", en: "hobby", ru: "хобби", ex_no: "What is your hobby?", ex_uk: "Яке твоє хобі?", en_ex: "What is your hobby?", ru_ex: "Какое у тебя хобби?" },
            { t: "Хобі", no: "read", uk: "читати", en: "read", ru: "читать", ex_no: "I like to read books.", ex_uk: "Я люблю читати книги.", en_ex: "I like to read books.", ru_ex: "Я люблю читать книги." },
            { t: "Хобі", no: "travel", uk: "подорожувати", en: "travel", ru: "путешествовать", ex_no: "We love to travel.", ex_uk: "Ми любимо подорожувати.", en_ex: "We love to travel.", ru_ex: "Мы любим путешествовать." },
            { t: "Хобі", no: "music", uk: "музика", en: "music", ru: "музыка", ex_no: "I listen to music every day.", ex_uk: "Я слухаю музику щодня.", en_ex: "I listen to music every day.", ru_ex: "Я слушаю музыку каждый день." },
            { t: "Погода", no: "rain", uk: "дощ", en: "rain", ru: "дождь", ex_no: "It's going to rain tomorrow.", ex_uk: "Завтра буде дощ.", en_ex: "It's going to rain tomorrow.", ru_ex: "Завтра будет дождь." },
            { t: "Погода", no: "snow", uk: "сніг", en: "snow", ru: "снег", ex_no: "It snows in winter.", ex_uk: "Взимку йде сніг.", en_ex: "It snows in winter.", ru_ex: "Зимой идёт снег." },
            { t: "Погода", no: "sunny", uk: "сонячно", en: "sunny", ru: "солнечно", ex_no: "It's sunny today.", ex_uk: "Сьогодні сонячно.", en_ex: "It's sunny today.", ru_ex: "Сегодня солнечно." },
            { t: "Погода", no: "cold", uk: "холодно", en: "cold", ru: "холодно", ex_no: "It's cold outside.", ex_uk: "На вулиці холодно.", en_ex: "It's cold outside.", ru_ex: "На улице холодно." },
            { t: "Погода", no: "hot", uk: "спекотно", en: "hot", ru: "жарко", ex_no: "It's very hot in summer.", ex_uk: "Влітку дуже спекотно.", en_ex: "It's very hot in summer.", ru_ex: "Летом очень жарко." },
            { t: "Освіта", no: "school", uk: "школа", en: "school", ru: "школа", ex_no: "The children go to school.", ex_uk: "Діти ходять до школи.", en_ex: "The children go to school.", ru_ex: "Дети ходят в школу." },
            { t: "Освіта", no: "teacher", uk: "вчитель", en: "teacher", ru: "учитель", ex_no: "The teacher explains grammar.", ex_uk: "Вчитель пояснює граматику.", en_ex: "The teacher explains grammar.", ru_ex: "Учитель объясняет грамматику." },
            { t: "Освіта", no: "student", uk: "студент", en: "student", ru: "студент", ex_no: "She is a student at university.", ex_uk: "Вона студентка університету.", en_ex: "She is a student at university.", ru_ex: "Она студентка университета." },
            { t: "Освіта", no: "exam", uk: "іспит", en: "exam", ru: "экзамен", ex_no: "I passed the exam.", ex_uk: "Я склав іспит.", en_ex: "I passed the exam.", ru_ex: "Я сдал экзамен." },
            { t: "Ресторан", no: "menu", uk: "меню", en: "menu", ru: "меню", ex_no: "Can I have the menu?", ex_uk: "Можна меню?", en_ex: "Can I have the menu?", ru_ex: "Можно меню?" },
            { t: "Ресторан", no: "bill", uk: "рахунок", en: "bill", ru: "счёт", ex_no: "Can we have the bill, please?", ex_uk: "Можна нам рахунок, будь ласка?", en_ex: "Can we have the bill, please?", ru_ex: "Можно нам счёт, пожалуйста?" },
            { t: "Ресторан", no: "waiter", uk: "офіціант", en: "waiter", ru: "официант", ex_no: "The waiter is friendly.", ex_uk: "Офіціант привітний.", en_ex: "The waiter is friendly.", ru_ex: "Официант приветливый." },
            { t: "Ресторан", no: "order", uk: "замовляти", en: "order", ru: "заказывать", ex_no: "We order pizza on Friday.", ex_uk: "Ми замовляємо піцу в п'ятницю.", en_ex: "We order pizza on Friday.", ru_ex: "Мы заказываем пиццу в пятницу." },
            { t: "Емоції", no: "happy", uk: "щасливий", en: "happy", ru: "счастливый", ex_no: "She feels happy today.", ex_uk: "Вона сьогодні щаслива.", en_ex: "She feels happy today.", ru_ex: "Она сегодня счастлива." },
            { t: "Емоції", no: "sad", uk: "сумний", en: "sad", ru: "грустный", ex_no: "The sad movie made me cry.", ex_uk: "Сумний фільм змусив мене плакати.", en_ex: "The sad movie made me cry.", ru_ex: "Грустный фильм заставил меня плакать." },
            { t: "Емоції", no: "angry", uk: "злий", en: "angry", ru: "злой", ex_no: "He gets angry when he is late.", ex_uk: "Він злиться, коли запізнюється.", en_ex: "He gets angry when he is late.", ru_ex: "Он злится, когда опаздывает." },
            { t: "Емоції", no: "tired", uk: "втомлений", en: "tired", ru: "уставший", ex_no: "I feel tired after work.", ex_uk: "Я почуваюся втомленим після роботи.", en_ex: "I feel tired after work.", ru_ex: "Я чувствую себя уставшим после работы." },
            { t: "Минулий час", no: "walked", uk: "йшов/пішов", en: "walked", ru: "шёл", ex_no: "He walked to the station.", ex_uk: "Він пішов на станцію пішки.", en_ex: "He walked to the station.", ru_ex: "Он пошёл на станцию пешком." },
            { t: "Минулий час", no: "visited", uk: "відвідав", en: "visited", ru: "посетил", ex_no: "We visited London last year.", ex_uk: "Ми відвідали Лондон минулого року.", en_ex: "We visited London last year.", ru_ex: "Мы посетили Лондон в прошлом году." },
            { t: "Минулий час", no: "stayed", uk: "зупинився / залишився", en: "stayed", ru: "остановился", ex_no: "We stayed at a nice hotel.", ex_uk: "Ми зупинилися в хорошому готелі.", en_ex: "We stayed at a nice hotel.", ru_ex: "Мы остановились в хорошем отеле." },
            { t: "Минулий час", no: "watched", uk: "дивився", en: "watched", ru: "смотрел", ex_no: "I watched TV last night.", ex_uk: "Я дивився телевізор учора ввечері.", en_ex: "I watched TV last night.", ru_ex: "Я смотрел телевизор вчера вечером." },
            { t: "Здоров'я", no: "doctor", uk: "лікар", en: "doctor", ru: "врач", ex_no: "I need to see a doctor.", ex_uk: "Мені потрібно піти до лікаря.", en_ex: "I need to see a doctor.", ru_ex: "Мне нужно пойти к врачу." },
            { t: "Здоров'я", no: "medicine", uk: "ліки", en: "medicine", ru: "лекарство", ex_no: "Take this medicine three times a day.", ex_uk: "Приймай ці ліки тричі на день.", en_ex: "Take this medicine three times a day.", ru_ex: "Принимай это лекарство три раза в день." },
        ],

        // -------------------- B1 --------------------
        B1: [
            { t: "Подорожі", no: "airport", uk: "аеропорт", en: "airport", ru: "аэропорт", ex_no: "We meet at the airport.", ex_uk: "Зустрінемось в аеропорту.", en_ex: "We meet at the airport.", ru_ex: "Встретимся в аэропорту." },
            { t: "Подорожі", no: "ticket", uk: "квиток", en: "ticket", ru: "билет", ex_no: "I booked a ticket online.", ex_uk: "Я забронював квиток онлайн.", en_ex: "I booked a ticket online.", ru_ex: "Я забронировал билет онлайн." },
            { t: "Подорожі", no: "hotel", uk: "готель", en: "hotel", ru: "отель", ex_no: "The hotel is near the center.", ex_uk: "Готель біля центру.", en_ex: "The hotel is near the center.", ru_ex: "Отель рядом с центром." },
            { t: "Подорожі", no: "passport", uk: "паспорт", en: "passport", ru: "паспорт", ex_no: "Don't forget your passport.", ex_uk: "Не забудь паспорт.", en_ex: "Don't forget your passport.", ru_ex: "Не забудь паспорт." },
            { t: "Подорожі", no: "luggage", uk: "багаж", en: "luggage", ru: "багаж", ex_no: "My luggage is heavy.", ex_uk: "Мій багаж важкий.", en_ex: "My luggage is heavy.", ru_ex: "Мой багаж тяжёлый." },
            { t: "Подорожі", no: "delay", uk: "затримка", en: "delay", ru: "задержка", ex_no: "There was a delay due to weather.", ex_uk: "Через погоду сталася затримка.", en_ex: "There was a delay due to weather.", ru_ex: "Из-за погоды произошла задержка." },
            { t: "Подорожі", no: "destination", uk: "пункт призначення", en: "destination", ru: "назначение", ex_no: "Our destination is London.", ex_uk: "Наш пункт призначення — Лондон.", en_ex: "Our destination is London.", ru_ex: "Наш пункт назначения — Лондон." },
            { t: "Подорожі", no: "tourist", uk: "турист", en: "tourist", ru: "турист", ex_no: "Tourists visit the museum.", ex_uk: "Туристи відвідують музей.", en_ex: "Tourists visit the museum.", ru_ex: "Туристы посещают музей." },
            { t: "Здоров'я", no: "hospital", uk: "лікарня", en: "hospital", ru: "больница", ex_no: "He was taken to the hospital.", ex_uk: "Його відвезли до лікарні.", en_ex: "He was taken to the hospital.", ru_ex: "Его отвезли в больницу." },
            { t: "Здоров'я", no: "prescription", uk: "рецепт", en: "prescription", ru: "рецепт", ex_no: "I need a prescription for this medicine.", ex_uk: "Мені потрібен рецепт на ці ліки.", en_ex: "I need a prescription for this medicine.", ru_ex: "Мне нужен рецепт на это лекарство." },
            { t: "Здоров'я", no: "insurance", uk: "страхування", en: "insurance", ru: "страховка", ex_no: "It's wise to have travel insurance.", ex_uk: "Розумно мати туристичну страховку.", en_ex: "It's wise to have travel insurance.", ru_ex: "Разумно иметь туристическую страховку." },
            { t: "Здоров'я", no: "vaccine", uk: "вакцина", en: "vaccine", ru: "вакцина", ex_no: "Children get this vaccine for free.", ex_uk: "Діти отримують цю вакцину безкоштовно.", en_ex: "Children get this vaccine for free.", ru_ex: "Дети получают эту вакцину бесплатно." },
            { t: "Стосунки", no: "friend", uk: "друг", en: "friend", ru: "друг", ex_no: "He is my best friend.", ex_uk: "Він мій найкращий друг.", en_ex: "He is my best friend.", ru_ex: "Он мой лучший друг." },
            { t: "Стосунки", no: "partner", uk: "партнер", en: "partner", ru: "партнёр", ex_no: "I introduced my partner to my family.", ex_uk: "Я познайомив свого партнера з родиною.", en_ex: "I introduced my partner to my family.", ru_ex: "Я познакомил своего партнёра с семьёй." },
            { t: "Стосунки", no: "marriage", uk: "шлюб", en: "marriage", ru: "брак", ex_no: "They celebrated ten years of marriage.", ex_uk: "Вони відсвяткували десять років шлюбу.", en_ex: "They celebrated ten years of marriage.", ru_ex: "Они отпраздновали десять лет брака." },
            { t: "Стосунки", no: "trust", uk: "довіра", en: "trust", ru: "доверие", ex_no: "Trust is important in a relationship.", ex_uk: "Довіра важлива у стосунках.", en_ex: "Trust is important in a relationship.", ru_ex: "Доверие важно в отношениях." },
            { t: "Медіа", no: "news", uk: "новини", en: "news", ru: "новости", ex_no: "I watch the news every evening.", ex_uk: "Я дивлюся новини щовечора.", en_ex: "I watch the news every evening.", ru_ex: "Я смотрю новости каждый вечер." },
            { t: "Медіа", no: "newspaper", uk: "газета", en: "newspaper", ru: "газета", ex_no: "He reads the newspaper in the morning.", ex_uk: "Він читає газету вранці.", en_ex: "He reads the newspaper in the morning.", ru_ex: "Он читает газету утром." },
            { t: "Медіа", no: "social media", uk: "соціальні мережі", en: "social media", ru: "социальные сети", ex_no: "Young people spend time on social media.", ex_uk: "Молодь проводить час у соціальних мережах.", en_ex: "Young people spend time on social media.", ru_ex: "Молодёжь проводит время в социальных сетях." },
            { t: "Медіа", no: "podcast", uk: "подкаст", en: "podcast", ru: "подкаст", ex_no: "I listen to podcasts while exercising.", ex_uk: "Я слухаю подкасти під час тренування.", en_ex: "I listen to podcasts while exercising.", ru_ex: "Я слушаю подкасты во время тренировки." },
            { t: "Довкілля", no: "environment", uk: "довкілля", en: "environment", ru: "окружающая среда", ex_no: "We must protect the environment.", ex_uk: "Ми повинні захищати довкілля.", en_ex: "We must protect the environment.", ru_ex: "Мы должны защищать окружающую среду." },
            { t: "Довкілля", no: "climate", uk: "клімат", en: "climate", ru: "климат", ex_no: "Climate change is a global problem.", ex_uk: "Зміна клімату — глобальна проблема.", en_ex: "Climate change is a global problem.", ru_ex: "Изменение климата — глобальная проблема." },
            { t: "Довкілля", no: "pollution", uk: "забруднення", en: "pollution", ru: "загрязнение", ex_no: "Pollution harms wildlife.", ex_uk: "Забруднення шкодить дикій природі.", en_ex: "Pollution harms wildlife.", ru_ex: "Загрязнение вредит дикой природе." },
            { t: "Довкілля", no: "recycling", uk: "переробка", en: "recycling", ru: "переработка", ex_no: "Recycling is important.", ex_uk: "Переробка важлива.", en_ex: "Recycling is important.", ru_ex: "Переработка важна." },
            { t: "Довкілля", no: "waste", uk: "відходи", en: "waste", ru: "отходы", ex_no: "We sort waste into categories.", ex_uk: "Ми сортуємо сміття за категоріями.", en_ex: "We sort waste into categories.", ru_ex: "Мы сортируем отходы по категориям." },
            { t: "Дієслова", no: "understand", uk: "розуміти", en: "understand", ru: "понимать", ex_no: "I don't understand what you mean.", ex_uk: "Я не розумію, що ти маєш на увазі.", en_ex: "I don't understand what you mean.", ru_ex: "Я не понимаю, что ты имеешь в виду." },
            { t: "Дієслова", no: "explain", uk: "пояснювати", en: "explain", ru: "объяснять", ex_no: "Can you explain the rule again?", ex_uk: "Можеш пояснити правило ще раз?", en_ex: "Can you explain the rule again?", ru_ex: "Можешь объяснить правило ещё раз?" },
            { t: "Дієслова", no: "believe", uk: "вірити", en: "believe", ru: "верить", ex_no: "I believe she is right.", ex_uk: "Я вірю, що вона має рацію.", en_ex: "I believe she is right.", ru_ex: "Я верю, что она права." },
            { t: "Дієслова", no: "try", uk: "пробувати", en: "try", ru: "пытаться", ex_no: "I'm trying to learn English.", ex_uk: "Я намагаюся вивчити англійську.", en_ex: "I'm trying to learn English.", ru_ex: "Я пытаюсь выучить английский." },
            { t: "Дієслова", no: "decide", uk: "вирішувати", en: "decide", ru: "решать", ex_no: "I decided to move to London.", ex_uk: "Я вирішив переїхати до Лондона.", en_ex: "I decided to move to London.", ru_ex: "Я решил переехать в Лондон." },
            { t: "Дієслова", no: "admit", uk: "визнавати", en: "admit", ru: "признавать", ex_no: "He admitted his mistake.", ex_uk: "Він визнав свою помилку.", en_ex: "He admitted his mistake.", ru_ex: "Он признал свою ошибку." },
            { t: "Дієслова", no: "avoid", uk: "уникати", en: "avoid", ru: "избегать", ex_no: "We should avoid risks.", ex_uk: "Нам слід уникати ризиків.", en_ex: "We should avoid risks.", ru_ex: "Нам следует избегать рисков." },
            { t: "Кар'єра", no: "career", uk: "кар'єра", en: "career", ru: "карьера", ex_no: "She has a successful career.", ex_uk: "Вона має успішну кар'єру.", en_ex: "She has a successful career.", ru_ex: "У неё успешная карьера." },
            { t: "Кар'єра", no: "interview", uk: "співбесіда", en: "interview", ru: "собеседование", ex_no: "The interview went well.", ex_uk: "Співбесіда пройшла добре.", en_ex: "The interview went well.", ru_ex: "Собеседование прошло хорошо." },
            { t: "Кар'єра", no: "colleague", uk: "колега", en: "colleague", ru: "коллега", ex_no: "My colleagues are friendly.", ex_uk: "Мої колеги привітні.", en_ex: "My colleagues are friendly.", ru_ex: "Мои коллеги приветливы." },
            { t: "Кар'єра", no: "application", uk: "заявка", en: "application", ru: "заявка", ex_no: "I submitted my application yesterday.", ex_uk: "Я подав заявку вчора.", en_ex: "I submitted my application yesterday.", ru_ex: "Я подал заявку вчера." },
        ],

        // -------------------- B2 --------------------
        B2: [
            { t: "Політика", no: "government", uk: "уряд", en: "government", ru: "правительство", ex_no: "The government presented a new budget.", ex_uk: "Уряд представив новий бюджет.", en_ex: "The government presented a new budget.", ru_ex: "Правительство представило новый бюджет." },
            { t: "Політика", no: "election", uk: "вибори", en: "election", ru: "выборы", ex_no: "The election is next month.", ex_uk: "Вибори наступного місяця.", en_ex: "The election is next month.", ru_ex: "Выборы в следующем месяце." },
            { t: "Політика", no: "democracy", uk: "демократія", en: "democracy", ru: "демократия", ex_no: "Freedom of speech is a cornerstone of democracy.", ex_uk: "Свобода слова — основа демократії.", en_ex: "Freedom of speech is a cornerstone of democracy.", ru_ex: "Свобода слова — основа демократии." },
            { t: "Політика", no: "opposition", uk: "опозиція", en: "opposition", ru: "оппозиция", ex_no: "The opposition criticized the proposal.", ex_uk: "Опозиція розкритикувала пропозицію.", en_ex: "The opposition criticized the proposal.", ru_ex: "Оппозиция раскритиковала предложение." },
            { t: "Економіка", no: "economy", uk: "економіка", en: "economy", ru: "экономика", ex_no: "The economy is growing slowly.", ex_uk: "Економіка зростає повільно.", en_ex: "The economy is growing slowly.", ru_ex: "Экономика растёт медленно." },
            { t: "Економіка", no: "market", uk: "ринок", en: "market", ru: "рынок", ex_no: "The market reacted to the news.", ex_uk: "Ринок відреагував на новину.", en_ex: "The market reacted to the news.", ru_ex: "Рынок отреагировал на новость." },
            { t: "Економіка", no: "inflation", uk: "інфляція", en: "inflation", ru: "инфляция", ex_no: "Inflation has risen sharply.", ex_uk: "Інфляція різко зросла.", en_ex: "Inflation has risen sharply.", ru_ex: "Инфляция резко выросла." },
            { t: "Економіка", no: "investment", uk: "інвестиція", en: "investment", ru: "инвестиция", ex_no: "Long-term investment is important.", ex_uk: "Довгострокові інвестиції важливі.", en_ex: "Long-term investment is important.", ru_ex: "Долгосрочные инвестиции важны." },
            { t: "Наука", no: "research", uk: "дослідження", en: "research", ru: "исследование", ex_no: "New research shows surprising results.", ex_uk: "Нове дослідження показує несподівані результати.", en_ex: "New research shows surprising results.", ru_ex: "Новое исследование показывает неожиданные результаты." },
            { t: "Наука", no: "theory", uk: "теорія", en: "theory", ru: "теория", ex_no: "The theory was confirmed by experiments.", ex_uk: "Теорію підтвердили експерименти.", en_ex: "The theory was confirmed by experiments.", ru_ex: "Теорию подтвердили эксперименты." },
            { t: "Наука", no: "experiment", uk: "експеримент", en: "experiment", ru: "эксперимент", ex_no: "They conducted a controlled experiment.", ex_uk: "Вони провели контрольований експеримент.", en_ex: "They conducted a controlled experiment.", ru_ex: "Они провели контролируемый эксперимент." },
            { t: "Наука", no: "data", uk: "дані", en: "data", ru: "данные", ex_no: "Data was collected over several months.", ex_uk: "Дані збирали протягом кількох місяців.", en_ex: "Data was collected over several months.", ru_ex: "Данные собирали в течение нескольких месяцев." },
            { t: "Культура", no: "art", uk: "мистецтво", en: "art", ru: "искусство", ex_no: "The exhibition shows modern art.", ex_uk: "Виставка демонструє сучасне мистецтво.", en_ex: "The exhibition shows modern art.", ru_ex: "Выставка демонстрирует современное искусство." },
            { t: "Культура", no: "literature", uk: "література", en: "literature", ru: "литература", ex_no: "She studies English literature.", ex_uk: "Вона вивчає англійську літературу.", en_ex: "She studies English literature.", ru_ex: "Она изучает английскую литературу." },
            { t: "Культура", no: "author", uk: "автор", en: "author", ru: "автор", ex_no: "The author received recognition.", ex_uk: "Автор отримав визнання.", en_ex: "The author received recognition.", ru_ex: "Автор получил признание." },
            { t: "Дієслова", no: "influence", uk: "впливати", en: "influence", ru: "влиять", ex_no: "The media influences public opinion.", ex_uk: "ЗМІ впливають на громадську думку.", en_ex: "The media influences public opinion.", ru_ex: "СМИ влияют на общественное мнение." },
            { t: "Дієслова", no: "assess", uk: "оцінювати", en: "assess", ru: "оценивать", ex_no: "We need to assess the situation.", ex_uk: "Нам потрібно оцінити ситуацію.", en_ex: "We need to assess the situation.", ru_ex: "Нам нужно оценить ситуацию." },
            { t: "Дієслова", no: "develop", uk: "розвивати", en: "develop", ru: "развивать", ex_no: "The company is developing new products.", ex_uk: "Компанія розробляє нові продукти.", en_ex: "The company is developing new products.", ru_ex: "Компания разрабатывает новые продукты." },
            { t: "Дієслова", no: "present", uk: "представляти", en: "present", ru: "представлять", ex_no: "She presented the results to the board.", ex_uk: "Вона представила результати правлінню.", en_ex: "She presented the results to the board.", ru_ex: "Она представила результаты правлению." },
            { t: "Дієслова", no: "analyze", uk: "аналізувати", en: "analyze", ru: "анализировать", ex_no: "We need to analyze the data.", ex_uk: "Нам потрібно проаналізувати дані.", en_ex: "We need to analyze the data.", ru_ex: "Нам нужно проанализировать данные." },
            { t: "Дієслова", no: "conclude", uk: "робити висновок", en: "conclude", ru: "делать вывод", ex_no: "The report concludes that the measure worked.", ex_uk: "Звіт робить висновок, що захід спрацював.", en_ex: "The report concludes that the measure worked.", ru_ex: "Отчёт делает вывод, что мера сработала." },
            { t: "Бізнес", no: "business", uk: "бізнес", en: "business", ru: "бизнес", ex_no: "Business is going well this year.", ex_uk: "Цього року бізнес іде добре.", en_ex: "Business is going well this year.", ru_ex: "В этом году бизнес идёт хорошо." },
            { t: "Бізнес", no: "strategy", uk: "стратегія", en: "strategy", ru: "стратегия", ex_no: "We need a new strategy.", ex_uk: "Нам потрібна нова стратегія.", en_ex: "We need a new strategy.", ru_ex: "Нам нужна новая стратегия." },
            { t: "Бізнес", no: "competition", uk: "конкуренція", en: "competition", ru: "конкуренция", ex_no: "Competition is intense.", ex_uk: "Конкуренція є жорсткою.", en_ex: "Competition is intense.", ru_ex: "Конкуренция жёсткая." },
            { t: "Бізнес", no: "negotiation", uk: "переговори", en: "negotiation", ru: "переговоры", ex_no: "Negotiations are underway.", ex_uk: "Переговори тривають.", en_ex: "Negotiations are underway.", ru_ex: "Переговоры продолжаются." },
            { t: "Медицина", no: "symptom", uk: "симптом", en: "symptom", ru: "симптом", ex_no: "Fever is a common symptom.", ex_uk: "Температура — поширений симптом.", en_ex: "Fever is a common symptom.", ru_ex: "Температура — распространённый симптом." },
            { t: "Медицина", no: "chronic", uk: "хронічний", en: "chronic", ru: "хронический", ex_no: "He has a chronic illness.", ex_uk: "Він має хронічну хворобу.", en_ex: "He has a chronic illness.", ru_ex: "У него хроническое заболевание." },
            { t: "Медицина", no: "epidemic", uk: "епідемія", en: "epidemic", ru: "эпидемия", ex_no: "The epidemic spread quickly.", ex_uk: "Епідемія швидко поширилася.", en_ex: "The epidemic spread quickly.", ru_ex: "Эпидемия быстро распространилась." },
            { t: "Медицина", no: "prevention", uk: "профілактика", en: "prevention", ru: "профилактика", ex_no: "Prevention is better than cure.", ex_uk: "Профілактика краща за лікування.", en_ex: "Prevention is better than cure.", ru_ex: "Профилактика лучше лечения." },
        ],

        // -------------------- C1 --------------------
        C1: [
            { t: "Дискурс", no: "however", uk: "однак", en: "however", ru: "однако", ex_no: "The results were promising; however, there is still work to do.", ex_uk: "Результати були обнадійливі; однак роботи ще багато.", en_ex: "The results were promising; however, there is still work to do.", ru_ex: "Результаты были обнадёживающими; однако работы ещё много." },
            { t: "Дискурс", no: "moreover", uk: "крім того", en: "moreover", ru: "кроме того", ex_no: "The project is expensive, and moreover time-consuming.", ex_uk: "Проєкт дорогий, і до того ж забирає багато часу.", en_ex: "The project is expensive, and moreover time-consuming.", ru_ex: "Проект дорогой, и к тому же отнимает много времени." },
            { t: "Дискурс", no: "consequently", uk: "отже", en: "consequently", ru: "следовательно", ex_no: "Demand fell, and prices consequently dropped.", ex_uk: "Попит впав, і ціни, відповідно, знизилися.", en_ex: "Demand fell, and prices consequently dropped.", ru_ex: "Спрос упал, и цены, соответственно, снизились." },
            { t: "Дискурс", no: "despite", uk: "незважаючи на", en: "despite", ru: "несмотря на", ex_no: "Despite the challenges, they completed the project.", ex_uk: "Незважаючи на труднощі, вони завершили проєкт.", en_ex: "Despite the challenges, they completed the project.", ru_ex: "Несмотря на трудности, они завершили проект." },
            { t: "Дискурс", no: "in other words", uk: "іншими словами", en: "in other words", ru: "другими словами", ex_no: "In other words, the situation is more complicated.", ex_uk: "Іншими словами, ситуація складніша.", en_ex: "In other words, the situation is more complicated.", ru_ex: "Другими словами, ситуация сложнее." },
            { t: "Нюанси", no: "imply", uk: "натякати", en: "imply", ru: "намекать", ex_no: "The report implies that several factors are at play.", ex_uk: "Звіт натякає, що діють кілька факторів.", en_ex: "The report implies that several factors are at play.", ru_ex: "Отчёт намекает, что действуют несколько факторов." },
            { t: "Нюанси", no: "emphasize", uk: "підкреслювати", en: "emphasize", ru: "подчёркивать", ex_no: "The speaker emphasized the importance of cooperation.", ex_uk: "Доповідач підкреслив важливість співпраці.", en_ex: "The speaker emphasized the importance of cooperation.", ru_ex: "Докладчик подчеркнул важность сотрудничества." },
            { t: "Нюанси", no: "substantiate", uk: "обґрунтовувати", en: "substantiate", ru: "обосновывать", ex_no: "You need to substantiate your claim with evidence.", ex_uk: "Тобі потрібно обґрунтувати своє твердження доказами.", en_ex: "You need to substantiate your claim with evidence.", ru_ex: "Тебе нужно обосновать своё утверждение доказательствами." },
            { t: "Нюанси", no: "nuanced", uk: "нюансований", en: "nuanced", ru: "нюансированный", ex_no: "The debate requires a more nuanced approach.", ex_uk: "Дебати потребують більш нюансованого підходу.", en_ex: "The debate requires a more nuanced approach.", ru_ex: "Дебаты требуют более нюансированного подхода." },
            { t: "Нюанси", no: "comprehensive", uk: "всеохопний", en: "comprehensive", ru: "всеобъемлющий", ex_no: "This is a comprehensive study.", ex_uk: "Це всеохопне дослідження.", en_ex: "This is a comprehensive study.", ru_ex: "Это всеобъемлющее исследование." },
            { t: "Академічна", no: "hypothesis", uk: "гіпотеза", en: "hypothesis", ru: "гипотеза", ex_no: "The researchers tested the hypothesis.", ex_uk: "Науковці перевірили гіпотезу.", en_ex: "The researchers tested the hypothesis.", ru_ex: "Учёные проверили гипотезу." },
            { t: "Академічна", no: "methodology", uk: "методологія", en: "methodology", ru: "методология", ex_no: "The methodology is clearly described.", ex_uk: "Методологія чітко описана.", en_ex: "The methodology is clearly described.", ru_ex: "Методология четко описана." },
            { t: "Академічна", no: "perspective", uk: "перспектива", en: "perspective", ru: "перспектива", ex_no: "From a historical perspective, the event was significant.", ex_uk: "З історичної перспективи подія була значущою.", en_ex: "From a historical perspective, the event was significant.", ru_ex: "С исторической точки зрения событие было значимым." },
            { t: "Академічна", no: "source criticism", uk: "критика джерел", en: "source criticism", ru: "критика источников", ex_no: "Good source criticism is crucial.", ex_uk: "Гарна критика джерел є вирішальною.", en_ex: "Good source criticism is crucial.", ru_ex: "Хорошая критика источников имеет решающее значение." },
            { t: "Філософія", no: "existence", uk: "існування", en: "existence", ru: "существование", ex_no: "The question of existence is eternal.", ex_uk: "Питання про існування вічне.", en_ex: "The question of existence is eternal.", ru_ex: "Вопрос о существовании вечен." },
            { t: "Філософія", no: "consciousness", uk: "свідомість", en: "consciousness", ru: "сознание", ex_no: "Consciousness is a complex phenomenon.", ex_uk: "Свідомість — складне явище.", en_ex: "Consciousness is a complex phenomenon.", ru_ex: "Сознание — сложное явление." },
            { t: "Філософія", no: "ethics", uk: "етика", en: "ethics", ru: "этика", ex_no: "Ethics deals with what is right and wrong.", ex_uk: "Етика стосується того, що правильно, а що ні.", en_ex: "Ethics deals with what is right and wrong.", ru_ex: "Этика касается того, что правильно, а что нет." },
            { t: "Лінгвістика", no: "syntax", uk: "синтаксис", en: "syntax", ru: "синтаксис", ex_no: "Syntax is the study of sentence structure.", ex_uk: "Синтаксис — це вивчення структури речень.", en_ex: "Syntax is the study of sentence structure.", ru_ex: "Синтаксис — это изучение структуры предложений." },
            { t: "Лінгвістика", no: "semantics", uk: "семантика", en: "semantics", ru: "семантика", ex_no: "Semantics deals with meaning.", ex_uk: "Семантика займається значенням.", en_ex: "Semantics deals with meaning.", ru_ex: "Семантика занимается значением." },
            { t: "Соціологія", no: "social inequality", uk: "соціальна нерівність", en: "social inequality", ru: "социальное неравенство", ex_no: "Social inequality is a major problem.", ex_uk: "Соціальна нерівність — велика проблема.", en_ex: "Social inequality is a major problem.", ru_ex: "Социальное неравенство — большая проблема." },
            { t: "Соціологія", no: "integration", uk: "інтеграція", en: "integration", ru: "интеграция", ex_no: "Integration of immigrants is important.", ex_uk: "Інтеграція іммігрантів важлива.", en_ex: "Integration of immigrants is important.", ru_ex: "Интеграция иммигрантов важна." },
            { t: "Соціологія", no: "diversity", uk: "різноманіття", en: "diversity", ru: "разнообразие", ex_no: "Diversity enriches society.", ex_uk: "Різноманіття збагачує суспільство.", en_ex: "Diversity enriches society.", ru_ex: "Разнообразие обогащает общество." },
            { t: "Психологія", no: "cognition", uk: "когніція", en: "cognition", ru: "когниция", ex_no: "Cognition includes thinking and memory.", ex_uk: "Когніція охоплює мислення та пам'ять.", en_ex: "Cognition includes thinking and memory.", ru_ex: "Когниция охватывает мышление и память." },
            { t: "Психологія", no: "emotion", uk: "емоція", en: "emotion", ru: "эмоция", ex_no: "Emotions influence our choices.", ex_uk: "Емоції впливають на наш вибір.", en_ex: "Emotions influence our choices.", ru_ex: "Эмоции влияют на наш выбор." },
            { t: "Психологія", no: "behavior", uk: "поведінка", en: "behavior", ru: "поведение", ex_no: "His behavior was unexpected.", ex_uk: "Його поведінка була несподіваною.", en_ex: "His behavior was unexpected.", ru_ex: "Его поведение было неожиданным." },
            { t: "Психологія", no: "motivation", uk: "мотивація", en: "motivation", ru: "мотивация", ex_no: "Motivation comes from within.", ex_uk: "Мотивація походить зсередини.", en_ex: "Motivation comes from within.", ru_ex: "Мотивация исходит изнутри." },
        ],

        // -------------------- C2 --------------------
        C2: [
            { t: "Ідіоми", no: "to kill two birds with one stone", uk: "убити двох зайців", en: "to kill two birds with one stone", ru: "убить двух зайцев", ex_no: "By working from home I kill two birds with one stone.", ex_uk: "Працюючи з дому, я вбиваю двох зайців.", en_ex: "By working from home I kill two birds with one stone.", ru_ex: "Работая из дома, я убиваю двух зайцев." },
            { t: "Ідіоми", no: "to bite the bullet", uk: "проковтнути гірку пігулку", en: "to bite the bullet", ru: "проглотить горькую пилюлю", ex_no: "I had to bite the bullet and admit I was wrong.", ex_uk: "Мені довелося проковтнути гірку пігулку і визнати, що я помилявся.", en_ex: "I had to bite the bullet and admit I was wrong.", ru_ex: "Мне пришлось проглотить горькую пилюлю и признать, что я ошибался." },
            { t: "Ідіоми", no: "to cast pearls before swine", uk: "метати бісер перед свинями", en: "to cast pearls before swine", ru: "метать бисер перед свиньями", ex_no: "Explaining it to him is like casting pearls before swine.", ex_uk: "Пояснювати йому це — все одно що метати бісер перед свинями.", en_ex: "Explaining it to him is like casting pearls before swine.", ru_ex: "Объяснять ему это — всё равно что метать бисер перед свиньями." },
            { t: "Ідіоми", no: "to hold great sway", uk: "мати великий вплив", en: "to hold great sway", ru: "иметь большое влияние", ex_no: "He holds great sway in the industry.", ex_uk: "Він має величезний вплив у галузі.", en_ex: "He holds great sway in the industry.", ru_ex: "Он имеет большое влияние в отрасли." },
            { t: "Ідіоми", no: "to paint a bleak picture", uk: "згущувати фарби", en: "to paint a bleak picture", ru: "сгущать краски", ex_no: "Don't paint a bleak picture; it'll work out.", ex_uk: "Не згущуй фарби; все владнається.", en_ex: "Don't paint a bleak picture; it'll work out.", ru_ex: "Не сгущай краски; всё уладится." },
            { t: "Ідіоми", no: "to throw in the towel", uk: "здатися", en: "to throw in the towel", ru: "сдаться", ex_no: "After several defeats, he threw in the towel.", ex_uk: "Після кількох поразок він здався.", en_ex: "After several defeats, he threw in the towel.", ru_ex: "После нескольких поражений он сдался." },
            { t: "Ідіоми", no: "to fall for a trick", uk: "попастися на гачок", en: "to fall for a trick", ru: "попасться на удочку", ex_no: "He fell for the scam and lost money.", ex_uk: "Він попався на шахрайство і втратив гроші.", en_ex: "He fell for the scam and lost money.", ru_ex: "Он попался на аферу и потерял деньги." },
            { t: "Стилістика", no: "fiction", uk: "художня література", en: "fiction", ru: "художественная литература", ex_no: "She prefers fiction to non-fiction.", ex_uk: "Вона надає перевагу художній літературі перед науковою.", en_ex: "She prefers fiction to non-fiction.", ru_ex: "Она предпочитает художественную литературу научной." },
            { t: "Стилістика", no: "satire", uk: "сатира", en: "satire", ru: "сатира", ex_no: "The show uses satire to comment on politics.", ex_uk: "Шоу використовує сатиру для коментування політики.", en_ex: "The show uses satire to comment on politics.", ru_ex: "Шоу использует сатиру для комментирования политики." },
            { t: "Стилістика", no: "irony", uk: "іронія", en: "irony", ru: "ирония", ex_no: "His comment was meant as irony.", ex_uk: "Його коментар був іронією.", en_ex: "His comment was meant as irony.", ru_ex: "Его комментарий был иронией." },
            { t: "Рідкісна лексика", no: "transient", uk: "минущий", en: "transient", ru: "преходящий", ex_no: "Fame can be transient.", ex_uk: "Слава може бути минущою.", en_ex: "Fame can be transient.", ru_ex: "Слава может быть преходящей." },
            { t: "Рідкісна лексика", no: "unpredictable", uk: "непередбачуваний", en: "unpredictable", ru: "непредсказуемый", ex_no: "The weather is unpredictable.", ex_uk: "Погода непередбачувана.", en_ex: "The weather is unpredictable.", ru_ex: "Погода непредсказуема." },
            { t: "Рідкісна лексика", no: "inevitable", uk: "неминучий", en: "inevitable", ru: "неизбежный", ex_no: "The conflict seemed inevitable.", ex_uk: "Конфлікт здавався неминучим.", en_ex: "The conflict seemed inevitable.", ru_ex: "Конфликт казался неизбежным." },
            { t: "Риторика", no: "rhetoric", uk: "риторика", en: "rhetoric", ru: "риторика", ex_no: "Rhetoric is the art of persuasion.", ex_uk: "Риторика — це мистецтво переконання.", en_ex: "Rhetoric is the art of persuasion.", ru_ex: "Риторика — это искусство убеждения." },
            { t: "Риторика", no: "argumentation", uk: "аргументація", en: "argumentation", ru: "аргументация", ex_no: "His argumentation was solid.", ex_uk: "Його аргументація була вагомою.", en_ex: "His argumentation was solid.", ru_ex: "Его аргументация была убедительной." },
            { t: "Риторика", no: "appeal", uk: "звернення", en: "appeal", ru: "апелляция", ex_no: "The appeal to emotions was strong.", ex_uk: "Звернення до емоцій було сильним.", en_ex: "The appeal to emotions was strong.", ru_ex: "Обращение к эмоциям было сильным." },
            { t: "Літературознавство", no: "motif", uk: "мотив", en: "motif", ru: "мотив", ex_no: "Love is a central motif in the book.", ex_uk: "Кохання — центральний мотив у книзі.", en_ex: "Love is a central motif in the book.", ru_ex: "Любовь — центральный мотив в книге." },
            { t: "Літературознавство", no: "theme", uk: "тема", en: "theme", ru: "тема", ex_no: "The theme of the novel is loneliness.", ex_uk: "Тема роману — самотність.", en_ex: "The theme of the novel is loneliness.", ru_ex: "Тема романа — одиночество." },
            { t: "Літературознавство", no: "symbolism", uk: "символіка", en: "symbolism", ru: "символика", ex_no: "The poem is rich in symbolism.", ex_uk: "Вірш багатий на символіку.", en_ex: "The poem is rich in symbolism.", ru_ex: "Стихотворение богато на символику." },
            { t: "Абстрактне", no: "contrast", uk: "контраст", en: "contrast", ru: "контраст", ex_no: "The contrast between rich and poor is stark.", ex_uk: "Контраст між багатими та бідними різкий.", en_ex: "The contrast between rich and poor is stark.", ru_ex: "Контраст между богатыми и бедными резкий." },
            { t: "Абстрактне", no: "exclude", uk: "виключати", en: "exclude", ru: "исключать", ex_no: "We must not exclude anyone.", ex_uk: "Ми не повинні нікого виключати.", en_ex: "We must not exclude anyone.", ru_ex: "Мы не должны никого исключать." },
            { t: "Абстрактне", no: "include", uk: "включати", en: "include", ru: "включать", ex_no: "Everyone should be included.", ex_uk: "Усі повинні бути включені.", en_ex: "Everyone should be included.", ru_ex: "Все должны быть включены." },
            { t: "Абстрактне", no: "context", uk: "контекст", en: "context", ru: "контекст", ex_no: "Without context, it's hard to understand.", ex_uk: "Без контексту важко зрозуміти.", en_ex: "Without context, it's hard to understand.", ru_ex: "Без контекста трудно понять." },
            { t: "Абстрактне", no: "reflect", uk: "відображати", en: "reflect", ru: "отражать", ex_no: "The conversation reflects social changes.", ex_uk: "Розмова відображає соціальні зміни.", en_ex: "The conversation reflects social changes.", ru_ex: "Разговор отражает социальные изменения." },
            { t: "Абстрактне", no: "elaborate", uk: "деталізувати", en: "elaborate", ru: "детализировать", ex_no: "Can you elaborate on that point?", ex_uk: "Можеш детальніше розкрити цей пункт?", en_ex: "Can you elaborate on that point?", ru_ex: "Можешь детальнее раскрыть этот пункт?" },
        ]
    };

    // =====================================================================
    //  GRAMMAR – ГРАМАТИКА АНГЛІЙСЬКОЇ (розширена)
    // =====================================================================
    const GRAMMAR = [
        // A1
        {
            id: "en_gr1", level: "A1",
            title: "Дієслово 'to be' (am/is/are)",
            exp: "У теперішньому часі 'to be' змінюється залежно від особи: I am, he/she/it is, you/we/they are.",
            table: { head: ["Pronoun", "Form"], rows: [["I", "am"], ["he / she / it", "is"], ["you / we / they", "are"]] },
            ex: { q: "Оберіть правильну форму: She ___ a doctor.", opts: ["am", "is", "are"], a: 1 },
            title_en: "The verb 'to be' (am/is/are)",
            title_ru: "Глагол 'to be' (am/is/are)",
            exp_en: "In the present tense, 'to be' changes: I am, he/she/it is, you/we/they are.",
            exp_ru: "В настоящем времени 'to be' меняется: I am, he/she/it is, you/we/they are.",
            head_en: ["Pronoun", "Form"],
            head_ru: ["Местоимение", "Форма"],
            q_en: "Choose the correct form: She ___ a doctor.",
            q_ru: "Выберите правильную форму: She ___ a doctor.",
        },
        {
            id: "en_gr2", level: "A1",
            title: "Множина іменників (-s)",
            exp: "Більшість іменників у множині отримують закінчення -s.",
            table: { head: ["Singular", "Plural"], rows: [["a book", "books"], ["a car", "cars"], ["a house", "houses"]] },
            ex: { q: "Множина від 'apple'", opts: ["apples", "appleis", "applees"], a: 0 },
            title_en: "Plural nouns (-s)",
            title_ru: "Множественное число существительных (-s)",
            exp_en: "Most nouns form the plural by adding -s.",
            exp_ru: "Большинство существительных образуют множественное число, добавляя -s.",
            head_en: ["Singular", "Plural"],
            head_ru: ["Единственное", "Множественное"],
            q_en: "Plural of 'apple'",
            q_ru: "Множественное число от 'apple'",
        },
        // A2
        {
            id: "en_gr3", level: "A2",
            title: "Минулий час правильних дієслів (-ed)",
            exp: "Правильні дієслова в минулому часі отримують закінчення -ed.",
            table: { head: ["Present", "Past"], rows: [["work", "worked"], ["play", "played"], ["watch", "watched"]] },
            ex: { q: "Минулий час від 'walk'", opts: ["walked", "walkd", "walkied"], a: 0 },
            title_en: "Past tense of regular verbs (-ed)",
            title_ru: "Прошедшее время правильных глаголов (-ed)",
            exp_en: "Regular verbs form the past tense by adding -ed.",
            exp_ru: "Правильные глаголы образуют прошедшее время, добавляя -ed.",
            head_en: ["Present", "Past"],
            head_ru: ["Настоящее", "Прошедшее"],
            q_en: "Past tense of 'walk'",
            q_ru: "Прошедшее время от 'walk'",
        },
        {
            id: "en_gr4", level: "A2",
            title: "Модальні дієслова (can, must, should)",
            exp: "Модальні дієслова виражають можливість, необхідність, пораду. Після них вживається інфінітив без 'to'.",
            table: { head: ["Modal", "Meaning"], rows: [["can", "здатність / дозвіл"], ["must", "обов'язок"], ["should", "рекомендація"]] },
            ex: { q: "Оберіть правильне модальне дієслово: You ___ wear a seatbelt.", opts: ["can", "must", "should"], a: 1 },
            title_en: "Modal verbs (can, must, should)",
            title_ru: "Модальные глаголы (can, must, should)",
            exp_en: "Modal verbs express ability, obligation, or advice. They are followed by the infinitive without 'to'.",
            exp_ru: "Модальные глаголы выражают способность, необходимость, совет. За ними следует инфинитив без 'to'.",
            head_en: ["Modal", "Meaning"],
            head_ru: ["Модальный", "Значение"],
            q_en: "Choose the correct modal: You ___ wear a seatbelt.",
            q_ru: "Выберите правильный модальный глагол: You ___ wear a seatbelt.",
        },
        // B1
        {
            id: "en_gr5", level: "B1",
            title: "Present Perfect (have/has + past participle)",
            exp: "Present Perfect використовується для дій, що відбулися в минулому, але мають зв'язок з теперішнім.",
            table: { head: ["Subject", "Auxiliary", "Participle"], rows: [["I", "have", "visited"], ["She", "has", "visited"], ["They", "have", "visited"]] },
            ex: { q: "Оберіть правильну форму: I ___ (see) that film.", opts: ["have seen", "has seen", "saw"], a: 0 },
            title_en: "Present Perfect",
            title_ru: "Настоящее совершенное время (Present Perfect)",
            exp_en: "Present Perfect is used for past actions connected to the present.",
            exp_ru: "Present Perfect используется для действий, произошедших в прошлом, но имеющих связь с настоящим.",
            head_en: ["Subject", "Auxiliary", "Participle"],
            head_ru: ["Подлежащее", "Вспомогательный", "Причастие"],
            q_en: "Choose the correct form: I ___ (see) that film.",
            q_ru: "Выберите правильную форму: I ___ (see) that film.",
        },
        {
            id: "en_gr6", level: "B1",
            title: "Passive Voice (present simple)",
            exp: "Пасивний стан утворюється з 'to be' + past participle.",
            table: { head: ["Active", "Passive"], rows: [["The cat eats the fish.", "The fish is eaten by the cat."]] },
            ex: { q: "Оберіть пасивну форму: The book ___ by the student.", opts: ["is read", "reads", "is reading"], a: 0 },
            title_en: "Passive Voice (present simple)",
            title_ru: "Пассивный залог (настоящее время)",
            exp_en: "Passive voice is formed with 'to be' + past participle.",
            exp_ru: "Пассивный залог образуется с помощью 'to be' + причастие прошедшего времени.",
            head_en: ["Active", "Passive"],
            head_ru: ["Актив", "Пассив"],
            q_en: "Choose the passive: The book ___ by the student.",
            q_ru: "Выберите пассивную форму: The book ___ by the student.",
        },
        {
            id: "en_gr7", level: "B1",
            title: "Conditional (if-clause type 1)",
            exp: "Умовні речення 1-го типу (реальна умова): if + present simple, will + infinitive.",
            table: { head: ["If-clause", "Main clause"], rows: [["If it rains", "I will stay at home."]] },
            ex: { q: "Доповніть: If she ___ (study) hard, she will pass.", opts: ["studies", "studied", "will study"], a: 0 },
            title_en: "Conditional (type 1)",
            title_ru: "Условное предложение (1-й тип)",
            exp_en: "Type 1 conditional: if + present simple, will + infinitive.",
            exp_ru: "Условное предложение 1-го типа: if + present simple, will + infinitive.",
            head_en: ["If-clause", "Main clause"],
            head_ru: ["Придаточное условия", "Главное предложение"],
            q_en: "Complete: If she ___ (study) hard, she will pass.",
            q_ru: "Дополните: If she ___ (study) hard, she will pass.",
        },
        // B2
        {
            id: "en_gr8", level: "B2",
            title: "Reported Speech (indirect speech)",
            exp: "У непрямій мові змінюються часи та займенники.",
            table: { head: ["Direct", "Indirect"], rows: [["\"I am tired,\" she said.", "She said she was tired."]] },
            ex: { q: "Оберіть непряму мову: He said, 'I will come.'", opts: ["He said he will come.", "He said he would come.", "He said he comes."], a: 1 },
            title_en: "Reported Speech",
            title_ru: "Косвенная речь",
            exp_en: "In reported speech, tenses and pronouns change.",
            exp_ru: "В косвенной речи меняются времена и местоимения.",
            head_en: ["Direct", "Indirect"],
            head_ru: ["Прямая", "Косвенная"],
            q_en: "Choose the indirect speech: He said, 'I will come.'",
            q_ru: "Выберите косвенную речь: He said, 'I will come.'",
        },
        {
            id: "en_gr9", level: "B2",
            title: "Conditional (type 3)",
            exp: "Умовні речення 3-го типу (нереальна умова в минулому): if + past perfect, would have + past participle.",
            table: { head: ["If-clause", "Main clause"], rows: [["If I had known", "I would have helped."]] },
            ex: { q: "Доповніть: If we ___ (arrive) earlier, we would have seen the show.", opts: ["arrived", "had arrived", "would arrive"], a: 1 },
            title_en: "Conditional (type 3)",
            title_ru: "Условное предложение (3-й тип)",
            exp_en: "Type 3 conditional: if + past perfect, would have + past participle.",
            exp_ru: "Условное предложение 3-го типа: if + past perfect, would have + past participle.",
            head_en: ["If-clause", "Main clause"],
            head_ru: ["Придаточное условия", "Главное предложение"],
            q_en: "Complete: If we ___ (arrive) earlier, we would have seen the show.",
            q_ru: "Дополните: If we ___ (arrive) earlier, we would have seen the show.",
        },
        // C1
        {
            id: "en_gr10", level: "C1",
            title: "Inversion (negative adverbials)",
            exp: "Інверсія з негативними прислівниками (never, seldom, not only тощо): допоміжне дієслово перед підметом.",
            table: { head: ["Normal", "Inverted"], rows: [["I have never seen such a thing.", "Never have I seen such a thing."]] },
            ex: { q: "Оберіть правильну інверсію: Not only ___ late, but he also forgot the documents.", opts: ["was he", "he was", "were he"], a: 0 },
            title_en: "Inversion (negative adverbials)",
            title_ru: "Инверсия с отрицательными наречиями",
            exp_en: "Inversion places the auxiliary verb before the subject after negative adverbs.",
            exp_ru: "Инверсия ставит вспомогательный глагол перед подлежащим после отрицательных наречий.",
            head_en: ["Normal", "Inverted"],
            head_ru: ["Обычный порядок", "Инверсия"],
            q_en: "Choose the correct inversion: Not only ___ late, but he also forgot the documents.",
            q_ru: "Выберите правильную инверсию: Not only ___ late, but he also forgot the documents.",
        },
        {
            id: "en_gr11", level: "C1",
            title: "Subjunctive",
            exp: "Стан умовного способу для вираження бажання, пропозиції: 'I wish', 'It's important that' + bare infinitive.",
            table: { head: ["Pattern", "Example"], rows: [["I wish + past simple", "I wish I were rich."], ["It's important that + subjunctive", "It's important that he be on time."]] },
            ex: { q: "Оберіть правильну форму: I wish I ___ (be) there.", opts: ["was", "were", "had been"], a: 1 },
            title_en: "Subjunctive",
            title_ru: "Сослагательное наклонение",
            exp_en: "Used to express wishes or importance: I wish, It's important that + bare infinitive.",
            exp_ru: "Используется для выражения желания или важности: I wish, It's important that + инфинитив без to.",
            head_en: ["Pattern", "Example"],
            head_ru: ["Конструкция", "Пример"],
            q_en: "Choose the correct form: I wish I ___ (be) there.",
            q_ru: "Выберите правильную форму: I wish I ___ (be) there.",
        },
        // C2
        {
            id: "en_gr12", level: "C2",
            title: "Modal perfect (must have, might have, etc.)",
            exp: "Модальні дієслова + have + past participle виражають припущення про минуле.",
            table: { head: ["Modal perfect", "Usage"], rows: [["must have done", "strong probability"], ["might have done", "possibility"], ["should have done", "regret"]] },
            ex: { q: "Оберіть правильний варіант: She ___ (forget) the keys; she looks worried.", opts: ["must have forgotten", "might have forgotten", "should have forgotten"], a: 0 },
            title_en: "Modal perfect",
            title_ru: "Модальные глаголы в перфекте",
            exp_en: "Modal + have + past participle expresses speculation about the past.",
            exp_ru: "Модальный глагол + have + причастие прошедшего времени выражает предположение о прошлом.",
            head_en: ["Modal perfect", "Usage"],
            head_ru: ["Модальный перфект", "Значение"],
            q_en: "Choose the correct: She ___ (forget) the keys; she looks worried.",
            q_ru: "Выберите правильный вариант: She ___ (forget) the keys; she looks worried.",
        },
    ];

    // =====================================================================
    //  NORSKPROVE_TASKS – ЗАВДАННЯ ДЛЯ ПРАКТИКИ (Аналог Norskprøve)
    // =====================================================================
    const NORSKPROVE_TASKS = {
        A1: {
            reading: [
                {
                    title: "Hello!",
                    text: "Hello! My name is Anna. I am from Poland. I live in London. I am a student. I like English food.",
                    questions: [
                        { q: "Where is Anna from?", opts: ["Norway", "Poland", "Sweden"], a: 1 },
                        { q: "What does Anna do?", opts: ["She is a teacher", "She is a student", "She is a doctor"], a: 1 },
                        { q: "Where does Anna live?", opts: ["Bergen", "London", "Warsaw"], a: 1 },
                    ],
                },
            ],
            listening: [],
            writing: [],
            speaking: [],
        },
        A2: {
            reading: [
                {
                    title: "A day at the shops",
                    text: "Yesterday I went to the shops. I bought bread, milk, and eggs. The shop was full of people. I met a friend and we talked. Then I went home.",
                    questions: [
                        { q: "What did I buy?", opts: ["Bread, milk, cheese", "Bread, milk, eggs", "Eggs, cheese, butter"], a: 1 },
                        { q: "Who did I meet?", opts: ["A teacher", "A friend", "A doctor"], a: 1 },
                        { q: "Where was I?", opts: ["At school", "At the shops", "At work"], a: 1 },
                    ],
                },
            ],
            listening: [],
            writing: [],
            speaking: [],
        },
        B1: {
            reading: [
                {
                    title: "Climate change",
                    text: "Climate change is a big problem. Temperatures are rising, and ice is melting. Many animals lose their habitats. We must reduce pollution and use more renewable energy.",
                    questions: [
                        { q: "What is happening to the ice?", opts: ["It is freezing", "It is melting", "It is growing"], a: 1 },
                        { q: "What can we do?", opts: ["Use more oil", "Recycle", "Drive more cars"], a: 1 },
                        { q: "What is threatening the animals?", opts: ["Loss of habitat", "Hunting", "Pollution"], a: 0 },
                    ],
                },
            ],
            listening: [],
            writing: [],
            speaking: [],
        },
        B2: {
            reading: [
                {
                    title: "The future of work",
                    text: "Automation will change many jobs. Some jobs will disappear, but new ones will appear. Digital skills will become important. Workers must be flexible and learn throughout their lives.",
                    questions: [
                        { q: "What will happen to some jobs?", opts: ["They will disappear", "They will become safer", "They will pay better"], a: 0 },
                        { q: "What will become important?", opts: ["Physical strength", "Digital skills", "Social networks"], a: 1 },
                        { q: "What can technology improve?", opts: ["Salary", "Work environment", "Leisure"], a: 1 },
                    ],
                },
            ],
            listening: [],
            writing: [],
            speaking: [],
        },
        C1: {
            reading: [
                {
                    title: "Ethics of AI",
                    text: "Artificial intelligence raises new ethical questions. Who is responsible when an algorithm makes a mistake? Should AI have rights? At the same time, AI can contribute to medical research and climate modelling.",
                    questions: [
                        { q: "What does AI raise?", opts: ["New ethical questions", "Technical problems", "Economic growth"], a: 0 },
                        { q: "What can AI contribute to?", opts: ["Research", "Warfare", "Surveillance"], a: 0 },
                        { q: "What must we develop?", opts: ["New algorithms", "Guidelines", "More data centers"], a: 1 },
                    ],
                },
            ],
            listening: [],
            writing: [],
            speaking: [],
        },
        C2: {
            reading: [
                {
                    title: "Philosophy and science",
                    text: "Science rests on philosophical assumptions. The question of what is true, and how we can know it, is fundamental. Scientific method gives us tools, but it is not infallible. Critical thinking is essential.",
                    questions: [
                        { q: "What does science rest on?", opts: ["Philosophical assumptions", "Religious dogmas", "Political power"], a: 0 },
                        { q: "What is essential?", opts: ["Critical thinking", "Academic titles", "Publication"], a: 0 },
                    ],
                },
            ],
            listening: [],
            writing: [],
            speaking: [],
        },
    };

    // =====================================================================
    //  LEVEL_TEST – ТЕСТ НА РІВЕНЬ АНГЛІЙСЬКОЇ (розширений)
    // =====================================================================
    const LEVEL_TEST = [
        // A1
        { lvl: "A1", q: "Hello! How ___ you?", opts: ["am", "is", "are"], a: 2 },
        { lvl: "A1", q: "I ___ a student.", opts: ["am", "is", "are"], a: 0 },
        { lvl: "A1", q: "She ___ a doctor.", opts: ["am", "is", "are"], a: 1 },
        { lvl: "A1", q: "They ___ from England.", opts: ["am", "is", "are"], a: 2 },
        { lvl: "A1", q: "What's your name? ___ name is John.", opts: ["My", "Your", "His"], a: 0 },
        { lvl: "A1", q: "I have ___ apple.", opts: ["a", "an", "–"], a: 1 },
        { lvl: "A1", q: "This is ___ house.", opts: ["a", "an", "–"], a: 0 },
        { lvl: "A1", q: "We ___ to school every day.", opts: ["go", "goes", "going"], a: 0 },
        { lvl: "A1", q: "She ___ coffee in the morning.", opts: ["drink", "drinks", "drinking"], a: 1 },
        { lvl: "A1", q: "I don't like ___ weather.", opts: ["a", "an", "–"], a: 2 },
        // A2
        { lvl: "A2", q: "I ___ to the cinema yesterday.", opts: ["went", "go", "gone"], a: 0 },
        { lvl: "A2", q: "She didn't ___ me.", opts: ["call", "called", "calling"], a: 0 },
        { lvl: "A2", q: "___ you like ice cream?", opts: ["Do", "Does", "Are"], a: 0 },
        { lvl: "A2", q: "We are ___ to London next week.", opts: ["go", "going", "gone"], a: 1 },
        { lvl: "A2", q: "He ___ a car.", opts: ["has", "have", "is"], a: 0 },
        { lvl: "A2", q: "I can ___ you.", opts: ["help", "helps", "helping"], a: 0 },
        { lvl: "A2", q: "She ___ speak three languages.", opts: ["can", "is", "has"], a: 0 },
        { lvl: "A2", q: "We ___ dinner at 7 pm.", opts: ["have", "has", "having"], a: 0 },
        { lvl: "A2", q: "I'm tired because I ___ work late.", opts: ["work", "worked", "working"], a: 1 },
        { lvl: "A2", q: "___ you seen my keys?", opts: ["Have", "Has", "Did"], a: 0 },
        // B1
        { lvl: "B1", q: "I've been here ___ 2015.", opts: ["for", "since", "during"], a: 1 },
        { lvl: "B1", q: "She hasn't finished her homework ___ .", opts: ["yet", "already", "just"], a: 0 },
        { lvl: "B1", q: "The book ___ by the teacher.", opts: ["writes", "is written", "has written"], a: 1 },
        { lvl: "B1", q: "If it rains, we ___ at home.", opts: ["stay", "will stay", "would stay"], a: 1 },
        { lvl: "B1", q: "I wish I ___ more time.", opts: ["have", "had", "will have"], a: 1 },
        { lvl: "B1", q: "She ___ me her address yesterday.", opts: ["gave", "gives", "has given"], a: 0 },
        { lvl: "B1", q: "They went to the cinema ___ they were bored.", opts: ["although", "because", "but"], a: 1 },
        { lvl: "B1", q: "He doesn't enjoy ___ in the city.", opts: ["living", "live", "to live"], a: 0 },
        { lvl: "B1", q: "I promise I ___ you later.", opts: ["call", "will call", "am calling"], a: 1 },
        { lvl: "B1", q: "The coffee is ___ hot to drink.", opts: ["too", "enough", "very"], a: 0 },
        // B2
        { lvl: "B2", q: "___ he had studied, he would have passed.", opts: ["If", "Although", "Unless"], a: 0 },
        { lvl: "B2", q: "She asked me ___ I was going.", opts: ["where", "that", "if"], a: 0 },
        { lvl: "B2", q: "The movie was ___ I had expected.", opts: ["more better than", "better than", "as good as"], a: 1 },
        { lvl: "B2", q: "We need to discuss ___ to solve the problem.", opts: ["how", "that", "what"], a: 0 },
        { lvl: "B2", q: "He is ___ of the two candidates.", opts: ["the best", "the better", "better"], a: 1 },
        { lvl: "B2", q: "She denied ___ the money.", opts: ["to steal", "stealing", "stole"], a: 1 },
        { lvl: "B2", q: "The exam was ___ I thought.", opts: ["more easy as", "easier than", "easy than"], a: 1 },
        { lvl: "B2", q: "I wish I ___ more about art.", opts: ["knew", "know", "would know"], a: 0 },
        { lvl: "B2", q: "They ___ to the party if they had been invited.", opts: ["would come", "would have come", "came"], a: 1 },
        { lvl: "B2", q: "This is the house ___ I grew up.", opts: ["where", "which", "that"], a: 0 },
        // C1
        { lvl: "C1", q: "Not only ___ to the meeting, but he also presented.", opts: ["did he come", "he came", "came he"], a: 0 },
        { lvl: "C1", q: "I wish I ___ the answer.", opts: ["knew", "know", "had known"], a: 0 },
        { lvl: "C1", q: "It's essential that he ___ on time.", opts: ["be", "is", "was"], a: 0 },
        { lvl: "C1", q: "The report ___ by the end of the day.", opts: ["will be finished", "is being finished", "is finished"], a: 0 },
        { lvl: "C1", q: "Had I known, I ___ different.", opts: ["would do", "would have done", "did"], a: 1 },
        { lvl: "C1", q: "She is ___ of the two sisters.", opts: ["the tallest", "the taller", "taller"], a: 1 },
        { lvl: "C1", q: "The proposal was rejected, ___ we expected.", opts: ["as", "that", "which"], a: 0 },
        { lvl: "C1", q: "I can't help ___ worried.", opts: ["feel", "feeling", "to feel"], a: 1 },
        { lvl: "C1", q: "The lecture was ___ long for the students.", opts: ["too", "so", "very"], a: 0 },
        { lvl: "C1", q: "He has a tendency ___ impatient.", opts: ["to be", "of being", "being"], a: 0 },
        // C2
        { lvl: "C2", q: "Were I rich, I ___ travel the world.", opts: ["would", "will", "would have"], a: 0 },
        { lvl: "C2", q: "The author's use of metaphor ___ the reader.", opts: ["challenges", "challenge", "challenging"], a: 0 },
        { lvl: "C2", q: "Little ___ she know what awaited her.", opts: ["does", "did", "didn't"], a: 1 },
        { lvl: "C2", q: "The committee ___ divided on the issue.", opts: ["is", "are", "were"], a: 0 },
        { lvl: "C2", q: "It is imperative that the project ___ on schedule.", opts: ["is completed", "be completed", "will be completed"], a: 1 },
        { lvl: "C2", q: "Her argument was ___ persuasive.", opts: ["most", "more", "much"], a: 0 },
        { lvl: "C2", q: "The research, ___ findings are groundbreaking, took years.", opts: ["whose", "which", "that"], a: 0 },
        { lvl: "C2", q: "He spoke with an air of ___ that annoyed everyone.", opts: ["authority", "authoritative", "authoritarian"], a: 0 },
        { lvl: "C2", q: "The scandal cast ___ the reputation of the company.", opts: ["doubt on", "doubt at", "doubt about"], a: 0 },
        { lvl: "C2", q: "She is a ___ critic of the government.", opts: ["vocal", "vociferous", "both"], a: 2 },
    ];

    // =====================================================================
    //  АБЕТКА
    // =====================================================================
    const ALPHABET = [
        { letter: "A a", name: "ей", sound: "«ей», у словах часто як «е» чи «а»", example: "cat", example_uk: "кіт" },
        { letter: "B b", name: "бі", sound: "як українське «б»", example: "book", example_uk: "книга" },
        { letter: "C c", name: "сі", sound: "як «к» або «с» залежно від слова", example: "cup", example_uk: "чашка" },
        { letter: "D d", name: "ді", sound: "як українське «д»", example: "dog", example_uk: "собака" },
        { letter: "E e", name: "і", sound: "у словах часто як «е»", example: "egg", example_uk: "яйце" },
        { letter: "F f", name: "еф", sound: "як українське «ф»", example: "fish", example_uk: "риба" },
        { letter: "G g", name: "джі", sound: "як «ґ» або «дж» залежно від слова", example: "green", example_uk: "зелений" },
        { letter: "H h", name: "ейч", sound: "легке видихання, як в «hello»", example: "house", example_uk: "будинок" },
        { letter: "I i", name: "ай", sound: "у словах часто як коротке «і»", example: "ink", example_uk: "чорнило" },
        { letter: "J j", name: "джей", sound: "як українське «дж»", example: "jam", example_uk: "варення" },
        { letter: "K k", name: "кей", sound: "як українське «к»", example: "key", example_uk: "ключ" },
        { letter: "L l", name: "ел", sound: "як українське «л»", example: "lion", example_uk: "лев" },
        { letter: "M m", name: "ем", sound: "як українське «м»", example: "moon", example_uk: "місяць" },
        { letter: "N n", name: "ен", sound: "як українське «н»", example: "night", example_uk: "ніч" },
        { letter: "O o", name: "оу", sound: "у словах часто як коротке «о»", example: "orange", example_uk: "апельсин" },
        { letter: "P p", name: "пі", sound: "як українське «п»", example: "pen", example_uk: "ручка" },
        { letter: "Q q", name: "к'ю", sound: "завжди разом з «u» — «кв»", example: "queen", example_uk: "королева" },
        { letter: "R r", name: "ар", sound: "легше за українське «р», без розкату", example: "red", example_uk: "червоний" },
        { letter: "S s", name: "ес", sound: "як українське «с»", example: "sun", example_uk: "сонце" },
        { letter: "T t", name: "ті", sound: "як українське «т»", example: "table", example_uk: "стіл" },
        { letter: "U u", name: "ю", sound: "у словах часто як «а» чи «ю»", example: "umbrella", example_uk: "парасолька" },
        { letter: "V v", name: "ві", sound: "як українське «в», але зуби торкаються губи", example: "van", example_uk: "фургон" },
        { letter: "W w", name: "дабл-ю", sound: "як коротке українське «у»", example: "water", example_uk: "вода" },
        { letter: "X x", name: "екс", sound: "як «кс»", example: "box", example_uk: "коробка" },
        { letter: "Y y", name: "вай", sound: "як «й» на початку слова, «і» в кінці", example: "yellow", example_uk: "жовтий" },
        { letter: "Z z", name: "зед", sound: "як українське «з»", example: "zoo", example_uk: "зоопарк" },
    ];

    // =====================================================================
    //  РЕЄСТРАЦІЯ ДАНИХ У ГЛОБАЛЬНИЙ ОБ'ЄКТ
    // =====================================================================
    window.LANG_DATA = window.LANG_DATA || {};
    window.LANG_DATA.en = {
        VOCAB,
        GRAMMAR,
        NORSKPROVE_TASKS,
        LEVEL_TEST,
        ALPHABET,
    };
})();