// =====================================================================
//  js/data-it.js — ІТАЛІЙСЬКА МОВА (ПОВНИЙ НАБІР)
//  Повністю сумісний з js/data.js для норвезької.
//  Містить VOCAB, GRAMMAR, NORSKPROVE_TASKS, LEVEL_TEST.
// =====================================================================
(function () {

    // =====================================================================
    //  VOCAB – СЛОВНИК ЗА РІВНЯМИ (A1-C2)
    // =====================================================================
    const VOCAB = {
        // -------------------- A1 --------------------
        A1: [
            { t: "Привітання", no: "ciao", pron: "чао", uk: "привіт", en: "hello", ru: "привет", ex_no: "Ciao, come stai?", ex_uk: "Привіт, як справи?", en_ex: "Hello, how are you?", ru_ex: "Привет, как дела?" },
            { t: "Привітання", no: "buongiorno", pron: "буонджорно", uk: "добрий ранок", en: "good morning", ru: "доброе утро", ex_no: "Buongiorno, hai dormito bene?", ex_uk: "Добрий ранок, ти добре спав?", en_ex: "Good morning, did you sleep well?", ru_ex: "Доброе утро, ты хорошо спал?" },
            { t: "Привітання", no: "buonasera", pron: "буонасера", uk: "добрий вечір", en: "good evening", ru: "добрый вечер", ex_no: "Buonasera, benvenuto a casa nostra.", ex_uk: "Добрий вечір, ласкаво просимо до нас.", en_ex: "Good evening, welcome to our home.", ru_ex: "Добрый вечер, добро пожаловать к нам." },
            { t: "Привітання", no: "buonanotte", pron: "буонанотте", uk: "на добраніч", en: "good night", ru: "спокойной ночи", ex_no: "Buonanotte, dormi bene!", ex_uk: "На добраніч, солодких снів!", en_ex: "Good night, sleep well!", ru_ex: "Спокойной ночи, сладких снов!" },
            { t: "Привітання", no: "arrivederci", pron: "аррівeдерчі", uk: "до побачення", en: "goodbye", ru: "до свидания", ex_no: "Arrivederci, ci vediamo domani.", ex_uk: "До побачення, побачимось завтра.", en_ex: "Goodbye, see you tomorrow.", ru_ex: "До свидания, увидимся завтра." },
            { t: "Привітання", no: "grazie", pron: "грацiє", uk: "дякую", en: "thank you", ru: "спасибо", ex_no: "Grazie per il tuo aiuto.", ex_uk: "Дякую за твою допомогу.", en_ex: "Thank you for your help.", ru_ex: "Спасибо за твою помощь." },
            { t: "Привітання", no: "per favore", pron: "пер фаворе", uk: "будь ласка", en: "please", ru: "пожалуйста", ex_no: "Puoi aiutarmi, per favore?", ex_uk: "Можеш допомогти мені, будь ласка?", en_ex: "Can you help me, please?", ru_ex: "Можешь помочь мне, пожалуйста?" },
            { t: "Привітання", no: "scusa", pron: "скуза", uk: "вибачте", en: "sorry", ru: "извините", ex_no: "Scusa, dov'è la stazione?", ex_uk: "Вибачте, де вокзал?", en_ex: "Sorry, where is the station?", ru_ex: "Извините, где вокзал?" },
            { t: "Привітання", no: "sì", pron: "сі", uk: "так", en: "yes", ru: "да", ex_no: "Sì, è vero.", ex_uk: "Так, це правда.", en_ex: "Yes, that's right.", ru_ex: "Да, это правда." },
            { t: "Привітання", no: "no", pron: "но", uk: "ні", en: "no", ru: "нет", ex_no: "No, non lo so.", ex_uk: "Ні, я не знаю.", en_ex: "No, I don't know.", ru_ex: "Нет, я не знаю." },
            { t: "Привітання", no: "benvenuto", pron: "бенвенуто", uk: "ласкаво просимо", en: "welcome", ru: "добро пожаловать", ex_no: "Benvenuto a casa nostra!", ex_uk: "Ласкаво просимо до нашого дому!", en_ex: "Welcome to our home!", ru_ex: "Добро пожаловать в наш дом!" },
            { t: "Привітання", no: "come stai", pron: "коме стай", uk: "як справи", en: "how are you", ru: "как дела", ex_no: "Ciao Anna, come stai?", ex_uk: "Привіт, Анно, як справи?", en_ex: "Hi Anna, how are you?", ru_ex: "Привет, Анна, как дела?" },
            { t: "Числа", no: "zero", pron: "дзеро", uk: "нуль", en: "zero", ru: "ноль", ex_no: "Iniziamo da zero.", ex_uk: "Ми починаємо з нуля.", en_ex: "We start from zero.", ru_ex: "Мы начинаем с нуля." },
            { t: "Числа", no: "uno", pron: "уно", uk: "один", en: "one", ru: "один", ex_no: "Ho un gatto.", ex_uk: "У мене є один кіт.", en_ex: "I have one cat.", ru_ex: "У меня есть один кот." },
            { t: "Числа", no: "due", pron: "дуе", uk: "два", en: "two", ru: "два", ex_no: "Sono le due.", ex_uk: "Зараз друга година.", en_ex: "It's two o'clock.", ru_ex: "Сейчас два часа." },
            { t: "Числа", no: "tre", pron: "тре", uk: "три", en: "three", ru: "три", ex_no: "Ho tre fratelli.", ex_uk: "У мене три брати.", en_ex: "I have three brothers.", ru_ex: "У меня три брата." },
            { t: "Числа", no: "quattro", pron: "куаттро", uk: "чотири", en: "four", ru: "четыре", ex_no: "Il tavolo ha quattro gambe.", ex_uk: "У стола чотири ноги.", en_ex: "The table has four legs.", ru_ex: "У стола четыре ноги." },
            { t: "Числа", no: "cinque", pron: "чінкуе", uk: "п'ять", en: "five", ru: "пять", ex_no: "Finisco di lavorare alle cinque.", ex_uk: "Я закінчую роботу о п'ятій.", en_ex: "I finish work at five.", ru_ex: "Я заканчиваю работу в пять." },
            { t: "Числа", no: "sei", pron: "сей", uk: "шість", en: "six", ru: "шесть", ex_no: "Ci svegliamo alle sei.", ex_uk: "Ми прокидаємось о шостій.", en_ex: "We wake up at six.", ru_ex: "Мы просыпаемся в шесть." },
            { t: "Числа", no: "sette", pron: "сеттe", uk: "сім", en: "seven", ru: "семь", ex_no: "Una settimana ha sette giorni.", ex_uk: "У тижні сім днів.", en_ex: "There are seven days in a week.", ru_ex: "В неделе семь дней." },
            { t: "Числа", no: "otto", pron: "отто", uk: "вісім", en: "eight", ru: "восемь", ex_no: "Il negozio apre alle otto.", ex_uk: "Магазин відкривається о восьмій.", en_ex: "The shop opens at eight.", ru_ex: "Магазин открывается в восемь." },
            { t: "Числа", no: "nove", pron: "нове", uk: "дев'ять", en: "nine", ru: "девять", ex_no: "La scuola inizia alle nove.", ex_uk: "Школа починається о дев'ятій.", en_ex: "School starts at nine.", ru_ex: "Школа начинается в девять." },
            { t: "Числа", no: "dieci", pron: "дьєчі", uk: "десять", en: "ten", ru: "десять", ex_no: "Conto fino a dieci.", ex_uk: "Я рахую до десяти.", en_ex: "I count to ten.", ru_ex: "Я считаю до десяти." },
            { t: "Числа", no: "venti", pron: "венті", uk: "двадцять", en: "twenty", ru: "двадцать", ex_no: "Lei ha vent'anni.", ex_uk: "Їй двадцять років.", en_ex: "She is twenty years old.", ru_ex: "Ей двадцать лет." },
            { t: "Числа", no: "cento", pron: "ченто", uk: "сто", en: "hundred", ru: "сто", ex_no: "Ci sono cento persone qui.", ex_uk: "Тут сто людей.", en_ex: "There are a hundred people here.", ru_ex: "Здесь сто человек." },
            { t: "Родина", no: "la famiglia", pron: "ля фамiлья", uk: "родина", en: "family", ru: "семья", ex_no: "Amo la mia famiglia.", ex_uk: "Я люблю свою родину.", en_ex: "I love my family.", ru_ex: "Я люблю свою семью." },
            { t: "Родина", no: "la madre", pron: "ля мадре", uk: "мама", en: "mother", ru: "мама", ex_no: "Mia madre cucina la cena.", ex_uk: "Моя мама готує вечерю.", en_ex: "My mother cooks dinner.", ru_ex: "Моя мама готовит ужин." },
            { t: "Родина", no: "il padre", pron: "іль падре", uk: "тато", en: "father", ru: "папа", ex_no: "Mio padre lavora in città.", ex_uk: "Мій тато працює в місті.", en_ex: "My father works in the city.", ru_ex: "Мой папа работает в городе." },
            { t: "Родина", no: "la sorella", pron: "ля сорелла", uk: "сестра", en: "sister", ru: "сестра", ex_no: "Mia sorella è più giovane di me.", ex_uk: "Моя сестра молодша за мене.", en_ex: "My sister is younger than me.", ru_ex: "Моя сестра младше меня." },
            { t: "Родина", no: "il fratello", pron: "іль фрателло", uk: "брат", en: "brother", ru: "брат", ex_no: "Mio fratello vive a Roma.", ex_uk: "Мій брат живе в Римі.", en_ex: "My brother lives in Rome.", ru_ex: "Мой брат живёт в Риме." },
            { t: "Родина", no: "il bambino", pron: "іль бамбіно", uk: "дитина", en: "child", ru: "ребёнок", ex_no: "Il bambino gioca fuori.", ex_uk: "Дитина грається надворі.", en_ex: "The child is playing outside.", ru_ex: "Ребёнок играет на улице." },
            { t: "Родина", no: "la nonna", pron: "ля нонна", uk: "бабуся", en: "grandmother", ru: "бабушка", ex_no: "Mia nonna fa il pane ogni settimana.", ex_uk: "Моя бабуся пече хліб щотижня.", en_ex: "My grandmother bakes bread every week.", ru_ex: "Моя бабушка печёт хлеб каждую неделю." },
            { t: "Родина", no: "il nonno", pron: "іль нонно", uk: "дідусь", en: "grandfather", ru: "дедушка", ex_no: "Mio nonno racconta belle storie.", ex_uk: "Мій дідусь розповідає чудові історії.", en_ex: "My grandfather tells great stories.", ru_ex: "Мой дедушка рассказывает отличные истории." },
            { t: "Родина", no: "l'amico", pron: "ляміко", uk: "друг", en: "friend", ru: "друг", ex_no: "Lui è il mio migliore amico.", ex_uk: "Він мій найкращий друг.", en_ex: "He is my best friend.", ru_ex: "Он мой лучший друг." },
            { t: "Кольори", no: "rosso", pron: "россо", uk: "червоний", en: "red", ru: "красный", ex_no: "La mela è rossa.", ex_uk: "Яблуко червоне.", en_ex: "The apple is red.", ru_ex: "Яблоко красное." },
            { t: "Кольори", no: "blu", pron: "блю", uk: "синій", en: "blue", ru: "синий", ex_no: "Il cielo è blu oggi.", ex_uk: "Сьогодні небо синє.", en_ex: "The sky is blue today.", ru_ex: "Сегодня небо синее." },
            { t: "Кольори", no: "verde", pron: "верде", uk: "зелений", en: "green", ru: "зелёный", ex_no: "L'erba è verde.", ex_uk: "Трава зелена.", en_ex: "The grass is green.", ru_ex: "Трава зелёная." },
            { t: "Кольори", no: "giallo", pron: "джалло", uk: "жовтий", en: "yellow", ru: "жёлтый", ex_no: "Il sole è giallo.", ex_uk: "Сонце жовте.", en_ex: "The sun is yellow.", ru_ex: "Солнце жёлтое." },
            { t: "Кольори", no: "nero", pron: "неро", uk: "чорний", en: "black", ru: "чёрный", ex_no: "Lei ha un gatto nero.", ex_uk: "У неї чорний кіт.", en_ex: "She has a black cat.", ru_ex: "У неё чёрный кот." },
            { t: "Кольори", no: "bianco", pron: "б'янко", uk: "білий", en: "white", ru: "белый", ex_no: "La neve è bianca.", ex_uk: "Сніг білий.", en_ex: "The snow is white.", ru_ex: "Снег белый." },
            { t: "Кольори", no: "arancione", pron: "аранчьоне", uk: "помаранчевий", en: "orange", ru: "оранжевый", ex_no: "Mi piace il succo d'arancia.", ex_uk: "Мені подобається помаранчевий сік.", en_ex: "I like orange juice.", ru_ex: "Мне нравится апельсиновый сок." },
            { t: "Дні тижня", no: "lunedì", pron: "лунедi", uk: "понеділок", en: "Monday", ru: "понедельник", ex_no: "Inizio a lavorare lunedì.", ex_uk: "Я починаю роботу в понеділок.", en_ex: "I start work on Monday.", ru_ex: "Я начинаю работу в понедельник." },
            { t: "Дні тижня", no: "martedì", pron: "мартедi", uk: "вівторок", en: "Tuesday", ru: "вторник", ex_no: "Abbiamo una riunione martedì.", ex_uk: "У нас зустріч у вівторок.", en_ex: "We have a meeting on Tuesday.", ru_ex: "У нас встреча во вторник." },
            { t: "Дні тижня", no: "mercoledì", pron: "меркoледi", uk: "середа", en: "Wednesday", ru: "среда", ex_no: "Vado in palestra il mercoledì.", ex_uk: "Я ходжу в спортзал у середу.", en_ex: "I go to the gym on Wednesday.", ru_ex: "Я хожу в спортзал в среду." },
            { t: "Дні тижня", no: "giovedì", pron: "джовeдi", uk: "четвер", en: "Thursday", ru: "четверг", ex_no: "L'esame è giovedì.", ex_uk: "Іспит у четвер.", en_ex: "The exam is on Thursday.", ru_ex: "Экзамен в четверг." },
            { t: "Дні тижня", no: "venerdì", pron: "венердi", uk: "п'ятниця", en: "Friday", ru: "пятница", ex_no: "Festeggiamo venerdì.", ex_uk: "Ми святкуємо в п'ятницю.", en_ex: "We celebrate on Friday.", ru_ex: "Мы празднуем в пятницу." },
            { t: "Дні тижня", no: "sabato", pron: "сабато", uk: "субота", en: "Saturday", ru: "суббота", ex_no: "Pulisco la casa il sabato.", ex_uk: "Я прибираю в суботу.", en_ex: "I clean the house on Saturday.", ru_ex: "Я убираюсь в субботу." },
            { t: "Дні тижня", no: "domenica", pron: "доменіка", uk: "неділя", en: "Sunday", ru: "воскресенье", ex_no: "Ci riposiamo la domenica.", ex_uk: "Ми відпочиваємо в неділю.", en_ex: "We rest on Sunday.", ru_ex: "Мы отдыхаем в воскресенье." },
            { t: "Дієслова", no: "essere", pron: "ессере", uk: "бути", en: "to be", ru: "быть", ex_no: "Sono uno studente.", ex_uk: "Я студент.", en_ex: "I am a student.", ru_ex: "Я студент." },
            { t: "Дієслова", no: "avere", pron: "авере", uk: "мати", en: "to have", ru: "иметь", ex_no: "Ho una macchina.", ex_uk: "У мене є машина.", en_ex: "I have a car.", ru_ex: "У меня есть машина." },
            { t: "Дієслова", no: "andare", pron: "андаре", uk: "йти", en: "to go", ru: "идти", ex_no: "Vado al lavoro ogni giorno.", ex_uk: "Я йду на роботу щодня.", en_ex: "I go to work every day.", ru_ex: "Я иду на работу каждый день." },
            { t: "Дієслова", no: "mangiare", pron: "манджаре", uk: "їсти", en: "to eat", ru: "есть", ex_no: "Facciamo colazione alle sette.", ex_uk: "Ми снідаємо о сьомій.", en_ex: "We eat breakfast at seven.", ru_ex: "Мы завтракаем в семь." },
            { t: "Дієслова", no: "bere", pron: "бере", uk: "пити", en: "to drink", ru: "пить", ex_no: "Bevo acqua ogni mattina.", ex_uk: "Я п'ю воду щоранку.", en_ex: "I drink water every morning.", ru_ex: "Я пью воду каждое утро." },
            { t: "Дієслова", no: "vedere", pron: "ведере", uk: "бачити", en: "to see", ru: "видеть", ex_no: "Posso vedere le montagne.", ex_uk: "Я бачу гори.", en_ex: "I can see the mountains.", ru_ex: "Я вижу горы." },
            { t: "Дієслова", no: "parlare", pron: "парларе", uk: "говорити", en: "to speak", ru: "говорить", ex_no: "Lei parla tre lingue.", ex_uk: "Вона говорить трьома мовами.", en_ex: "She speaks three languages.", ru_ex: "Она говорит на трёх языках." },
            { t: "Дієслова", no: "volere", pron: "волере", uk: "хотіти", en: "to want", ru: "хотеть", ex_no: "Vorrei un caffè, per favore.", ex_uk: "Я хочу каву, будь ласка.", en_ex: "I want a coffee, please.", ru_ex: "Я хочу кофе, пожалуйста." },
            { t: "Дієслова", no: "vivere", pron: "вiвере", uk: "жити", en: "to live", ru: "жить", ex_no: "Viviamo in una piccola città.", ex_uk: "Ми живемо в маленькому місті.", en_ex: "We live in a small town.", ru_ex: "Мы живём в маленьком городе." },
            { t: "Дієслова", no: "lavorare", pron: "лаворaре", uk: "працювати", en: "to work", ru: "работать", ex_no: "Lui lavora in un ospedale.", ex_uk: "Він працює в лікарні.", en_ex: "He works in a hospital.", ru_ex: "Он работает в больнице." },
            { t: "Дієслова", no: "dormire", pron: "дормiре", uk: "спати", en: "to sleep", ru: "спать", ex_no: "Il bambino dorme molto.", ex_uk: "Дитина багато спить.", en_ex: "The baby sleeps a lot.", ru_ex: "Малыш много спит." },
            { t: "Їжа", no: "il pane", pron: "іль пане", uk: "хліб", en: "bread", ru: "хлеб", ex_no: "Compro pane fresco ogni giorno.", ex_uk: "Я купую свіжий хліб щодня.", en_ex: "I buy fresh bread every day.", ru_ex: "Я покупаю свежий хлеб каждый день." },
            { t: "Їжа", no: "l'acqua", pron: "лаккуа", uk: "вода", en: "water", ru: "вода", ex_no: "Posso avere un po' d'acqua?", ex_uk: "Можна мені трохи води?", en_ex: "Can I have some water?", ru_ex: "Можно мне немного воды?" },
            { t: "Їжа", no: "il latte", pron: "іль латте", uk: "молоко", en: "milk", ru: "молоко", ex_no: "Bevo latte a colazione.", ex_uk: "Я п'ю молоко зі сніданком.", en_ex: "I drink milk with breakfast.", ru_ex: "Я пью молоко с завтраком." },
            { t: "Їжа", no: "l'uovo", pron: "луово", uk: "яйце", en: "egg", ru: "яйцо", ex_no: "Mangio un uovo ogni mattina.", ex_uk: "Я їм яйце щоранку.", en_ex: "I eat an egg every morning.", ru_ex: "Я ем яйцо каждое утро." },
            { t: "Їжа", no: "la mela", pron: "ля мела", uk: "яблуко", en: "apple", ru: "яблоко", ex_no: "Lei mangia una mela a pranzo.", ex_uk: "Вона їсть яблуко на обід.", en_ex: "She eats an apple for lunch.", ru_ex: "Она ест яблоко на обед." },
            { t: "Їжа", no: "la carne", pron: "ля карне", uk: "м'ясо", en: "meat", ru: "мясо", ex_no: "Non mangiamo carne il venerdì.", ex_uk: "Ми не їмо м'ясо по п'ятницях.", en_ex: "We don't eat meat on Fridays.", ru_ex: "Мы не едим мясо по пятницам." },
            { t: "Їжа", no: "il formaggio", pron: "іль формаджо", uk: "сир", en: "cheese", ru: "сыр", ex_no: "Adoro il formaggio italiano.", ex_uk: "Я люблю італійський сир.", en_ex: "I love Italian cheese.", ru_ex: "Я люблю итальянский сыр." },
            { t: "Їжа", no: "il caffè", pron: "іль каффе", uk: "кава", en: "coffee", ru: "кофе", ex_no: "Bevo il caffè ogni mattina.", ex_uk: "Я п'ю каву щоранку.", en_ex: "I drink coffee every morning.", ru_ex: "Я пью кофе каждое утро." },
            { t: "Прикметники", no: "grande", pron: "гранде", uk: "великий", en: "big", ru: "большой", ex_no: "Questa è una casa grande.", ex_uk: "Це великий будинок.", en_ex: "This is a big house.", ru_ex: "Это большой дом." },
            { t: "Прикметники", no: "piccolo", pron: "пiкколо", uk: "маленький", en: "small", ru: "маленький", ex_no: "Il gatto è molto piccolo.", ex_uk: "Кіт дуже маленький.", en_ex: "The cat is very small.", ru_ex: "Кот очень маленький." },
            { t: "Прикметники", no: "buono", pron: "буоно", uk: "добрий", en: "good", ru: "хороший", ex_no: "Questa è una buona idea.", ex_uk: "Це добра ідея.", en_ex: "This is a good idea.", ru_ex: "Это хорошая идея." },
            { t: "Прикметники", no: "cattivo", pron: "каттiво", uk: "поганий", en: "bad", ru: "плохой", ex_no: "Il tempo è cattivo oggi.", ex_uk: "Сьогодні погана погода.", en_ex: "The weather is bad today.", ru_ex: "Сегодня плохая погода." },
            { t: "Прикметники", no: "nuovo", pron: "нуово", uk: "новий", en: "new", ru: "новый", ex_no: "Ho comprato un telefono nuovo.", ex_uk: "Я купив новий телефон.", en_ex: "I bought a new phone.", ru_ex: "Я купил новый телефон." },
            { t: "Прикметники", no: "vecchio", pron: "векк'йо", uk: "старий", en: "old", ru: "старый", ex_no: "Questo libro è molto vecchio.", ex_uk: "Ця книга дуже стара.", en_ex: "This book is very old.", ru_ex: "Эта книга очень старая." },
            { t: "Тіло", no: "la testa", pron: "ля теста", uk: "голова", en: "head", ru: "голова", ex_no: "Mi fa male la testa.", ex_uk: "У мене болить голова.", en_ex: "My head hurts.", ru_ex: "У меня болит голова." },
            { t: "Тіло", no: "la mano", pron: "ля мано", uk: "рука", en: "hand", ru: "рука", ex_no: "Dammi la tua mano.", ex_uk: "Дай мені руку.", en_ex: "Give me your hand.", ru_ex: "Дай мне руку." },
            { t: "Тіло", no: "l'occhio", pron: "локк'йо", uk: "око", en: "eye", ru: "глаз", ex_no: "Lei ha gli occhi azzurri.", ex_uk: "У неї блакитні очі.", en_ex: "She has blue eyes.", ru_ex: "У неё голубые глаза." },
            { t: "Тіло", no: "l'orecchio", pron: "лорeкк'йо", uk: "вухо", en: "ear", ru: "ухо", ex_no: "Ho un'infezione all'orecchio.", ex_uk: "У мене інфекція вуха.", en_ex: "I have an ear infection.", ru_ex: "У меня инфекция уха." },
            { t: "Тіло", no: "il naso", pron: "іль назо", uk: "ніс", en: "nose", ru: "нос", ex_no: "Il suo naso è rosso.", ex_uk: "Її ніс червоний.", en_ex: "Her nose is red.", ru_ex: "У неё красный нос." },
            { t: "Дім", no: "la casa", pron: "ля каза", uk: "будинок", en: "house", ru: "дом", ex_no: "Viviamo in una piccola casa.", ex_uk: "Ми живемо в маленькому будинку.", en_ex: "We live in a small house.", ru_ex: "Мы живём в маленьком доме." },
            { t: "Дім", no: "la camera", pron: "ля камера", uk: "кімната", en: "room", ru: "комната", ex_no: "La mia camera è al piano di sopra.", ex_uk: "Моя кімната нагорі.", en_ex: "My room is upstairs.", ru_ex: "Моя комната наверху." },
            { t: "Дім", no: "la porta", pron: "ля порта", uk: "двері", en: "door", ru: "дверь", ex_no: "Per favore, chiudi la porta.", ex_uk: "Будь ласка, зачини двері.", en_ex: "Please close the door.", ru_ex: "Пожалуйста, закрой дверь." },
            { t: "Дім", no: "il tavolo", pron: "іль тавoло", uk: "стіл", en: "table", ru: "стол", ex_no: "Il libro è sul tavolo.", ex_uk: "Книга на столі.", en_ex: "The book is on the table.", ru_ex: "Книга на столе." },
            { t: "Дім", no: "la sedia", pron: "ля седья", uk: "стілець", en: "chair", ru: "стул", ex_no: "Siediti sulla sedia.", ex_uk: "Сідай на стілець.", en_ex: "Sit on the chair.", ru_ex: "Садись на стул." },
            { t: "Транспорт", no: "la macchina", pron: "ля маккiна", uk: "машина", en: "car", ru: "машина", ex_no: "Andiamo al lavoro in macchina.", ex_uk: "Ми їздимо на роботу машиною.", en_ex: "We drive to work by car.", ru_ex: "Мы ездим на работу на машине." },
            { t: "Транспорт", no: "l'autobus", pron: "лаутобус", uk: "автобус", en: "bus", ru: "автобус", ex_no: "Prendo l'autobus per andare a scuola.", ex_uk: "Я їду автобусом до школи.", en_ex: "I take the bus to school.", ru_ex: "Я еду автобусом в школу." },
            { t: "Транспорт", no: "il treno", pron: "іль трено", uk: "поїзд", en: "train", ru: "поезд", ex_no: "Il treno parte alle otto.", ex_uk: "Поїзд відправляється о восьмій.", en_ex: "The train leaves at eight.", ru_ex: "Поезд отправляется в восемь." },
            { t: "Транспорт", no: "la bicicletta", pron: "ля бiчiклeтта", uk: "велосипед", en: "bicycle", ru: "велосипед", ex_no: "Vado al lavoro in bicicletta.", ex_uk: "Я їду на велосипеді на роботу.", en_ex: "I ride my bicycle to work.", ru_ex: "Я еду на велосипеде на работу." },
        ],
        // -------------------- A2 --------------------
        A2: [
            { t: "Покупки", no: "il negozio", pron: "іль неґоцьо", uk: "магазин", en: "shop", ru: "магазин", ex_no: "Il negozio apre alle nove.", ex_uk: "Магазин відкривається о дев'ятій.", en_ex: "The shop opens at nine.", ru_ex: "Магазин открывается в девять." },
            { t: "Покупки", no: "comprare", pron: "компраре", uk: "купувати", en: "buy", ru: "покупать", ex_no: "Compro il pane fresco ogni giorno.", ex_uk: "Я купую свіжий хліб щодня.", en_ex: "I buy fresh bread every day.", ru_ex: "Я покупаю свежий хлеб каждый день." },
            { t: "Покупки", no: "il prezzo", pron: "іль преццо", uk: "ціна", en: "price", ru: "цена", ex_no: "Qual è il prezzo di questo?", ex_uk: "Яка ціна на це?", en_ex: "What is the price of this?", ru_ex: "Какая цена на это?" },
            { t: "Покупки", no: "i soldi", pron: "і солді", uk: "гроші", en: "money", ru: "деньги", ex_no: "Non ho abbastanza soldi.", ex_uk: "У мене недостатньо грошей.", en_ex: "I don't have enough money.", ru_ex: "У меня недостаточно денег." },
            { t: "Напрямки", no: "a sinistra", pron: "а сiнiстра", uk: "ліворуч", en: "left", ru: "налево", ex_no: "Gira a sinistra all'angolo.", ex_uk: "Поверни ліворуч на розі.", en_ex: "Turn left at the corner.", ru_ex: "Поверни налево на углу." },
            { t: "Напрямки", no: "a destra", pron: "а дeстра", uk: "праворуч", en: "right", ru: "направо", ex_no: "La stazione è alla tua destra.", ex_uk: "Станція праворуч від тебе.", en_ex: "The station is on your right.", ru_ex: "Станция справа от тебя." },
            { t: "Напрямки", no: "dritto", pron: "дрiтто", uk: "прямо", en: "straight", ru: "прямо", ex_no: "Vai dritto.", ex_uk: "Іди прямо.", en_ex: "Go straight ahead.", ru_ex: "Иди прямо." },
            { t: "Напрямки", no: "la mappa", pron: "ля мaппа", uk: "карта", en: "map", ru: "карта", ex_no: "Puoi mostrarmelo sulla mappa?", ex_uk: "Можеш показати мені на карті?", en_ex: "Can you show me on the map?", ru_ex: "Можешь показать мне на карте?" },
            { t: "Робота", no: "il lavoro", pron: "іль лаворо", uk: "робота", en: "job", ru: "работа", ex_no: "Ha trovato un nuovo lavoro.", ex_uk: "Вона знайшла нову роботу.", en_ex: "She found a new job.", ru_ex: "Она нашла новую работу." },
            { t: "Робота", no: "l'ufficio", pron: "луффiчо", uk: "офіс", en: "office", ru: "офис", ex_no: "Lavoro in un ufficio.", ex_uk: "Я працюю в офісі.", en_ex: "I work in an office.", ru_ex: "Я работаю в офисе." },
            { t: "Робота", no: "la riunione", pron: "ля рьюньйоне", uk: "зустріч", en: "meeting", ru: "встреча", ex_no: "Abbiamo una riunione alle dieci.", ex_uk: "У нас зустріч о десятій.", en_ex: "We have a meeting at ten.", ru_ex: "У нас встреча в десять." },
            { t: "Робота", no: "lo stipendio", pron: "ло стiпендьо", uk: "зарплата", en: "salary", ru: "зарплата", ex_no: "Il mio stipendio è buono.", ex_uk: "Моя зарплата хороша.", en_ex: "My salary is good.", ru_ex: "Моя зарплата хорошая." },
            { t: "Хобі", no: "il hobby", pron: "іль хоббi", uk: "хобі", en: "hobby", ru: "хобби", ex_no: "Qual è il tuo hobby?", ex_uk: "Яке твоє хобі?", en_ex: "What is your hobby?", ru_ex: "Какое у тебя хобби?" },
            { t: "Хобі", no: "leggere", pron: "леджере", uk: "читати", en: "read", ru: "читать", ex_no: "Mi piace leggere libri.", ex_uk: "Я люблю читати книги.", en_ex: "I like to read books.", ru_ex: "Я люблю читать книги." },
            { t: "Хобі", no: "viaggiare", pron: "в'яджаре", uk: "подорожувати", en: "travel", ru: "путешествовать", ex_no: "Amiamo viaggiare.", ex_uk: "Ми любимо подорожувати.", en_ex: "We love to travel.", ru_ex: "Мы любим путешествовать." },
            { t: "Хобі", no: "la musica", pron: "ля музiка", uk: "музика", en: "music", ru: "музыка", ex_no: "Ascolto musica ogni giorno.", ex_uk: "Я слухаю музику щодня.", en_ex: "I listen to music every day.", ru_ex: "Я слушаю музыку каждый день." },
            { t: "Погода", no: "la pioggia", pron: "ля п'оджа", uk: "дощ", en: "rain", ru: "дождь", ex_no: "Domani pioverà.", ex_uk: "Завтра буде дощ.", en_ex: "It's going to rain tomorrow.", ru_ex: "Завтра будет дождь." },
            { t: "Погода", no: "la neve", pron: "ля неве", uk: "сніг", en: "snow", ru: "снег", ex_no: "In inverno nevica.", ex_uk: "Взимку йде сніг.", en_ex: "It snows in winter.", ru_ex: "Зимой идёт снег." },
            { t: "Погода", no: "soleggiato", pron: "солeджато", uk: "сонячно", en: "sunny", ru: "солнечно", ex_no: "Oggi è soleggiato.", ex_uk: "Сьогодні сонячно.", en_ex: "It's sunny today.", ru_ex: "Сегодня солнечно." },
            { t: "Погода", no: "freddo", pron: "фреддо", uk: "холодно", en: "cold", ru: "холодно", ex_no: "Fa freddo fuori.", ex_uk: "На вулиці холодно.", en_ex: "It's cold outside.", ru_ex: "На улице холодно." },
            { t: "Погода", no: "caldo", pron: "калдо", uk: "спекотно", en: "hot", ru: "жарко", ex_no: "Fa molto caldo in estate.", ex_uk: "Влітку дуже спекотно.", en_ex: "It's very hot in summer.", ru_ex: "Летом очень жарко." },
            { t: "Освіта", no: "la scuola", pron: "ля скуола", uk: "школа", en: "school", ru: "школа", ex_no: "I bambini vanno a scuola.", ex_uk: "Діти ходять до школи.", en_ex: "The children go to school.", ru_ex: "Дети ходят в школу." },
            { t: "Освіта", no: "l'insegnante", pron: "лiнсеньянте", uk: "вчитель", en: "teacher", ru: "учитель", ex_no: "L'insegnante spiega la grammatica.", ex_uk: "Вчитель пояснює граматику.", en_ex: "The teacher explains grammar.", ru_ex: "Учитель объясняет грамматику." },
            { t: "Освіта", no: "lo studente", pron: "ло студeнте", uk: "студент", en: "student", ru: "студент", ex_no: "Lei è una studentessa all'università.", ex_uk: "Вона студентка університету.", en_ex: "She is a student at university.", ru_ex: "Она студентка университета." },
            { t: "Освіта", no: "l'esame", pron: "лезаме", uk: "іспит", en: "exam", ru: "экзамен", ex_no: "Ho superato l'esame.", ex_uk: "Я склав іспит.", en_ex: "I passed the exam.", ru_ex: "Я сдал экзамен." },
            { t: "Ресторан", no: "il menu", pron: "іль меню", uk: "меню", en: "menu", ru: "меню", ex_no: "Posso avere il menu?", ex_uk: "Можна меню?", en_ex: "Can I have the menu?", ru_ex: "Можно меню?" },
            { t: "Ресторан", no: "il conto", pron: "іль конто", uk: "рахунок", en: "bill", ru: "счёт", ex_no: "Possiamo avere il conto, per favore?", ex_uk: "Можна нам рахунок, будь ласка?", en_ex: "Can we have the bill, please?", ru_ex: "Можно нам счёт, пожалуйста?" },
            { t: "Ресторан", no: "il cameriere", pron: "іль камерьере", uk: "офіціант", en: "waiter", ru: "официант", ex_no: "Il cameriere è gentile.", ex_uk: "Офіціант привітний.", en_ex: "The waiter is friendly.", ru_ex: "Официант приветливый." },
            { t: "Ресторан", no: "ordinare", pron: "ордiнаре", uk: "замовляти", en: "order", ru: "заказывать", ex_no: "Ordiniamo pizza il venerdì.", ex_uk: "Ми замовляємо піцу в п'ятницю.", en_ex: "We order pizza on Friday.", ru_ex: "Мы заказываем пиццу в пятницу." },
            { t: "Емоції", no: "felice", pron: "фелiче", uk: "щасливий", en: "happy", ru: "счастливый", ex_no: "Oggi si sente felice.", ex_uk: "Вона сьогодні щаслива.", en_ex: "She feels happy today.", ru_ex: "Она сегодня счастлива." },
            { t: "Емоції", no: "triste", pron: "трiсте", uk: "сумний", en: "sad", ru: "грустный", ex_no: "Il film triste mi ha fatto piangere.", ex_uk: "Сумний фільм змусив мене плакати.", en_ex: "The sad movie made me cry.", ru_ex: "Грустный фильм заставил меня плакать." },
            { t: "Емоції", no: "arrabbiato", pron: "аррабб'ято", uk: "злий", en: "angry", ru: "злой", ex_no: "Si arrabbia quando è in ritardo.", ex_uk: "Він злиться, коли запізнюється.", en_ex: "He gets angry when he is late.", ru_ex: "Он злится, когда опаздывает." },
            { t: "Емоції", no: "stanco", pron: "станко", uk: "втомлений", en: "tired", ru: "уставший", ex_no: "Mi sento stanco dopo il lavoro.", ex_uk: "Я почуваюся втомленим після роботи.", en_ex: "I feel tired after work.", ru_ex: "Я чувствую себя уставшим после работы." },
            { t: "Минулий час", no: "ho camminato", pron: "о каммiнато", uk: "я пішов", en: "I walked", ru: "я пошёл", ex_no: "Ho camminato fino alla stazione.", ex_uk: "Я пішов на станцію пішки.", en_ex: "I walked to the station.", ru_ex: "Я пошёл на станцию пешком." },
            { t: "Минулий час", no: "ho visitato", pron: "о вiзiтато", uk: "я відвідав", en: "I visited", ru: "я посетил", ex_no: "Abbiamo visitato Roma l'anno scorso.", ex_uk: "Ми відвідали Рим минулого року.", en_ex: "We visited Rome last year.", ru_ex: "Мы посетили Рим в прошлом году." },
            { t: "Минулий час", no: "sono rimasto", pron: "соно рiмасто", uk: "я зупинився / залишився", en: "I stayed", ru: "я остановился", ex_no: "Siamo rimasti in un bell'albergo.", ex_uk: "Ми зупинилися в хорошому готелі.", en_ex: "We stayed at a nice hotel.", ru_ex: "Мы остановились в хорошем отеле." },
            { t: "Минулий час", no: "ho guardato", pron: "о гуардато", uk: "я дивився", en: "I watched", ru: "я смотрел", ex_no: "Ho guardato la TV ieri sera.", ex_uk: "Я дивився телевізор учора ввечері.", en_ex: "I watched TV last night.", ru_ex: "Я смотрел телевизор вчера вечером." },
            { t: "Здоров'я", no: "il dottore", pron: "іль доттoре", uk: "лікар", en: "doctor", ru: "врач", ex_no: "Devo vedere un dottore.", ex_uk: "Мені потрібно піти до лікаря.", en_ex: "I need to see a doctor.", ru_ex: "Мне нужно пойти к врачу." },
            { t: "Здоров'я", no: "la medicina", pron: "ля медiчiна", uk: "ліки", en: "medicine", ru: "лекарство", ex_no: "Prendi questa medicina tre volte al giorno.", ex_uk: "Приймай ці ліки тричі на день.", en_ex: "Take this medicine three times a day.", ru_ex: "Принимай это лекарство три раза в день." },
            { t: "Здоров'я", no: "la febbre", pron: "ля феббре", uk: "температура", en: "fever", ru: "температура", ex_no: "Ha la febbre alta.", ex_uk: "У нього висока температура.", en_ex: "He has a high fever.", ru_ex: "У него высокая температура." },
        ],
        // -------------------- B1 --------------------
        B1: [
            { t: "Подорожі", no: "l'aeroporto", pron: "лаeропорто", uk: "аеропорт", en: "airport", ru: "аэропорт", ex_no: "Ci incontriamo all'aeroporto.", ex_uk: "Зустрінемось в аеропорту.", en_ex: "We meet at the airport.", ru_ex: "Встретимся в аэропорту." },
            { t: "Подорожі", no: "il biglietto", pron: "іль бiл'єтто", uk: "квиток", en: "ticket", ru: "билет", ex_no: "Ho prenotato un biglietto online.", ex_uk: "Я забронював квиток онлайн.", en_ex: "I booked a ticket online.", ru_ex: "Я забронировал билет онлайн." },
            { t: "Подорожі", no: "l'hotel", pron: "лотель", uk: "готель", en: "hotel", ru: "отель", ex_no: "L'hotel è vicino al centro.", ex_uk: "Готель біля центру.", en_ex: "The hotel is near the center.", ru_ex: "Отель рядом с центром." },
            { t: "Подорожі", no: "il passaporto", pron: "іль пассапорто", uk: "паспорт", en: "passport", ru: "паспорт", ex_no: "Non dimenticare il passaporto.", ex_uk: "Не забудь паспорт.", en_ex: "Don't forget your passport.", ru_ex: "Не забудь паспорт." },
            { t: "Подорожі", no: "il bagaglio", pron: "іль баґал'йо", uk: "багаж", en: "luggage", ru: "багаж", ex_no: "Il mio bagaglio è pesante.", ex_uk: "Мій багаж важкий.", en_ex: "My luggage is heavy.", ru_ex: "Мой багаж тяжёлый." },
            { t: "Подорожі", no: "il ritardo", pron: "іль рiтардо", uk: "затримка", en: "delay", ru: "задержка", ex_no: "C'è stato un ritardo a causa del maltempo.", ex_uk: "Через негоду сталася затримка.", en_ex: "There was a delay due to bad weather.", ru_ex: "Из-за непогоды произошла задержка." },
            { t: "Подорожі", no: "la destinazione", pron: "ля дестiнацьоне", uk: "пункт призначення", en: "destination", ru: "назначение", ex_no: "La nostra destinazione è Roma.", ex_uk: "Наш пункт призначення — Рим.", en_ex: "Our destination is Rome.", ru_ex: "Наш пункт назначения — Рим." },
            { t: "Подорожі", no: "il turista", pron: "іль турiста", uk: "турист", en: "tourist", ru: "турист", ex_no: "I turisti visitano il museo.", ex_uk: "Туристи відвідують музей.", en_ex: "Tourists visit the museum.", ru_ex: "Туристы посещают музей." },
            { t: "Здоров'я", no: "l'ospedale", pron: "лоспедале", uk: "лікарня", en: "hospital", ru: "больница", ex_no: "È stato portato in ospedale.", ex_uk: "Його відвезли до лікарні.", en_ex: "He was taken to the hospital.", ru_ex: "Его отвезли в больницу." },
            { t: "Здоров'я", no: "la ricetta", pron: "ля рiчeтта", uk: "рецепт", en: "prescription", ru: "рецепт", ex_no: "Ho bisogno di una ricetta per questa medicina.", ex_uk: "Мені потрібен рецепт на ці ліки.", en_ex: "I need a prescription for this medicine.", ru_ex: "Мне нужен рецепт на это лекарство." },
            { t: "Здоров'я", no: "l'assicurazione", pron: "лассiкурацьоне", uk: "страхування", en: "insurance", ru: "страховка", ex_no: "È saggio avere un'assicurazione di viaggio.", ex_uk: "Розумно мати туристичну страховку.", en_ex: "It's wise to have travel insurance.", ru_ex: "Разумно иметь туристическую страховку." },
            { t: "Здоров'я", no: "il vaccino", pron: "іль ваччiно", uk: "вакцина", en: "vaccine", ru: "вакцина", ex_no: "I bambini ricevono questo vaccino gratuitamente.", ex_uk: "Діти отримують цю вакцину безкоштовно.", en_ex: "Children get this vaccine for free.", ru_ex: "Дети получают эту вакцину бесплатно." },
            { t: "Стосунки", no: "il partner", pron: "іль партнер", uk: "партнер", en: "partner", ru: "партнёр", ex_no: "Ho presentato il mio partner alla mia famiglia.", ex_uk: "Я познайомив свого партнера з родиною.", en_ex: "I introduced my partner to my family.", ru_ex: "Я познакомил своего партнёра с семьёй." },
            { t: "Стосунки", no: "il matrimonio", pron: "іль матрiмоньйо", uk: "шлюб", en: "marriage", ru: "брак", ex_no: "Hanno celebrato dieci anni di matrimonio.", ex_uk: "Вони відсвяткували десять років шлюбу.", en_ex: "They celebrated ten years of marriage.", ru_ex: "Они отпраздновали десять лет брака." },
            { t: "Стосунки", no: "la fiducia", pron: "ля фiдучя", uk: "довіра", en: "trust", ru: "доверие", ex_no: "La fiducia è importante in una relazione.", ex_uk: "Довіра важлива у стосунках.", en_ex: "Trust is important in a relationship.", ru_ex: "Доверие важно в отношениях." },
            { t: "Медіа", no: "le notizie", pron: "ле нотiцiє", uk: "новини", en: "news", ru: "новости", ex_no: "Guardo le notizie ogni sera.", ex_uk: "Я дивлюся новини щовечора.", en_ex: "I watch the news every evening.", ru_ex: "Я смотрю новости каждый вечер." },
            { t: "Медіа", no: "il giornale", pron: "іль джорнале", uk: "газета", en: "newspaper", ru: "газета", ex_no: "Legge il giornale la mattina.", ex_uk: "Він читає газету вранці.", en_ex: "He reads the newspaper in the morning.", ru_ex: "Он читает газету утром." },
            { t: "Медіа", no: "i social media", pron: "і сошиал медіа", uk: "соціальні мережі", en: "social media", ru: "социальные сети", ex_no: "I giovani passano tempo sui social media.", ex_uk: "Молодь проводить час у соціальних мережах.", en_ex: "Young people spend time on social media.", ru_ex: "Молодёжь проводит время в социальных сетях." },
            { t: "Медіа", no: "il podcast", pron: "іль подкaст", uk: "подкаст", en: "podcast", ru: "подкаст", ex_no: "Ascolto i podcast mentre faccio esercizio.", ex_uk: "Я слухаю подкасти під час тренування.", en_ex: "I listen to podcasts while exercising.", ru_ex: "Я слушаю подкасты во время тренировки." },
            { t: "Довкілля", no: "l'ambiente", pron: "ляmб'єнте", uk: "довкілля", en: "environment", ru: "окружающая среда", ex_no: "Dobbiamo proteggere l'ambiente.", ex_uk: "Ми повинні захищати довкілля.", en_ex: "We must protect the environment.", ru_ex: "Мы должны защищать окружающую среду." },
            { t: "Довкілля", no: "il clima", pron: "іль клiма", uk: "клімат", en: "climate", ru: "климат", ex_no: "Il cambiamento climatico è un problema globale.", ex_uk: "Зміна клімату — глобальна проблема.", en_ex: "Climate change is a global problem.", ru_ex: "Изменение климата — глобальная проблема." },
            { t: "Довкілля", no: "l'inquinamento", pron: "лiнквiнаменто", uk: "забруднення", en: "pollution", ru: "загрязнение", ex_no: "L'inquinamento danneggia la fauna selvatica.", ex_uk: "Забруднення шкодить дикій природі.", en_ex: "Pollution harms wildlife.", ru_ex: "Загрязнение вредит дикой природе." },
            { t: "Довкілля", no: "il riciclaggio", pron: "іль рiчiклaджо", uk: "переробка", en: "recycling", ru: "переработка", ex_no: "Il riciclaggio è importante.", ex_uk: "Переробка важлива.", en_ex: "Recycling is important.", ru_ex: "Переработка важна." },
            { t: "Довкілля", no: "i rifiuti", pron: "і рiфьютi", uk: "відходи", en: "waste", ru: "отходы", ex_no: "Classifichiamo i rifiuti in categorie.", ex_uk: "Ми сортуємо сміття за категоріями.", en_ex: "We sort waste into categories.", ru_ex: "Мы сортируем отходы по категориям." },
            { t: "Дієслова", no: "capire", pron: "капiре", uk: "розуміти", en: "understand", ru: "понимать", ex_no: "Non capisco cosa intendi.", ex_uk: "Я не розумію, що ти маєш на увазі.", en_ex: "I don't understand what you mean.", ru_ex: "Я не понимаю, что ты имеешь в виду." },
            { t: "Дієслова", no: "spiegare", pron: "сп'єгаре", uk: "пояснювати", en: "explain", ru: "объяснять", ex_no: "Puoi spiegare la regola di nuovo?", ex_uk: "Можеш пояснити правило ще раз?", en_ex: "Can you explain the rule again?", ru_ex: "Можешь объяснить правило ещё раз?" },
            { t: "Дієслова", no: "credere", pron: "креdере", uk: "вірити", en: "believe", ru: "верить", ex_no: "Credo che lei abbia ragione.", ex_uk: "Я вірю, що вона має рацію.", en_ex: "I believe she is right.", ru_ex: "Я верю, что она права." },
            { t: "Дієслова", no: "provare", pron: "проваре", uk: "пробувати", en: "try", ru: "пытаться", ex_no: "Sto provando a imparare l'italiano.", ex_uk: "Я намагаюся вивчити італійську.", en_ex: "I'm trying to learn Italian.", ru_ex: "Я пытаюсь выучить итальянский." },
            { t: "Дієслова", no: "decidere", pron: "дечiдере", uk: "вирішувати", en: "decide", ru: "решать", ex_no: "Ho deciso di trasferirmi a Roma.", ex_uk: "Я вирішив переїхати до Риму.", en_ex: "I decided to move to Rome.", ru_ex: "Я решил переехать в Рим." },
            { t: "Дієслова", no: "ammettere", pron: "аммeттере", uk: "визнавати", en: "admit", ru: "признавать", ex_no: "Ha ammesso il suo errore.", ex_uk: "Він визнав свою помилку.", en_ex: "He admitted his mistake.", ru_ex: "Он признал свою ошибку." },
            { t: "Дієслова", no: "evitare", pron: "евiтаре", uk: "уникати", en: "avoid", ru: "избегать", ex_no: "Dovremmo evitare i rischi.", ex_uk: "Нам слід уникати ризиків.", en_ex: "We should avoid risks.", ru_ex: "Нам следует избегать рисков." },
            { t: "Кар'єра", no: "la carriera", pron: "ля карр'єра", uk: "кар'єра", en: "career", ru: "карьера", ex_no: "Ha una carriera di successo.", ex_uk: "Вона має успішну кар'єру.", en_ex: "She has a successful career.", ru_ex: "У неё успешная карьера." },
            { t: "Кар'єра", no: "il colloquio", pron: "іль коллокуйо", uk: "співбесіда", en: "interview", ru: "собеседование", ex_no: "Il colloquio è andato bene.", ex_uk: "Співбесіда пройшла добре.", en_ex: "The interview went well.", ru_ex: "Собеседование прошло хорошо." },
            { t: "Кар'єра", no: "il collega", pron: "іль коллeга", uk: "колега", en: "colleague", ru: "коллега", ex_no: "I miei colleghi sono gentili.", ex_uk: "Мої колеги привітні.", en_ex: "My colleagues are friendly.", ru_ex: "Мои коллеги приветливы." },
            { t: "Кар'єра", no: "la domanda", pron: "ля домaнда", uk: "заявка", en: "application", ru: "заявка", ex_no: "Ho presentato la mia domanda ieri.", ex_uk: "Я подав заявку вчора.", en_ex: "I submitted my application yesterday.", ru_ex: "Я подал заявку вчера." },
        ],
        // -------------------- B2 --------------------
        B2: [
            { t: "Політика", no: "il governo", pron: "іль ґовeрно", uk: "уряд", en: "government", ru: "правительство", ex_no: "Il governo ha presentato un nuovo bilancio.", ex_uk: "Уряд представив новий бюджет.", en_ex: "The government presented a new budget.", ru_ex: "Правительство представило новый бюджет." },
            { t: "Політика", no: "le elezioni", pron: "ле елецьонi", uk: "вибори", en: "election", ru: "выборы", ex_no: "Le elezioni sono il mese prossimo.", ex_uk: "Вибори наступного місяця.", en_ex: "The election is next month.", ru_ex: "Выборы в следующем месяце." },
            { t: "Політика", no: "la democrazia", pron: "ля демократцiя", uk: "демократія", en: "democracy", ru: "демократия", ex_no: "La libertà di parola è un pilastro della democrazia.", ex_uk: "Свобода слова — основа демократії.", en_ex: "Freedom of speech is a cornerstone of democracy.", ru_ex: "Свобода слова — основа демократии." },
            { t: "Політика", no: "l'opposizione", pron: "лоппозiцьоне", uk: "опозиція", en: "opposition", ru: "оппозиция", ex_no: "L'opposizione ha criticato la proposta.", ex_uk: "Опозиція розкритикувала пропозицію.", en_ex: "The opposition criticized the proposal.", ru_ex: "Оппозиция раскритиковала предложение." },
            { t: "Економіка", no: "l'economia", pron: "лекономiя", uk: "економіка", en: "economy", ru: "экономика", ex_no: "L'economia sta crescendo lentamente.", ex_uk: "Економіка зростає повільно.", en_ex: "The economy is growing slowly.", ru_ex: "Экономика растёт медленно." },
            { t: "Економіка", no: "il mercato", pron: "іль меркaто", uk: "ринок", en: "market", ru: "рынок", ex_no: "Il mercato ha reagito alla notizia.", ex_uk: "Ринок відреагував на новину.", en_ex: "The market reacted to the news.", ru_ex: "Рынок отреагировал на новость." },
            { t: "Економіка", no: "l'inflazione", pron: "лiнфлацьоне", uk: "інфляція", en: "inflation", ru: "инфляция", ex_no: "L'inflazione è aumentata notevolmente.", ex_uk: "Інфляція різко зросла.", en_ex: "Inflation has risen sharply.", ru_ex: "Инфляция резко выросла." },
            { t: "Економіка", no: "l'investimento", pron: "лiнвестiменто", uk: "інвестиція", en: "investment", ru: "инвестиция", ex_no: "L'investimento a lungo termine è importante.", ex_uk: "Довгострокові інвестиції важливі.", en_ex: "Long-term investment is important.", ru_ex: "Долгосрочные инвестиции важны." },
            { t: "Наука", no: "la ricerca", pron: "ля рiчeрка", uk: "дослідження", en: "research", ru: "исследование", ex_no: "Nuove ricerche mostrano risultati sorprendenti.", ex_uk: "Нове дослідження показує несподівані результати.", en_ex: "New research shows surprising results.", ru_ex: "Новое исследование показывает неожиданные результаты." },
            { t: "Наука", no: "la teoria", pron: "ля теорiя", uk: "теорія", en: "theory", ru: "теория", ex_no: "La teoria è stata confermata dagli esperimenti.", ex_uk: "Теорію підтвердили експерименти.", en_ex: "The theory was confirmed by experiments.", ru_ex: "Теорию подтвердили эксперименты." },
            { t: "Наука", no: "l'esperimento", pron: "леспермiенто", uk: "експеримент", en: "experiment", ru: "эксперимент", ex_no: "Hanno condotto un esperimento controllato.", ex_uk: "Вони провели контрольований експеримент.", en_ex: "They conducted a controlled experiment.", ru_ex: "Они провели контролируемый эксперимент." },
            { t: "Наука", no: "i dati", pron: "і датi", uk: "дані", en: "data", ru: "данные", ex_no: "I dati sono stati raccolti per diversi mesi.", ex_uk: "Дані збирали протягом кількох місяців.", en_ex: "Data was collected over several months.", ru_ex: "Данные собирали в течение нескольких месяцев." },
            { t: "Культура", no: "l'arte", pron: "ляrте", uk: "мистецтво", en: "art", ru: "искусство", ex_no: "La mostra presenta arte moderna.", ex_uk: "Виставка демонструє сучасне мистецтво.", en_ex: "The exhibition shows modern art.", ru_ex: "Выставка демонстрирует современное искусство." },
            { t: "Культура", no: "la letteratura", pron: "ля леттература", uk: "література", en: "literature", ru: "литература", ex_no: "Studia letteratura italiana.", ex_uk: "Вона вивчає італійську літературу.", en_ex: "She studies Italian literature.", ru_ex: "Она изучает итальянскую литературу." },
            { t: "Культура", no: "l'autore", pron: "лаутoре", uk: "автор", en: "author", ru: "автор", ex_no: "L'autore ha ricevuto riconoscimenti.", ex_uk: "Автор отримав визнання.", en_ex: "The author received recognition.", ru_ex: "Автор получил признание." },
            { t: "Дієслова", no: "influenzare", pron: "iнфлюенцaре", uk: "впливати", en: "influence", ru: "влиять", ex_no: "I media influenzano l'opinione pubblica.", ex_uk: "ЗМІ впливають на громадську думку.", en_ex: "The media influences public opinion.", ru_ex: "СМИ влияют на общественное мнение." },
            { t: "Дієслова", no: "valutare", pron: "валутaре", uk: "оцінювати", en: "assess", ru: "оценивать", ex_no: "Dobbiamo valutare la situazione.", ex_uk: "Нам потрібно оцінити ситуацію.", en_ex: "We need to assess the situation.", ru_ex: "Нам нужно оценить ситуацию." },
            { t: "Дієслова", no: "sviluppare", pron: "звiлуппaре", uk: "розвивати", en: "develop", ru: "развивать", ex_no: "L'azienda sta sviluppando nuovi prodotti.", ex_uk: "Компанія розробляє нові продукти.", en_ex: "The company is developing new products.", ru_ex: "Компания разрабатывает новые продукты." },
            { t: "Дієслова", no: "presentare", pron: "презентaре", uk: "представляти", en: "present", ru: "представлять", ex_no: "Ha presentato i risultati al consiglio.", ex_uk: "Вона представила результати правлінню.", en_ex: "She presented the results to the board.", ru_ex: "Она представила результаты правлению." },
            { t: "Дієслова", no: "analizzare", pron: "аналiзaре", uk: "аналізувати", en: "analyze", ru: "анализировать", ex_no: "Dobbiamo analizzare i dati.", ex_uk: "Нам потрібно проаналізувати дані.", en_ex: "We need to analyze the data.", ru_ex: "Нам нужно проанализировать данные." },
            { t: "Дієслова", no: "concludere", pron: "конклюдере", uk: "робити висновок", en: "conclude", ru: "делать вывод", ex_no: "Il rapporto conclude che la misura ha funzionato.", ex_uk: "Звіт робить висновок, що захід спрацював.", en_ex: "The report concludes that the measure worked.", ru_ex: "Отчёт делает вывод, что мера сработала." },
            { t: "Бізнес", no: "l'azienda", pron: "лацьєнда", uk: "бізнес", en: "business", ru: "бизнес", ex_no: "L'azienda sta andando bene quest'anno.", ex_uk: "Цього року бізнес іде добре.", en_ex: "Business is going well this year.", ru_ex: "В этом году бизнес идёт хорошо." },
            { t: "Бізнес", no: "la strategia", pron: "ля стратeджя", uk: "стратегія", en: "strategy", ru: "стратегия", ex_no: "Abbiamo bisogno di una nuova strategia.", ex_uk: "Нам потрібна нова стратегія.", en_ex: "We need a new strategy.", ru_ex: "Нам нужна новая стратегия." },
            { t: "Бізнес", no: "la concorrenza", pron: "ля конкоррeнца", uk: "конкуренція", en: "competition", ru: "конкуренция", ex_no: "La concorrenza è agguerrita.", ex_uk: "Конкуренція є жорсткою.", en_ex: "Competition is intense.", ru_ex: "Конкуренция жёсткая." },
            { t: "Бізнес", no: "la negoziazione", pron: "ля неґоцяцьоне", uk: "переговори", en: "negotiation", ru: "переговоры", ex_no: "Le negoziazioni sono in corso.", ex_uk: "Переговори тривають.", en_ex: "Negotiations are underway.", ru_ex: "Переговоры продолжаются." },
            { t: "Медицина", no: "il sintomo", pron: "іль сiнтомо", uk: "симптом", en: "symptom", ru: "симптом", ex_no: "La febbre è un sintomo comune.", ex_uk: "Температура — поширений симптом.", en_ex: "Fever is a common symptom.", ru_ex: "Температура — распространённый симптом." },
            { t: "Медицина", no: "cronico", pron: "крoнiко", uk: "хронічний", en: "chronic", ru: "хронический", ex_no: "Ha una malattia cronica.", ex_uk: "Він має хронічну хворобу.", en_ex: "He has a chronic illness.", ru_ex: "У него хроническое заболевание." },
            { t: "Медицина", no: "l'epidemia", pron: "лепiдемiя", uk: "епідемія", en: "epidemic", ru: "эпидемия", ex_no: "L'epidemia si è diffusa rapidamente.", ex_uk: "Епідемія швидко поширилася.", en_ex: "The epidemic spread quickly.", ru_ex: "Эпидемия быстро распространилась." },
            { t: "Медицина", no: "la prevenzione", pron: "ля превенцьоне", uk: "профілактика", en: "prevention", ru: "профилактика", ex_no: "La prevenzione è meglio che curare.", ex_uk: "Профілактика краща за лікування.", en_ex: "Prevention is better than cure.", ru_ex: "Профилактика лучше лечения." },
        ],
        // -------------------- C1 --------------------
        C1: [
            { t: "Дискурс", no: "tuttavia", pron: "туттавiя", uk: "однак", en: "however", ru: "однако", ex_no: "I risultati erano promettenti; tuttavia c'è ancora lavoro da fare.", ex_uk: "Результати були обнадійливі; однак роботи ще багато.", en_ex: "The results were promising; however, there is still work to do.", ru_ex: "Результаты были обнадёживающими; однако работы ещё много." },
            { t: "Дискурс", no: "inoltre", pron: "iнoлтре", uk: "крім того", en: "moreover", ru: "кроме того", ex_no: "Il progetto è costoso e inoltre richiede tempo.", ex_uk: "Проєкт дорогий, і до того ж забирає багато часу.", en_ex: "The project is expensive, and moreover time-consuming.", ru_ex: "Проект дорогой, и к тому же отнимает много времени." },
            { t: "Дискурс", no: "di conseguenza", pron: "дi консегуeнца", uk: "отже", en: "consequently", ru: "следовательно", ex_no: "La domanda è diminuita e di conseguenza i prezzi sono scesi.", ex_uk: "Попит впав, і ціни, відповідно, знизилися.", en_ex: "Demand fell, and prices consequently dropped.", ru_ex: "Спрос упал, и цены, соответственно, снизились." },
            { t: "Дискурс", no: "nonostante", pron: "ноностaнте", uk: "незважаючи на", en: "despite", ru: "несмотря на", ex_no: "Nonostante le difficoltà, hanno completato il progetto.", ex_uk: "Незважаючи на труднощі, вони завершили проєкт.", en_ex: "Despite the challenges, they completed the project.", ru_ex: "Несмотря на трудности, они завершили проект." },
            { t: "Дискурс", no: "in altre parole", pron: "iн aльтре пaроле", uk: "іншими словами", en: "in other words", ru: "другими словами", ex_no: "In altre parole, la situazione è più complicata.", ex_uk: "Іншими словами, ситуація складніша.", en_ex: "In other words, the situation is more complicated.", ru_ex: "Другими словами, ситуация сложнее." },
            { t: "Нюанси", no: "implicare", pron: "iмплiкaре", uk: "натякати", en: "imply", ru: "намекать", ex_no: "Il rapporto implica che diversi fattori siano in gioco.", ex_uk: "Звіт натякає, що діють кілька факторів.", en_ex: "The report implies that several factors are at play.", ru_ex: "Отчёт намекает, что действуют несколько факторов." },
            { t: "Нюанси", no: "sottolineare", pron: "соттолiнeаре", uk: "підкреслювати", en: "emphasize", ru: "подчёркивать", ex_no: "Il relatore ha sottolineato l'importanza della cooperazione.", ex_uk: "Доповідач підкреслив важливість співпраці.", en_ex: "The speaker emphasized the importance of cooperation.", ru_ex: "Докладчик подчеркнул важность сотрудничества." },
            { t: "Нюанси", no: "comprovare", pron: "компровaре", uk: "обґрунтовувати", en: "substantiate", ru: "обосновывать", ex_no: "Devi comprovare la tua affermazione con prove.", ex_uk: "Тобі потрібно обґрунтувати своє твердження доказами.", en_ex: "You need to substantiate your claim with evidence.", ru_ex: "Тебе нужно обосновать своё утверждение доказательствами." },
            { t: "Нюанси", no: "sfumato", pron: "сфумaто", uk: "нюансований", en: "nuanced", ru: "нюансированный", ex_no: "Il dibattito richiede un approccio più sfumato.", ex_uk: "Дебати потребують більш нюансованого підходу.", en_ex: "The debate requires a more nuanced approach.", ru_ex: "Дебаты требуют более нюансированного подхода." },
            { t: "Нюанси", no: "completo", pron: "комплeто", uk: "всеохопний", en: "comprehensive", ru: "всеобъемлющий", ex_no: "Questo è uno studio completo.", ex_uk: "Це всеохопне дослідження.", en_ex: "This is a comprehensive study.", ru_ex: "Это всеобъемлющее исследование." },
            { t: "Академічна", no: "l'ipotesi", pron: "лiпoтезi", uk: "гіпотеза", en: "hypothesis", ru: "гипотеза", ex_no: "I ricercatori hanno testato l'ipotesi.", ex_uk: "Науковці перевірили гіпотезу.", en_ex: "The researchers tested the hypothesis.", ru_ex: "Учёные проверили гипотезу." },
            { t: "Академічна", no: "la metodologia", pron: "ля метoдолoджя", uk: "методологія", en: "methodology", ru: "методология", ex_no: "La metodologia è descritta chiaramente.", ex_uk: "Методологія чітко описана.", en_ex: "The methodology is clearly described.", ru_ex: "Методология четко описана." },
            { t: "Академічна", no: "la prospettiva", pron: "ля проспеттiва", uk: "перспектива", en: "perspective", ru: "перспектива", ex_no: "Da una prospettiva storica, l'evento è stato significativo.", ex_uk: "З історичної перспективи подія була значущою.", en_ex: "From a historical perspective, the event was significant.", ru_ex: "С исторической точки зрения событие было значимым." },
            { t: "Академічна", no: "la critica delle fonti", pron: "ля крiтiка деллe фонтi", uk: "критика джерел", en: "source criticism", ru: "критика источников", ex_no: "Una buona critica delle fonti è fondamentale.", ex_uk: "Гарна критика джерел є вирішальною.", en_ex: "Good source criticism is crucial.", ru_ex: "Хорошая критика источников имеет решающее значение." },
            { t: "Філософія", no: "l'esistenza", pron: "лезiстeнца", uk: "існування", en: "existence", ru: "существование", ex_no: "La questione dell'esistenza è eterna.", ex_uk: "Питання про існування вічне.", en_ex: "The question of existence is eternal.", ru_ex: "Вопрос о существовании вечен." },
            { t: "Філософія", no: "la coscienza", pron: "ля кошeнца", uk: "свідомість", en: "consciousness", ru: "сознание", ex_no: "La coscienza è un fenomeno complesso.", ex_uk: "Свідомість — складне явище.", en_ex: "Consciousness is a complex phenomenon.", ru_ex: "Сознание — сложное явление." },
            { t: "Філософія", no: "l'etica", pron: "лeтiка", uk: "етика", en: "ethics", ru: "этика", ex_no: "L'etica riguarda ciò che è giusto e sbagliato.", ex_uk: "Етика стосується того, що правильно, а що ні.", en_ex: "Ethics deals with what is right and wrong.", ru_ex: "Этика касается того, что правильно, а что нет." },
            { t: "Лінгвістика", no: "la sintassi", pron: "ля сiнтaссi", uk: "синтаксис", en: "syntax", ru: "синтаксис", ex_no: "La sintassi è lo studio della struttura delle frasi.", ex_uk: "Синтаксис — це вивчення структури речень.", en_ex: "Syntax is the study of sentence structure.", ru_ex: "Синтаксис — это изучение структуры предложений." },
            { t: "Лінгвістика", no: "la semantica", pron: "ля семaнтiка", uk: "семантика", en: "semantics", ru: "семантика", ex_no: "La semantica si occupa del significato.", ex_uk: "Семантика займається значенням.", en_ex: "Semantics deals with meaning.", ru_ex: "Семантика занимается значением." },
            { t: "Соціологія", no: "la disuguaglianza sociale", pron: "ля дiзугуальяnца сошaле", uk: "соціальна нерівність", en: "social inequality", ru: "социальное неравенство", ex_no: "La disuguaglianza sociale è un problema grave.", ex_uk: "Соціальна нерівність — велика проблема.", en_ex: "Social inequality is a major problem.", ru_ex: "Социальное неравенство — большая проблема." },
            { t: "Соціологія", no: "l'integrazione", pron: "лiнтеграцьоне", uk: "інтеграція", en: "integration", ru: "интеграция", ex_no: "L'integrazione degli immigrati è importante.", ex_uk: "Інтеграція іммігрантів важлива.", en_ex: "Integration of immigrants is important.", ru_ex: "Интеграция иммигрантов важна." },
            { t: "Соціологія", no: "la diversità", pron: "ля дiверсiтa", uk: "різноманіття", en: "diversity", ru: "разнообразие", ex_no: "La diversità arricchisce la società.", ex_uk: "Різноманіття збагачує суспільство.", en_ex: "Diversity enriches society.", ru_ex: "Разнообразие обогащает общество." },
            { t: "Психологія", no: "la cognizione", pron: "ля коньiцьоне", uk: "когніція", en: "cognition", ru: "когниция", ex_no: "La cognizione include pensiero e memoria.", ex_uk: "Когніція охоплює мислення та пам'ять.", en_ex: "Cognition includes thinking and memory.", ru_ex: "Когниция охватывает мышление и память." },
            { t: "Психологія", no: "l'emozione", pron: "лемоцьоне", uk: "емоція", en: "emotion", ru: "эмоция", ex_no: "Le emozioni influenzano le nostre scelte.", ex_uk: "Емоції впливають на наш вибір.", en_ex: "Emotions influence our choices.", ru_ex: "Эмоции влияют на наш выбор." },
            { t: "Психологія", no: "il comportamento", pron: "іль компортаменто", uk: "поведінка", en: "behavior", ru: "поведение", ex_no: "Il suo comportamento è stato inaspettato.", ex_uk: "Його поведінка була несподіваною.", en_ex: "His behavior was unexpected.", ru_ex: "Его поведение было неожиданным." },
            { t: "Психологія", no: "la motivazione", pron: "ля мотiвацьоне", uk: "мотивація", en: "motivation", ru: "мотивация", ex_no: "La motivazione viene dall'interno.", ex_uk: "Мотивація походить зсередини.", en_ex: "Motivation comes from within.", ru_ex: "Мотивация исходит изнутри." },
        ],
        // -------------------- C2 --------------------
        C2: [
            { t: "Ідіоми", no: "uccidere due piccioni con una fava", pron: "уччiдере дуе пiччонi кон уна фaва", uk: "убити двох зайців", en: "to kill two birds with one stone", ru: "убить двух зайцев", ex_no: "Lavorando da casa uccido due piccioni con una fava.", ex_uk: "Працюючи з дому, я вбиваю двох зайців.", en_ex: "By working from home I kill two birds with one stone.", ru_ex: "Работая из дома, я убиваю двух зайцев." },
            { t: "Ідіоми", no: "ingoiare il rospo", pron: "iнґояре іль рoспо", uk: "проковтнути гірку пігулку", en: "to bite the bullet", ru: "проглотить горькую пилюлю", ex_no: "Ho dovuto ingoiare il rospo e ammettere che avevo torto.", ex_uk: "Мені довелося проковтнути гірку пігулку і визнати, що я помилявся.", en_ex: "I had to bite the bullet and admit I was wrong.", ru_ex: "Мне пришлось проглотить горькую пилюлю и признать, что я ошибался." },
            { t: "Ідіоми", no: "gettare perle ai porci", pron: "джеттaре перле ай пoрчi", uk: "метати бісер перед свинями", en: "to cast pearls before swine", ru: "метать бисер перед свиньями", ex_no: "Spiegarglielo è come gettare perle ai porci.", ex_uk: "Пояснювати йому це — все одно що метати бісер перед свинями.", en_ex: "Explaining it to him is like casting pearls before swine.", ru_ex: "Объяснять ему это — всё равно что метать бисер перед свиньями." },
            { t: "Ідіоми", no: "avere grande influenza", pron: "авeре гранде iнфлюенца", uk: "мати великий вплив", en: "to hold great sway", ru: "иметь большое влияние", ex_no: "Ha grande influenza nel settore.", ex_uk: "Він має величезний вплив у галузі.", en_ex: "He holds great sway in the industry.", ru_ex: "Он имеет большое влияние в отрасли." },
            { t: "Ідіоми", no: "dipingere un quadro cupo", pron: "дiпiнджере ун куадро купo", uk: "згущувати фарби", en: "to paint a bleak picture", ru: "сгущать краски", ex_no: "Non dipingere un quadro cupo; si risolverà.", ex_uk: "Не згущуй фарби; все владнається.", en_ex: "Don't paint a bleak picture; it'll work out.", ru_ex: "Не сгущай краски; всё уладится." },
            { t: "Ідіоми", no: "gettare la spugna", pron: "джеттaре ля спуnья", uk: "здатися", en: "to throw in the towel", ru: "сдаться", ex_no: "Dopo diverse sconfitte, ha gettato la spugna.", ex_uk: "Після кількох поразок він здався.", en_ex: "After several defeats, he threw in the towel.", ru_ex: "После нескольких поражений он сдался." },
            { t: "Ідіоми", no: "cascare nella trappola", pron: "каскаре нeлла трaппола", uk: "попастися на гачок", en: "to fall for a trick", ru: "попасться на удочку", ex_no: "È cascato nella trappola e ha perso soldi.", ex_uk: "Він попався на шахрайство і втратив гроші.", en_ex: "He fell for the scam and lost money.", ru_ex: "Он попался на аферу и потерял деньги." },
            { t: "Стилістика", no: "la narrativa", pron: "ля наррaтiва", uk: "художня література", en: "fiction", ru: "художественная литература", ex_no: "Preferisce la narrativa alla saggistica.", ex_uk: "Вона надає перевагу художній літературі перед науковою.", en_ex: "She prefers fiction to non-fiction.", ru_ex: "Она предпочитает художественную литературу научной." },
            { t: "Стилістика", no: "la satira", pron: "ля сaтiра", uk: "сатира", en: "satire", ru: "сатира", ex_no: "Lo spettacolo usa la satira per commentare la politica.", ex_uk: "Шоу використовує сатиру для коментування політики.", en_ex: "The show uses satire to comment on politics.", ru_ex: "Шоу использует сатиру для комментирования политики." },
            { t: "Стилістика", no: "l'ironia", pron: "лiронiя", uk: "іронія", en: "irony", ru: "ирония", ex_no: "Il suo commento era ironico.", ex_uk: "Його коментар був іронією.", en_ex: "His comment was ironic.", ru_ex: "Его комментарий был иронией." },
            { t: "Рідкісна лексика", no: "effimero", pron: "еффiмеро", uk: "минущий", en: "transient", ru: "преходящий", ex_no: "La fama può essere effimera.", ex_uk: "Слава може бути минущою.", en_ex: "Fame can be transient.", ru_ex: "Слава может быть преходящей." },
            { t: "Рідкісна лексика", no: "imprevedibile", pron: "iмпревeдiбiле", uk: "непередбачуваний", en: "unpredictable", ru: "непредсказуемый", ex_no: "Il tempo è imprevedibile.", ex_uk: "Погода непередбачувана.", en_ex: "The weather is unpredictable.", ru_ex: "Погода непредсказуема." },
            { t: "Рідкісна лексика", no: "inevitabile", pron: "iневiтaбiле", uk: "неминучий", en: "inevitable", ru: "неизбежный", ex_no: "Il conflitto sembrava inevitabile.", ex_uk: "Конфлікт здавався неминучим.", en_ex: "The conflict seemed inevitable.", ru_ex: "Конфликт казался неизбежным." },
            { t: "Риторика", no: "la retorica", pron: "ля рeторiка", uk: "риторика", en: "rhetoric", ru: "риторика", ex_no: "La retorica è l'arte della persuasione.", ex_uk: "Риторика — це мистецтво переконання.", en_ex: "Rhetoric is the art of persuasion.", ru_ex: "Риторика — это искусство убеждения." },
            { t: "Риторика", no: "l'argomentazione", pron: "ляргоментацьоне", uk: "аргументація", en: "argumentation", ru: "аргументация", ex_no: "La sua argomentazione era solida.", ex_uk: "Його аргументація була вагомою.", en_ex: "His argumentation was solid.", ru_ex: "Его аргументация была убедительной." },
            { t: "Риторика", no: "l'appello", pron: "ляппeлло", uk: "звернення", en: "appeal", ru: "апелляция", ex_no: "L'appello alle emozioni era forte.", ex_uk: "Звернення до емоцій було сильним.", en_ex: "The appeal to emotions was strong.", ru_ex: "Обращение к эмоциям было сильным." },
            { t: "Літературознавство", no: "il motivo", pron: "іль мотiво", uk: "мотив", en: "motif", ru: "мотив", ex_no: "L'amore è un motivo centrale nel libro.", ex_uk: "Кохання — центральний мотив у книзі.", en_ex: "Love is a central motif in the book.", ru_ex: "Любовь — центральный мотив в книге." },
            { t: "Літературознавство", no: "il tema", pron: "іль тема", uk: "тема", en: "theme", ru: "тема", ex_no: "Il tema del romanzo è la solitudine.", ex_uk: "Тема роману — самотність.", en_ex: "The theme of the novel is loneliness.", ru_ex: "Тема романа — одиночество." },
            { t: "Літературознавство", no: "il simbolismo", pron: "іль сiмболiзмо", uk: "символіка", en: "symbolism", ru: "символика", ex_no: "La poesia è ricca di simbolismo.", ex_uk: "Вірш багатий на символіку.", en_ex: "The poem is rich in symbolism.", ru_ex: "Стихотворение богато на символику." },
            { t: "Абстрактне", no: "il contrasto", pron: "іль контрaсто", uk: "контраст", en: "contrast", ru: "контраст", ex_no: "Il contrasto tra ricchi e poveri è netto.", ex_uk: "Контраст між багатими та бідними різкий.", en_ex: "The contrast between rich and poor is stark.", ru_ex: "Контраст между богатыми и бедными резкий." },
            { t: "Абстрактне", no: "escludere", pron: "ескьюдере", uk: "виключати", en: "exclude", ru: "исключать", ex_no: "Non dobbiamo escludere nessuno.", ex_uk: "Ми не повинні нікого виключати.", en_ex: "We must not exclude anyone.", ru_ex: "Мы не должны никого исключать." },
            { t: "Абстрактне", no: "includere", pron: "iнклюдере", uk: "включати", en: "include", ru: "включать", ex_no: "Tutti dovrebbero essere inclusi.", ex_uk: "Усі повинні бути включені.", en_ex: "Everyone should be included.", ru_ex: "Все должны быть включены." },
            { t: "Абстрактне", no: "il contesto", pron: "іль контeсто", uk: "контекст", en: "context", ru: "контекст", ex_no: "Senza contesto, è difficile capire.", ex_uk: "Без контексту важко зрозуміти.", en_ex: "Without context, it's hard to understand.", ru_ex: "Без контекста трудно понять." },
            { t: "Абстрактне", no: "riflettere", pron: "рiфлeттере", uk: "відображати", en: "reflect", ru: "отражать", ex_no: "La conversazione riflette i cambiamenti sociali.", ex_uk: "Розмова відображає соціальні зміни.", en_ex: "The conversation reflects social changes.", ru_ex: "Разговор отражает социальные изменения." },
            { t: "Абстрактне", no: "elaborare", pron: "елаборaре", uk: "деталізувати", en: "elaborate", ru: "детализировать", ex_no: "Puoi elaborare questo punto?", ex_uk: "Можеш детальніше розкрити цей пункт?", en_ex: "Can you elaborate on that point?", ru_ex: "Можешь детальнее раскрыть этот пункт?" },
        ]
    };

    // =====================================================================
    //  GRAMMAR – ГРАМАТИКА ІТАЛІЙСЬКОЇ
    // =====================================================================
    const GRAMMAR = [
        // A1
        {
            id: "it_gr1", level: "A1",
            title: "Essere e avere (presente)",
            exp: "I verbi essere e avere sono fondamentali. Essere si usa per descrivere, avere per possesso.",
            table: { head: ["Pronome", "Essere", "Avere"], rows: [["io", "sono", "ho"], ["tu", "sei", "hai"], ["lui/lei", "è", "ha"], ["noi", "siamo", "abbiamo"], ["voi", "siete", "avete"], ["loro", "sono", "hanno"]] },
            ex: { q: "Io ___ uno studente.", opts: ["sono", "ho", "sei"], a: 0 },
            title_en: "Essere and avere (present)",
            title_ru: "Глаголы essere и avere (настоящее время)",
            exp_en: "Essere and avere are fundamental. Essere describes, avere indicates possession.",
            exp_ru: "Глаголы essere и avere являются фундаментальными. Essere описывает, avere указывает на обладание.",
            head_en: ["Pronoun", "Essere", "Avere"],
            head_ru: ["Местоимение", "Essere", "Avere"],
            q_en: "Io ___ uno studente.",
            q_ru: "Io ___ uno studente.",
        },
        // A2
        {
            id: "it_gr2", level: "A2",
            title: "Passato prossimo",
            exp: "Il passato prossimo si forma con avere/essere + participio passato. Si usa per azioni passate.",
            table: { head: ["Soggetto", "Aux", "Participio"], rows: [["io", "ho", "mangiato"], ["io", "sono", "andato/a"], ["loro", "hanno", "finito"]] },
            ex: { q: "Ieri ___ (mangiare) una pizza.", opts: ["ho mangiato", "sono mangiato", "ha mangiato"], a: 0 },
            title_en: "Passato prossimo",
            title_ru: "Прошедшее время (passato prossimo)",
            exp_en: "Passato prossimo is formed with avere/essere + past participle. Used for past actions.",
            exp_ru: "Passato prossimo образуется с avere/essere + причастие прошедшего времени. Используется для прошедших действий.",
            head_en: ["Subject", "Aux", "Participle"],
            head_ru: ["Подлежащее", "Вспомогательный", "Причастие"],
            q_en: "Ieri ___ (mangiare) una pizza.",
            q_ru: "Ieri ___ (mangiare) una pizza.",
        },
        // B1
        {
            id: "it_gr3", level: "B1",
            title: "Futuro semplice",
            exp: "Il futuro semplice si forma con l'infinito + desinenze: -ò, -ai, -à, -emo, -ete, -anno.",
            table: { head: ["Pronome", "Futuro di parlare"], rows: [["io", "parlerò"], ["tu", "parlerai"], ["lui/lei", "parlerà"], ["noi", "parleremo"], ["voi", "parlerete"], ["loro", "parleranno"]] },
            ex: { q: "Domani ___ (andare) al cinema.", opts: ["andrò", "vado", "sono andato"], a: 0 },
            title_en: "Futuro semplice",
            title_ru: "Будущее простое время",
            exp_en: "Futuro semplice is formed with infinitive + endings.",
            exp_ru: "Futuro semplice образуется с инфинитив + окончания.",
            head_en: ["Pronoun", "Futuro"],
            head_ru: ["Местоимение", "Futuro"],
            q_en: "Domani ___ (andare) al cinema.",
            q_ru: "Domani ___ (andare) al cinema.",
        },
        // B2
        {
            id: "it_gr4", level: "B2",
            title: "Congiuntivo presente",
            exp: "Il congiuntivo presente si usa per esprimere dubbio, desiderio, opinione. Si forma con che + congiuntivo.",
            table: { head: ["Verbo", "Congiuntivo di parlare"], rows: [["che io", "parli"], ["che tu", "parli"], ["che lui/lei", "parli"], ["che noi", "parliamo"], ["che voi", "parliate"], ["che loro", "parlino"]] },
            ex: { q: "Penso che ___ (essere) una buona idea.", opts: ["sia", "è", "fosse"], a: 0 },
            title_en: "Congiuntivo presente",
            title_ru: "Настоящее сослагательное наклонение",
            exp_en: "Used to express doubt, wish, opinion.",
            exp_ru: "Используется для выражения сомнения, желания, мнения.",
            head_en: ["Verb", "Congiuntivo"],
            head_ru: ["Глагол", "Сослагательное"],
            q_en: "Penso che ___ (essere) una buona idea.",
            q_ru: "Penso che ___ (essere) una buona idea.",
        },
        // C1
        {
            id: "it_gr5", level: "C1",
            title: "Periodo ipotetico",
            exp: "Il periodo ipotetico esprime condizioni. Tipo 3: se + trapassato prossimo, condizionale passato.",
            table: { head: ["If-clause", "Main clause"], rows: [["Se avessi saputo", "sarei venuto"]] },
            ex: { q: "Se ___ (sapere), ti avrei aiutato.", opts: ["avessi saputo", "sapevo", "ho saputo"], a: 0 },
            title_en: "Conditional clauses",
            title_ru: "Условные предложения",
            exp_en: "Expresses conditions.",
            exp_ru: "Выражает условия.",
            head_en: ["If-clause", "Main clause"],
            head_ru: ["Условие", "Следствие"],
            q_en: "Se ___ (sapere), ti avrei aiutato.",
            q_ru: "Se ___ (sapere), ti avrei aiutato.",
        },
        // C2
        {
            id: "it_gr6", level: "C2",
            title: "Congiuntivo trapassato",
            exp: "Usato per esprimere un'azione passata non reale nel periodo ipotetico o dopo espressioni di dubbio.",
            table: { head: ["Esempio"], rows: [["Se avessi avuto tempo, sarei venuto."]] },
            ex: { q: "Se ___ (avere) tempo, sarei andato.", opts: ["avessi avuto", "ho avuto", "avevo"], a: 0 },
            title_en: "Congiuntivo trapassato",
            title_ru: "Сослагательное прошедшее время",
            exp_en: "Used for unreal past actions.",
            exp_ru: "Используется для нереальных действий в прошлом.",
            head_en: ["Example"],
            head_ru: ["Пример"],
            q_en: "Se ___ (avere) tempo, sarei andato.",
            q_ru: "Se ___ (avere) tempo, sarei andato.",
        },
    ];

    // =====================================================================
    //  NORSKPROVE_TASKS – ЗАВДАННЯ ДЛЯ ПРАКТИКИ (Аналог Norskprøve)
    // =====================================================================
    const NORSKPROVE_TASKS = {
        A1: {
            reading: [
                {
                    title: "Ciao!",
                    text: "Ciao! Mi chiamo Anna. Vengo dalla Polonia. Vivo a Roma. Sono una studentessa. Mi piace la cucina italiana.",
                    questions: [
                        { q: "Da dove viene Anna?", opts: ["Norvegia", "Polonia", "Svezia"], a: 1 },
                        { q: "Cosa fa Anna?", opts: ["È un'insegnante", "È una studentessa", "È un medico"], a: 1 },
                        { q: "Dove vive Anna?", opts: ["Bergen", "Roma", "Varsavia"], a: 1 },
                    ],
                },
            ],
            listening: [],
            writing: [],
            speaking: [],
        },
        A2: {
            reading: [
                {
                    title: "Una giornata al negozio",
                    text: "Ieri sono andato al negozio. Ho comprato pane, latte e uova. Il negozio era pieno di gente. Ho incontrato un amico e abbiamo parlato un po'. Poi sono andato a casa.",
                    questions: [
                        { q: "Cosa ho comprato?", opts: ["Pane, latte, formaggio", "Pane, latte, uova", "Uova, formaggio, burro"], a: 1 },
                        { q: "Chi ho incontrato?", opts: ["Un insegnante", "Un amico", "Un medico"], a: 1 },
                        { q: "Dove ero?", opts: ["A scuola", "Al negozio", "Al lavoro"], a: 1 },
                    ],
                },
            ],
            listening: [],
            writing: [],
            speaking: [],
        },
        B1: {
            reading: [
                {
                    title: "Il cambiamento climatico",
                    text: "Il cambiamento climatico è un grande problema. Le temperature aumentano e i ghiacci si sciolgono. Molti animali perdono i loro habitat. Dobbiamo ridurre l'inquinamento e usare energie rinnovabili.",
                    questions: [
                        { q: "Cosa sta succedendo ai ghiacci?", opts: ["Si stanno congelando", "Si stanno sciogliendo", "Stanno crescendo"], a: 1 },
                        { q: "Cosa possiamo fare?", opts: ["Usare più petrolio", "Riciclare", "Guidare di più"], a: 1 },
                        { q: "Cosa minaccia gli animali?", opts: ["La perdita di habitat", "La caccia", "L'inquinamento"], a: 0 },
                    ],
                },
            ],
            listening: [],
            writing: [],
            speaking: [],
        },
        B2: {
            reading: [
                {
                    title: "Il futuro del lavoro",
                    text: "L'automazione cambierà molti mestieri. Alcuni lavori scompariranno, ma ne nasceranno di nuovi. Le competenze digitali diventeranno importanti. I lavoratori dovranno essere flessibili e imparare per tutta la vita.",
                    questions: [
                        { q: "Cosa succederà ad alcuni lavori?", opts: ["Scompariranno", "Diventeranno più sicuri", "Pagheranno meglio"], a: 0 },
                        { q: "Cosa diventerà importante?", opts: ["La forza fisica", "Le competenze digitali", "Le reti sociali"], a: 1 },
                        { q: "Cosa può migliorare la tecnologia?", opts: ["Lo stipendio", "L'ambiente di lavoro", "Il tempo libero"], a: 1 },
                    ],
                },
            ],
            listening: [],
            writing: [],
            speaking: [],
        },
        C1: {
            reading: [
                {
                    title: "L'etica dell'IA",
                    text: "L'intelligenza artificiale solleva nuove questioni etiche. Chi è responsabile quando un algoritmo sbaglia? L'IA dovrebbe avere diritti? Allo stesso tempo, l'IA può contribuire alla ricerca medica e alla modellizzazione climatica.",
                    questions: [
                        { q: "Cosa solleva l'IA?", opts: ["Nuove questioni etiche", "Problemi tecnici", "Crescita economica"], a: 0 },
                        { q: "A cosa può contribuire l'IA?", opts: ["Alla ricerca", "Alla guerra", "Alla sorveglianza"], a: 0 },
                        { q: "Cosa dobbiamo sviluppare?", opts: ["Nuovi algoritmi", "Linee guida", "Più data center"], a: 1 },
                    ],
                },
            ],
            listening: [],
            writing: [],
            speaking: [],
        },
        C2: {
            reading: [
                {
                    title: "Filosofia e scienza",
                    text: "La scienza si basa su presupposti filosofici. La domanda su cosa sia vero e come possiamo saperlo è fondamentale. Il metodo scientifico ci fornisce strumenti, ma non è infallibile. Il pensiero critico è essenziale.",
                    questions: [
                        { q: "Su cosa si basa la scienza?", opts: ["Presupposti filosofici", "Dogmi religiosi", "Potere politico"], a: 0 },
                        { q: "Cosa è essenziale?", opts: ["Il pensiero critico", "I titoli accademici", "La pubblicazione"], a: 0 },
                    ],
                },
            ],
            listening: [],
            writing: [],
            speaking: [],
        },
    };

    // =====================================================================
    //  LEVEL_TEST – ТЕСТ НА РІВЕНЬ ІТАЛІЙСЬКОЇ
    // =====================================================================
    const LEVEL_TEST = [
        // A1
        { lvl: "A1", q: "Ciao! Come ___?", opts: ["stai", "sei", "sono"], a: 0 },
        { lvl: "A1", q: "Io ___ uno studente.", opts: ["sono", "ho", "sei"], a: 0 },
        { lvl: "A1", q: "Lei ___ un medico.", opts: ["è", "sono", "hai"], a: 0 },
        { lvl: "A1", q: "Loro ___ di Roma.", opts: ["sono", "siamo", "ho"], a: 0 },
        { lvl: "A1", q: "Come ti chiami? ___ chiamo Marco.", opts: ["Mi", "Ti", "Si"], a: 0 },
        { lvl: "A1", q: "Ho ___ mela.", opts: ["una", "un", "dell"], a: 0 },
        { lvl: "A1", q: "Questo è ___ cane.", opts: ["un", "uno", "una"], a: 0 },
        { lvl: "A1", q: "Noi ___ a scuola ogni giorno.", opts: ["andiamo", "vanno", "vado"], a: 0 },
        { lvl: "A1", q: "Lei ___ caffè al mattino.", opts: ["beve", "bevo", "bevono"], a: 0 },
        { lvl: "A1", q: "Non mi piace ___ tempo.", opts: ["il", "la", "l'"], a: 0 },
        // A2
        { lvl: "A2", q: "Ieri ___ al cinema.", opts: ["sono andato", "vado", "vai"], a: 0 },
        { lvl: "A2", q: "Lei non mi ___ .", opts: ["ha chiamato", "chiama", "chiamato"], a: 0 },
        { lvl: "A2", q: "___ ti piace il gelato?", opts: ["A", "Di", "Da"], a: 0 },
        { lvl: "A2", q: "Noi ___ a Roma la prossima settimana.", opts: ["andiamo", "vado", "vanno"], a: 0 },
        { lvl: "A2", q: "Lui ___ una macchina.", opts: ["ha", "ho", "hai"], a: 0 },
        { lvl: "A2", q: "Posso ___ aiutare.", opts: ["aiutare", "aiuto", "aiutato"], a: 0 },
        { lvl: "A2", q: "Lei ___ parlare tre lingue.", opts: ["può", "è", "ha"], a: 0 },
        { lvl: "A2", q: "Noi ___ cena alle 7.", opts: ["facciamo", "fanno", "fai"], a: 0 },
        { lvl: "A2", q: "Sono stanco perché ___ tardi.", opts: ["ho lavorato", "lavoro", "lavoravo"], a: 0 },
        { lvl: "A2", q: "___ visto le mie chiavi?", opts: ["Hai", "Ha", "Ho"], a: 0 },
        // B1
        { lvl: "B1", q: "Sono qui ___ il 2015.", opts: ["da", "per", "in"], a: 0 },
        { lvl: "B1", q: "Non ha ancora finito i compiti ___ .", opts: ["ancora", "già", "appena"], a: 0 },
        { lvl: "B1", q: "Il libro ___ scritto dall'insegnante.", opts: ["è", "viene", "ha"], a: 0 },
        { lvl: "B1", q: "Se piove, ___ a casa.", opts: ["restiamo", "resteremo", "rimaniamo"], a: 1 },
        { lvl: "B1", q: "Vorrei ___ più tempo.", opts: ["avere", "ho", "avessi"], a: 0 },
        { lvl: "B1", q: "Lei mi ___ il suo indirizzo ieri.", opts: ["ha dato", "dà", "darà"], a: 0 },
        { lvl: "B1", q: "Sono andati al cinema ___ erano annoiati.", opts: ["perché", "anche se", "ma"], a: 0 },
        { lvl: "B1", q: "Non gli piace ___ in città.", opts: ["vivere", "vive", "vivendo"], a: 0 },
        { lvl: "B1", q: "Prometto che ___ più tardi.", opts: ["telefonerò", "telefono", "telefonavo"], a: 0 },
        { lvl: "B1", q: "Il caffè è ___ caldo per bere.", opts: ["troppo", "abbastanza", "molto"], a: 0 },
        // B2
        { lvl: "B2", q: "___ avesse studiato, avrebbe superato l'esame.", opts: ["Se", "Anche se", "A meno che"], a: 0 },
        { lvl: "B2", q: "Mi ha chiesto ___ andavo.", opts: ["dove", "che", "se"], a: 0 },
        { lvl: "B2", q: "Il film era ___ di quanto pensassi.", opts: ["migliore", "meglio", "buono"], a: 0 },
        { lvl: "B2", q: "Dobbiamo discutere ___ risolvere il problema.", opts: ["come", "cosa", "che"], a: 0 },
        { lvl: "B2", q: "Lui è ___ dei due candidati.", opts: ["il migliore", "migliore", "meglio"], a: 0 },
        { lvl: "B2", q: "Ha negato ___ i soldi.", opts: ["di avere rubato", "aver rubato", "rubare"], a: 1 },
        { lvl: "B2", q: "L'esame era ___ di quanto pensassi.", opts: ["più facile", "facile", "più facile che"], a: 0 },
        { lvl: "B2", q: "Vorrei ___ di più sull'arte.", opts: ["sapere", "sappia", "so"], a: 0 },
        { lvl: "B2", q: "Sarebbero venuti se ___ stati invitati.", opts: ["fossero", "sono", "erano"], a: 0 },
        { lvl: "B2", q: "Questa è la casa ___ sono cresciuto.", opts: ["dove", "che", "la quale"], a: 0 },
        // C1
        { lvl: "C1", q: "Non solo ___ alla riunione, ma ha anche presentato.", opts: ["è venuto", "venne", "veniva"], a: 0 },
        { lvl: "C1", q: "Vorrei ___ la risposta.", opts: ["sapere", "so", "sapessi"], a: 0 },
        { lvl: "C1", q: "È essenziale che ___ in orario.", opts: ["arrivi", "arriva", "arrivasse"], a: 0 },
        { lvl: "C1", q: "Il rapporto ___ entro la fine della giornata.", opts: ["sarà finito", "viene finito", "è finito"], a: 0 },
        { lvl: "C1", q: "Se l'avessi saputo, ___ diversamente.", opts: ["avrei fatto", "farei", "feci"], a: 0 },
        { lvl: "C1", q: "Lei è ___ delle due sorelle.", opts: ["la più alta", "la più alta", "più alta"], a: 0 },
        { lvl: "C1", q: "La proposta è stata respinta, ___ ci aspettavamo.", opts: ["come", "che", "il che"], a: 0 },
        { lvl: "C1", q: "Non posso fare a meno di ___ preoccupato.", opts: ["essere", "essere", "sentirmi"], a: 0 },
        { lvl: "C1", q: "La lezione era ___ lunga per gli studenti.", opts: ["troppo", "così", "molto"], a: 0 },
        { lvl: "C1", q: "Ha una tendenza ___ essere impaziente.", opts: ["a", "di", "per"], a: 0 },
        // C2
        { lvl: "C2", q: "Se fossi ricco, ___ il mondo.", opts: ["girerei", "girerei", "avrei girato"], a: 0 },
        { lvl: "C2", q: "L'uso della metafora da parte dell'autore ___ il lettore.", opts: ["sfida", "sfidano", "sfidante"], a: 0 },
        { lvl: "C2", q: "Poco ___ sapeva cosa l'aspettava.", opts: ["sapeva", "seppe", "sape"], a: 0 },
        { lvl: "C2", q: "Il comitato ___ diviso sulla questione.", opts: ["è", "sono", "erano"], a: 0 },
        { lvl: "C2", q: "È imperativo che il progetto ___ in tempo.", opts: ["sia completato", "viene completato", "venga completato"], a: 0 },
        { lvl: "C2", q: "Il suo argomento era ___ persuasivo.", opts: ["molto", "più", "assai"], a: 0 },
        { lvl: "C2", q: "La ricerca, ___ risultati sono rivoluzionari, ha richiesto anni.", opts: ["i cui", "che", "di cui"], a: 0 },
        { lvl: "C2", q: "Parlava con un'aria di ___ che infastidiva tutti.", opts: ["autorità", "autoritarismo", "autorevolezza"], a: 0 },
        { lvl: "C2", q: "Lo scandalo ha gettato ___ sulla reputazione dell'azienda.", opts: ["dubbi", "ombra", "luce"], a: 1 },
        { lvl: "C2", q: "Lei è una critica ___ del governo.", opts: ["feroce", "agguerrita", "entrambe"], a: 0 },
    ];

    // =====================================================================
    //  ALPHABET — АБЕТКА (італійська)
    // =====================================================================
    // Традиційна італійська абетка — 21 літера (без J, K, W, X, Y, які
    // вживаються лише в запозичених словах); ці 5 додано окремо нижче з
    // поміткою.
    const ALPHABET = [
        { letter: "A a", name: "а", sound: "як українське «а»", example: "amico", example_uk: "друг" },
        { letter: "B b", name: "бі", sound: "як українське «б»", example: "bello", example_uk: "гарний" },
        { letter: "C c", name: "чі", sound: "перед a/o/u — як «к»; перед e/i — як «ч»", example: "casa", example_uk: "будинок" },
        { letter: "D d", name: "ді", sound: "як українське «д»", example: "dove", example_uk: "де" },
        { letter: "E e", name: "е", sound: "як українське «е»", example: "elefante", example_uk: "слон" },
        { letter: "F f", name: "еффе", sound: "як українське «ф»", example: "fiore", example_uk: "квітка" },
        { letter: "G g", name: "джі", sound: "перед a/o/u — як «ґ»; перед e/i — як «дж»", example: "gatto", example_uk: "кіт" },
        { letter: "H h", name: "акка", sound: "не вимовляється взагалі (німа)", example: "ho", example_uk: "маю" },
        { letter: "I i", name: "і", sound: "як українське «і»", example: "isola", example_uk: "острів" },
        { letter: "L l", name: "елле", sound: "як українське «л»", example: "luna", example_uk: "місяць" },
        { letter: "M m", name: "емме", sound: "як українське «м»", example: "mare", example_uk: "море" },
        { letter: "N n", name: "енне", sound: "як українське «н»", example: "notte", example_uk: "ніч" },
        { letter: "O o", name: "о", sound: "як українське «о»", example: "oro", example_uk: "золото" },
        { letter: "P p", name: "пі", sound: "як українське «п»", example: "pane", example_uk: "хліб" },
        { letter: "Q q", name: "ку", sound: "як «к» (завжди разом з «u»: qu)", example: "questo", example_uk: "цей" },
        { letter: "R r", name: "ерре", sound: "легко розкотисте «р»", example: "rosso", example_uk: "червоний" },
        { letter: "S s", name: "ессе", sound: "як українське «с»; між голосними іноді як «з»", example: "sole", example_uk: "сонце" },
        { letter: "T t", name: "ті", sound: "як українське «т»", example: "tempo", example_uk: "час/погода" },
        { letter: "U u", name: "у", sound: "як українське «у»", example: "uva", example_uk: "виноград" },
        { letter: "V v", name: "ву", sound: "як українське «в»", example: "vita", example_uk: "життя" },
        { letter: "Z z", name: "дзета", sound: "як «дз» або «тц» залежно від слова", example: "zero", example_uk: "нуль" },
        { letter: "J j*", name: "і лунга", sound: "*лише в запозиченнях, як «й»", example: "jeans", example_uk: "джинси" },
        { letter: "K k*", name: "каппа", sound: "*лише в запозиченнях, як «к»", example: "kiwi", example_uk: "ківі" },
        { letter: "W w*", name: "доппіа ву", sound: "*лише в запозиченнях, як «в»", example: "weekend", example_uk: "вихідні" },
        { letter: "X x*", name: "ікс", sound: "*лише в запозиченнях, як «кс»", example: "taxi", example_uk: "таксі" },
        { letter: "Y y*", name: "іпсилон", sound: "*лише в запозиченнях, як «і»", example: "yoga", example_uk: "йога" },
    ];

    // =====================================================================
    //  LESSONS — УРОКИ (італійська)
    // =====================================================================
    const LESSONS = [
        {
            id: 1,
            level: 'A1',
            title: 'Знайомство: "Mi chiamo..."',
            title_en: 'Introducing yourself: "Mi chiamo..."',
            title_ru: 'Знакомство: "Mi chiamo..."',
            content: 'В італійській мові, щоб представитися, кажуть "Mi chiamo..." (Мене звати..., буквально "я себе називаю"). ' +
                'Наприклад: "Mi chiamo Anna" — Мене звати Анна.\n\n' +
                'Є й простіший варіант: "Sono Anna" (Я Анна) — дієслово "essere" (бути).\n\n' +
                'Щоб запитати ім\'я співрозмовника: "Come ti chiami?" (Як тебе звати? — неформально) або "Come si chiama?" (формально).\n\n' +
                'Приємно познайомитись — "Piacere" (найпростіший і найпоширеніший варіант).',
            content_en: 'In Italian, to introduce yourself you say "Mi chiamo..." (My name is..., literally "I call myself"). ' +
                'For example: "Mi chiamo Anna" — My name is Anna.\n\n' +
                'There\'s also a simpler option: "Sono Anna" (I am Anna) — using the verb "essere" (to be).\n\n' +
                'To ask for someone\'s name: "Come ti chiami?" (informal) or "Come si chiama?" (formal).\n\n' +
                'Nice to meet you — "Piacere" (the simplest and most common option).',
            content_ru: 'В итальянском языке, чтобы представиться, говорят "Mi chiamo..." (Меня зовут..., буквально "я себя называю"). ' +
                'Например: "Mi chiamo Anna" — Меня зовут Анна.\n\n' +
                'Есть и более простой вариант: "Sono Anna" (Я Анна) — глагол "essere" (быть).\n\n' +
                'Чтобы спросить имя собеседника: "Come ti chiami?" (неформально) или "Come si chiama?" (формально).\n\n' +
                'Приятно познакомиться — "Piacere" (самый простой и распространённый вариант).',
            tasks: [
                {
                    q: 'Як сказати "Мене звати Олена" італійською?',
                    q_en: 'How do you say "My name is Olena" in Italian?',
                    q_ru: 'Как сказать "Меня зовут Елена" по-итальянски?',
                    opts: ['Mi chiamo Olena', 'Ti chiami Olena', 'Si chiama Olena'],
                    a: 0,
                },
                {
                    q: 'Що означає "Come ti chiami?"',
                    q_en: 'What does "Come ti chiami?" mean?',
                    q_ru: 'Что означает "Come ti chiami?"',
                    opts: ['Скільки тобі років?', 'Як тебе звати?', 'Звідки ти?'],
                    a: 1,
                },
                {
                    q: 'Яке дієслово використовується у "Sono Anna"?',
                    q_en: 'Which verb is used in "Sono Anna"?',
                    q_ru: 'Какой глагол используется в "Sono Anna"?',
                    opts: ['chiamarsi', 'essere', 'avere'],
                    a: 1,
                },
            ],
        },

        {
            id: 2,
            level: 'A1',
            title: 'Алфавіт і вимова',
            content: 'Традиційна італійська абетка має 21 літеру — літери J, K, W, X, Y зустрічаються лише в запозичених словах.\n\n| c перед e/i | "ч" | ciao (привіт) |\n| c перед a/o/u | "к" | casa (будинок) |\n| g перед e/i | "дж" | gelato (морозиво) |\n| g перед a/o/u | "ґ" | gatto (кіт) |\n\nОсобливі буквосполучення:\n\n| gli | м\'яке "лі" | famiglia (родина) |\n| gn | "нь" | gnocchi (ньокі) |\n| sc перед e/i | "ш" | pesce (риба) |\n| h | не вимовляється взагалі | ho (маю) |\n\n> Порада: в італійській майже кожне слово читається саме так, як пишеться — на відміну від французької чи англійської. Це робить вимову однією з найлегших частин мови для новачків.\n\nПрактика: спробуй прочитати вголос ~Mi chiamo Anna~ (мене звати Анна) — усі літери вимовляються чітко.',
            tasks: [],
        },
        {
            id: 3,
            level: 'A1',
            title: 'Привітання і знайомство',
            content: 'Найпоширеніше привітання — універсальне ~Ciao~ (привіт/бувай), яке підходить у неформальних ситуаціях у будь-який час.\n\n| Buongiorno | Доброго ранку/дня |\n| Buonasera | Доброго вечора |\n| Buonanotte | На добраніч |\n| Arrivederci | До побачення (формально) |\n| A presto | До скорого |\n\nЩоб представитися, використовуй зворотне дієслово ~chiamarsi~ (називатися):\n\n| Mi chiamo Anna. | Мене звати Анна. |\n| Come ti chiami? | Як тебе звати? |\n| Piacere. | Приємно познайомитись. |\n\nЗапитати, як справи:\n\n| Come stai? | Як у тебе справи? |\n| Bene, grazie! E tu? | Добре, дякую! А в тебе? |\n\n> Порада: ~grazie~ (дякую) та ~prego~ (будь ласка / прошу, у відповідь на подяку) — обов\'язкові слова в будь-якій розмові італійською.\n\nПрактика: складіть коротенький діалог знайомства з двох-трьох реплік, використовуючи фрази вище.',
            tasks: [],
        },

        // === УРОК 4 — встав сюди, скопіювавши шаблон вище ===

    ];

    // =====================================================================
    //  РЕЄСТРАЦІЯ ДАНИХ У ГЛОБАЛЬНИЙ ОБ'ЄКТ
    // =====================================================================
    window.LANG_DATA = window.LANG_DATA || {};
    window.LANG_DATA.it = {
        VOCAB,
        GRAMMAR,
        NORSKPROVE_TASKS,
        LEVEL_TEST,
        ALPHABET,
        LESSONS,
    };
})();
