
// =====================================================================
//  js/data-ja.js — ЯПОНСЬКА МОВА (ПОВНИЙ НАБІР)
//  Повністю сумісний з js/data.js для норвезької.
//  Містить VOCAB, GRAMMAR, NORSKPROVE_TASKS, LEVEL_TEST, ALPHABET, LESSONS.
//
//  Особливість японської: слова записані писемністю мови (хірагана/
//  катакана/кандзі у полі "no"), а вимова (ромадзі) пояснюється в
//  ALPHABET та в текстах уроків — окремого поля вимови в загальній схемі
//  сайту нема, тож на рівнях A1-A2 слова навмисно дано хіраганою/
//  катаканою (без кандзі), щоб їх можна було прочитати одразу, маючи
//  вивчену абетку. З рівня B1 поступово додаються поширені кандзі.
// =====================================================================
(function () {

    // =====================================================================
    //  VOCAB – СЛОВНИК ЗА РІВНЯМИ (A1-C2)
    // =====================================================================
    const VOCAB = {
        // -------------------- A1 --------------------
        A1: [
            { t: "Привітання", no: "こんにちは", pron: "kon'nichiwa", uk: "добрий день / привіт", en: "hello / good afternoon", ru: "добрый день / привет", ex_no: "こんにちは、げんきですか。", ex_uk: "Добрий день, як справи?", en_ex: "Hello, how are you?", ru_ex: "Добрый день, как дела?" },
            { t: "Привітання", no: "おはようございます", pron: "ohayou gozaimasu", uk: "доброго ранку", en: "good morning", ru: "доброе утро", ex_no: "おはようございます、せんせい。", ex_uk: "Доброго ранку, вчителю.", en_ex: "Good morning, teacher.", ru_ex: "Доброе утро, учитель." },
            { t: "Привітання", no: "こんばんは", pron: "konbanwa", uk: "добрий вечір", en: "good evening", ru: "добрый вечер", ex_no: "こんばんは、おげんきですか。", ex_uk: "Добрий вечір, як ви?", en_ex: "Good evening, how are you?", ru_ex: "Добрый вечер, как вы?" },
            { t: "Привітання", no: "さようなら", pron: "sayounara", uk: "до побачення", en: "goodbye", ru: "до свидания", ex_no: "さようなら、またあした。", ex_uk: "До побачення, до завтра.", en_ex: "Goodbye, see you tomorrow.", ru_ex: "До свидания, до завтра." },
            { t: "Привітання", no: "ありがとうございます", pron: "arigatou gozaimasu", uk: "дякую", en: "thank you", ru: "спасибо", ex_no: "ほんとうにありがとうございます。", ex_uk: "Щиро дякую.", en_ex: "Thank you very much.", ru_ex: "Большое спасибо." },
            { t: "Привітання", no: "すみません", pron: "sumimasen", uk: "перепрошую / вибачте", en: "excuse me / sorry", ru: "извините", ex_no: "すみません、えきはどこですか。", ex_uk: "Перепрошую, де станція?", en_ex: "Excuse me, where is the station?", ru_ex: "Извините, где станция?" },
            { t: "Привітання", no: "はい", pron: "hai", uk: "так", en: "yes", ru: "да", ex_no: "はい、そうです。", ex_uk: "Так, це так.", en_ex: "Yes, that's right.", ru_ex: "Да, это так." },
            { t: "Привітання", no: "いいえ", pron: "iie", uk: "ні", en: "no", ru: "нет", ex_no: "いいえ、ちがいます。", ex_uk: "Ні, це не так.", en_ex: "No, that's not right.", ru_ex: "Нет, это не так." },
            { t: "Привітання", no: "はじめまして", pron: "hajimemashite", uk: "приємно познайомитись", en: "nice to meet you", ru: "приятно познакомиться", ex_no: "はじめまして、たなかです。", ex_uk: "Приємно познайомитись, я Танака.", en_ex: "Nice to meet you, I'm Tanaka.", ru_ex: "Приятно познакомиться, я Танака." },
            { t: "Привітання", no: "おねがいします", pron: "onegaishimasu", uk: "будь ласка", en: "please", ru: "пожалуйста", ex_no: "みずをおねがいします。", ex_uk: "Води, будь ласка.", en_ex: "Water, please.", ru_ex: "Воды, пожалуйста." },
            { t: "Числа", no: "いち", pron: "ichi", uk: "один", en: "one", ru: "один", ex_no: "りんごがいちこあります。", ex_uk: "Є одне яблуко.", en_ex: "There is one apple.", ru_ex: "Есть одно яблоко." },
            { t: "Числа", no: "に", pron: "ni", uk: "два", en: "two", ru: "два", ex_no: "ねこがにひきいます。", ex_uk: "Є два коти.", en_ex: "There are two cats.", ru_ex: "Есть два кота." },
            { t: "Числа", no: "さん", pron: "san", uk: "три", en: "three", ru: "три", ex_no: "ほんをさんさつかいました。", ex_uk: "Я купив три книги.", en_ex: "I bought three books.", ru_ex: "Я купил три книги." },
            { t: "Числа", no: "よん", pron: "yon", uk: "чотири", en: "four", ru: "четыре", ex_no: "いすがよんきゃくあります。", ex_uk: "Є чотири стільці.", en_ex: "There are four chairs.", ru_ex: "Есть четыре стула." },
            { t: "Числа", no: "ご", pron: "go", uk: "п'ять", en: "five", ru: "пять", ex_no: "きょうだいがごにんいます。", ex_uk: "У мене п'ятеро братів і сестер.", en_ex: "I have five siblings.", ru_ex: "У меня пятеро братьев и сестёр." },
            { t: "Числа", no: "ろく", pron: "roku", uk: "шість", en: "six", ru: "шесть", ex_no: "ろくじにおきます。", ex_uk: "Я прокидаюсь о шостій.", en_ex: "I wake up at six.", ru_ex: "Я просыпаюсь в шесть." },
            { t: "Числа", no: "なな", pron: "nana", uk: "сім", en: "seven", ru: "семь", ex_no: "いっしゅうかんはななかです。", ex_uk: "У тижні сім днів.", en_ex: "There are seven days in a week.", ru_ex: "В неделе семь дней." },
            { t: "Числа", no: "はち", pron: "hachi", uk: "вісім", en: "eight", ru: "восемь", ex_no: "はちじにねます。", ex_uk: "Я лягаю спати о восьмій.", en_ex: "I go to bed at eight.", ru_ex: "Я ложусь спать в восемь." },
            { t: "Числа", no: "きゅう", pron: "kyuu", uk: "дев'ять", en: "nine", ru: "девять", ex_no: "きゅうじにはじまります。", ex_uk: "Це починається о дев'ятій.", en_ex: "It starts at nine.", ru_ex: "Это начинается в девять." },
            { t: "Числа", no: "じゅう", pron: "juu", uk: "десять", en: "ten", ru: "десять", ex_no: "じゅうぷんまちます。", ex_uk: "Я почекаю десять хвилин.", en_ex: "I'll wait ten minutes.", ru_ex: "Я подожду десять минут." },
            { t: "Числа", no: "ひゃく", pron: "hyaku", uk: "сто", en: "hundred", ru: "сто", ex_no: "ひゃくえんです。", ex_uk: "Це сто єн.", en_ex: "It's a hundred yen.", ru_ex: "Это сто иен." },
            { t: "Родина", no: "かぞく", pron: "kazoku", uk: "родина", en: "family", ru: "семья", ex_no: "わたしのかぞくはよにんです。", ex_uk: "У моїй родині четверо.", en_ex: "There are four people in my family.", ru_ex: "В моей семье четыре человека." },
            { t: "Родина", no: "ちち", pron: "chichi", uk: "мій батько", en: "my father", ru: "мой отец", ex_no: "ちちはいしゃです。", ex_uk: "Мій батько лікар.", en_ex: "My father is a doctor.", ru_ex: "Мой отец врач." },
            { t: "Родина", no: "はは", pron: "haha", uk: "моя мама", en: "my mother", ru: "моя мама", ex_no: "はははせんせいです。", ex_uk: "Моя мама вчителька.", en_ex: "My mother is a teacher.", ru_ex: "Моя мама учительница." },
            { t: "Родина", no: "あに", pron: "ani", uk: "мій старший брат", en: "my older brother", ru: "мой старший брат", ex_no: "あにはがくせいです。", ex_uk: "Мій старший брат студент.", en_ex: "My older brother is a student.", ru_ex: "Мой старший брат студент." },
            { t: "Родина", no: "あね", pron: "ane", uk: "моя старша сестра", en: "my older sister", ru: "моя старшая сестра", ex_no: "あねはとうきょうにすんでいます。", ex_uk: "Моя старша сестра живе в Токіо.", en_ex: "My older sister lives in Tokyo.", ru_ex: "Моя старшая сестра живёт в Токио." },
            { t: "Родина", no: "むすこ", pron: "musuko", uk: "син", en: "son", ru: "сын", ex_no: "むすこはろくさいです。", ex_uk: "Синові шість років.", en_ex: "My son is six years old.", ru_ex: "Сыну шесть лет." },
            { t: "Родина", no: "むすめ", pron: "musume", uk: "дочка", en: "daughter", ru: "дочь", ex_no: "むすめはがっこうにいきます。", ex_uk: "Дочка йде до школи.", en_ex: "My daughter goes to school.", ru_ex: "Дочь идёт в школу." },
            { t: "Кольори", no: "あか", pron: "aka", uk: "червоний", en: "red", ru: "красный", ex_no: "あかいくるまがすきです。", ex_uk: "Мені подобається червона машина.", en_ex: "I like the red car.", ru_ex: "Мне нравится красная машина." },
            { t: "Кольори", no: "あお", pron: "ao", uk: "синій", en: "blue", ru: "синий", ex_no: "そらはあおいです。", ex_uk: "Небо синє.", en_ex: "The sky is blue.", ru_ex: "Небо синее." },
            { t: "Кольори", no: "しろ", pron: "shiro", uk: "білий", en: "white", ru: "белый", ex_no: "しろいねこがいます。", ex_uk: "Є білий кіт.", en_ex: "There is a white cat.", ru_ex: "Есть белый кот." },
            { t: "Кольори", no: "くろ", pron: "kuro", uk: "чорний", en: "black", ru: "чёрный", ex_no: "くろいかばんをかいました。", ex_uk: "Я купив чорну сумку.", en_ex: "I bought a black bag.", ru_ex: "Я купил чёрную сумку." },
            { t: "Кольори", no: "きいろ", pron: "kiiro", uk: "жовтий", en: "yellow", ru: "жёлтый", ex_no: "きいろいはながすきです。", ex_uk: "Мені подобаються жовті квіти.", en_ex: "I like yellow flowers.", ru_ex: "Мне нравятся жёлтые цветы." },
            { t: "Дні тижня", no: "げつようび", pron: "getsuyoubi", uk: "понеділок", en: "Monday", ru: "понедельник", ex_no: "げつようびにがっこうへいきます。", ex_uk: "У понеділок я йду до школи.", en_ex: "I go to school on Monday.", ru_ex: "В понедельник я иду в школу." },
            { t: "Дні тижня", no: "かようび", pron: "kayoubi", uk: "вівторок", en: "Tuesday", ru: "вторник", ex_no: "かようびはいそがしいです。", ex_uk: "У вівторок я зайнятий.", en_ex: "I'm busy on Tuesday.", ru_ex: "Во вторник я занят." },
            { t: "Дні тижня", no: "すいようび", pron: "suiyoubi", uk: "середа", en: "Wednesday", ru: "среда", ex_no: "すいようびにあいましょう。", ex_uk: "Зустріньмось у середу.", en_ex: "Let's meet on Wednesday.", ru_ex: "Встретимся в среду." },
            { t: "Дні тижня", no: "もくようび", pron: "mokuyoubi", uk: "четвер", en: "Thursday", ru: "четверг", ex_no: "もくようびはやすみです。", ex_uk: "У четвер вихідний.", en_ex: "Thursday is a day off.", ru_ex: "Четверг — выходной." },
            { t: "Дні тижня", no: "きんようび", pron: "kin'youbi", uk: "п'ятниця", en: "Friday", ru: "пятница", ex_no: "きんようびのよるがすきです。", ex_uk: "Мені подобається п'ятничний вечір.", en_ex: "I like Friday evenings.", ru_ex: "Мне нравится пятничный вечер." },
            { t: "Дні тижня", no: "どようび", pron: "doyoubi", uk: "субота", en: "Saturday", ru: "суббота", ex_no: "どようびにかいものします。", ex_uk: "У суботу я роблю покупки.", en_ex: "I go shopping on Saturday.", ru_ex: "В субботу я хожу за покупками." },
            { t: "Дні тижня", no: "にちようび", pron: "nichiyoubi", uk: "неділя", en: "Sunday", ru: "воскресенье", ex_no: "にちようびはやすみます。", ex_uk: "У неділю я відпочиваю.", en_ex: "I rest on Sunday.", ru_ex: "В воскресенье я отдыхаю." },
            { t: "Дієслова руху та дії", no: "いきます", pron: "ikimasu", uk: "йти / їхати", en: "to go", ru: "идти / ехать", ex_no: "がっこうへいきます。", ex_uk: "Я йду до школи.", en_ex: "I go to school.", ru_ex: "Я иду в школу." },
            { t: "Дієслова руху та дії", no: "きます", pron: "kimasu", uk: "приходити", en: "to come", ru: "приходить", ex_no: "ともだちがいえにきます。", ex_uk: "Друг приходить до мене додому.", en_ex: "A friend comes to my house.", ru_ex: "Друг приходит ко мне домой." },
            { t: "Дієслова руху та дії", no: "たべます", pron: "tabemasu", uk: "їсти", en: "to eat", ru: "есть", ex_no: "あさごはんをたべます。", ex_uk: "Я їм сніданок.", en_ex: "I eat breakfast.", ru_ex: "Я ем завтрак." },
            { t: "Дієслова руху та дії", no: "のみます", pron: "nomimasu", uk: "пити", en: "to drink", ru: "пить", ex_no: "みずをのみます。", ex_uk: "Я п'ю воду.", en_ex: "I drink water.", ru_ex: "Я пью воду." },
            { t: "Дієслова руху та дії", no: "みます", pron: "mimasu", uk: "дивитись", en: "to watch / to see", ru: "смотреть", ex_no: "テレビをみます。", ex_uk: "Я дивлюся телевізор.", en_ex: "I watch TV.", ru_ex: "Я смотрю телевизор." },
            { t: "Дієслова руху та дії", no: "ききます", pron: "kikimasu", uk: "слухати", en: "to listen", ru: "слушать", ex_no: "おんがくをききます。", ex_uk: "Я слухаю музику.", en_ex: "I listen to music.", ru_ex: "Я слушаю музыку." },
            { t: "Базова їжа", no: "ごはん", pron: "gohan", uk: "рис / їжа", en: "rice / meal", ru: "рис / еда", ex_no: "ごはんをたべましょう。", ex_uk: "Ходімо поїсти.", en_ex: "Let's eat.", ru_ex: "Пойдём поедим." },
            { t: "Базова їжа", no: "みず", pron: "mizu", uk: "вода", en: "water", ru: "вода", ex_no: "みずをください。", ex_uk: "Дайте, будь ласка, води.", en_ex: "Water, please.", ru_ex: "Воды, пожалуйста." },
            { t: "Базова їжа", no: "おちゃ", pron: "ocha", uk: "чай", en: "tea", ru: "чай", ex_no: "あついおちゃがすきです。", ex_uk: "Мені подобається гарячий чай.", en_ex: "I like hot tea.", ru_ex: "Мне нравится горячий чай." },
            { t: "Базова їжа", no: "さかな", pron: "sakana", uk: "риба", en: "fish", ru: "рыба", ex_no: "さかなをたべます。", ex_uk: "Я їм рибу.", en_ex: "I eat fish.", ru_ex: "Я ем рыбу." },
            { t: "Базова їжа", no: "にく", pron: "niku", uk: "м'ясо", en: "meat", ru: "мясо", ex_no: "にくがすきですか。", ex_uk: "Ти любиш м'ясо?", en_ex: "Do you like meat?", ru_ex: "Ты любишь мясо?" },
            { t: "Прикметники", no: "おおきい", pron: "ookii", uk: "великий", en: "big", ru: "большой", ex_no: "おおきいいえです。", ex_uk: "Це великий дім.", en_ex: "It's a big house.", ru_ex: "Это большой дом." },
            { t: "Прикметники", no: "ちいさい", pron: "chiisai", uk: "малий", en: "small", ru: "маленький", ex_no: "ちいさいねこです。", ex_uk: "Це маленький кіт.", en_ex: "It's a small cat.", ru_ex: "Это маленький кот." },
            { t: "Прикметники", no: "たかい", pron: "takai", uk: "високий / дорогий", en: "tall / expensive", ru: "высокий / дорогой", ex_no: "このみせはたかいです。", ex_uk: "Цей магазин дорогий.", en_ex: "This shop is expensive.", ru_ex: "Этот магазин дорогой." },
            { t: "Прикметники", no: "やすい", pron: "yasui", uk: "дешевий", en: "cheap", ru: "дешёвый", ex_no: "このほんはやすいです。", ex_uk: "Ця книга дешева.", en_ex: "This book is cheap.", ru_ex: "Эта книга дешёвая." },
            { t: "Прикметники", no: "おいしい", pron: "oishii", uk: "смачний", en: "delicious", ru: "вкусный", ex_no: "とてもおいしいです。", ex_uk: "Дуже смачно.", en_ex: "It's very delicious.", ru_ex: "Очень вкусно." },
            { t: "Тіло", no: "あたま", pron: "atama", uk: "голова", en: "head", ru: "голова", ex_no: "あたまがいたいです。", ex_uk: "У мене болить голова.", en_ex: "My head hurts.", ru_ex: "У меня болит голова." },
            { t: "Тіло", no: "て", pron: "te", uk: "рука", en: "hand", ru: "рука", ex_no: "てをあらいます。", ex_uk: "Я мию руки.", en_ex: "I wash my hands.", ru_ex: "Я мою руки." },
            { t: "Тіло", no: "め", pron: "me", uk: "око", en: "eye", ru: "глаз", ex_no: "めがいたいです。", ex_uk: "У мене болить око.", en_ex: "My eye hurts.", ru_ex: "У меня болит глаз." },
            { t: "Тіло", no: "みみ", pron: "mimi", uk: "вухо", en: "ear", ru: "ухо", ex_no: "みみがおおきいです。", ex_uk: "У нього великі вуха.", en_ex: "He has big ears.", ru_ex: "У него большие уши." },
            { t: "Дім", no: "いえ", pron: "ie", uk: "дім", en: "house", ru: "дом", ex_no: "いえにかえります。", ex_uk: "Я повертаюся додому.", en_ex: "I'm going home.", ru_ex: "Я возвращаюсь домой." },
            { t: "Дім", no: "へや", pron: "heya", uk: "кімната", en: "room", ru: "комната", ex_no: "へやはきれいです。", ex_uk: "Кімната чиста.", en_ex: "The room is clean.", ru_ex: "Комната чистая." },
            { t: "Дім", no: "まど", pron: "mado", uk: "вікно", en: "window", ru: "окно", ex_no: "まどをあけます。", ex_uk: "Я відкриваю вікно.", en_ex: "I open the window.", ru_ex: "Я открываю окно." },
            { t: "Одяг", no: "ふく", pron: "fuku", uk: "одяг", en: "clothes", ru: "одежда", ex_no: "あたらしいふくをかいました。", ex_uk: "Я купив новий одяг.", en_ex: "I bought new clothes.", ru_ex: "Я купил новую одежду." },
            { t: "Одяг", no: "くつ", pron: "kutsu", uk: "взуття", en: "shoes", ru: "обувь", ex_no: "くつをはきます。", ex_uk: "Я взуваю взуття.", en_ex: "I put on my shoes.", ru_ex: "Я надеваю обувь." },
            { t: "Погода", no: "あめ", pron: "ame", uk: "дощ", en: "rain", ru: "дождь", ex_no: "きょうはあめです。", ex_uk: "Сьогодні дощ.", en_ex: "It's raining today.", ru_ex: "Сегодня дождь." },
            { t: "Погода", no: "ゆき", pron: "yuki", uk: "сніг", en: "snow", ru: "снег", ex_no: "ふゆはゆきがふります。", ex_uk: "Взимку йде сніг.", en_ex: "It snows in winter.", ru_ex: "Зимой идёт снег." },
            { t: "Транспорт", no: "でんしゃ", pron: "densha", uk: "потяг / електричка", en: "train", ru: "поезд / электричка", ex_no: "でんしゃでいきます。", ex_uk: "Я їду потягом.", en_ex: "I go by train.", ru_ex: "Я еду на поезде." },
            { t: "Транспорт", no: "くるま", pron: "kuruma", uk: "машина", en: "car", ru: "машина", ex_no: "くるまでかいものにいきます。", ex_uk: "Я їду за покупками на машині.", en_ex: "I go shopping by car.", ru_ex: "Я езжу за покупками на машине." },
        ],
        // -------------------- A2 --------------------
        A2: [
            { t: "Покупки", no: "かいもの", pron: "kaimono", uk: "покупки", en: "shopping", ru: "покупки", ex_no: "しゅうまつにかいものにいきます。", ex_uk: "На вихідних я йду за покупками.", en_ex: "I go shopping on weekends.", ru_ex: "На выходных я хожу за покупками." },
            { t: "Покупки", no: "いくらですか", pron: "ikura desu ka", uk: "скільки коштує?", en: "how much is it?", ru: "сколько стоит?", ex_no: "このぼうし、いくらですか。", ex_uk: "Скільки коштує цей капелюх?", en_ex: "How much is this hat?", ru_ex: "Сколько стоит эта шляпа?" },
            { t: "Покупки", no: "みせ", pron: "mise", uk: "магазин", en: "shop", ru: "магазин", ex_no: "あたらしいみせができました。", ex_uk: "Відкрився новий магазин.", en_ex: "A new shop opened.", ru_ex: "Открылся новый магазин." },
            { t: "Робота", no: "しごと", pron: "shigoto", uk: "робота", en: "work / job", ru: "работа", ex_no: "しごとがいそがしいです。", ex_uk: "Робота напружена.", en_ex: "Work is busy.", ru_ex: "Работа напряжённая." },
            { t: "Робота", no: "かいしゃ", pron: "kaisha", uk: "компанія", en: "company", ru: "компания", ex_no: "かいしゃではたらいています。", ex_uk: "Я працюю в компанії.", en_ex: "I work at a company.", ru_ex: "Я работаю в компании." },
            { t: "Робота", no: "かいぎ", pron: "kaigi", uk: "нарада", en: "meeting", ru: "совещание", ex_no: "あしたかいぎがあります。", ex_uk: "Завтра нарада.", en_ex: "There's a meeting tomorrow.", ru_ex: "Завтра совещание." },
            { t: "Хобі", no: "しゅみ", pron: "shumi", uk: "хобі", en: "hobby", ru: "хобби", ex_no: "しゅみはどくしょです。", ex_uk: "Моє хобі — читання.", en_ex: "My hobby is reading.", ru_ex: "Моё хобби — чтение." },
            { t: "Хобі", no: "おんがく", pron: "ongaku", uk: "музика", en: "music", ru: "музыка", ex_no: "おんがくをきくのがすきです。", ex_uk: "Мені подобається слухати музику.", en_ex: "I like listening to music.", ru_ex: "Мне нравится слушать музыку." },
            { t: "Хобі", no: "スポーツ", pron: "supootsu", uk: "спорт", en: "sport", ru: "спорт", ex_no: "スポーツがとくいです。", ex_uk: "Я гарний у спорті.", en_ex: "I'm good at sports.", ru_ex: "Я хорош в спорте." },
            { t: "Емоції", no: "うれしい", pron: "ureshii", uk: "радісний", en: "happy", ru: "радостный", ex_no: "きょうはとてもうれしいです。", ex_uk: "Сьогодні я дуже радісний.", en_ex: "I'm very happy today.", ru_ex: "Сегодня я очень рад." },
            { t: "Емоції", no: "かなしい", pron: "kanashii", uk: "сумний", en: "sad", ru: "грустный", ex_no: "かなしいえいがをみました。", ex_uk: "Я подивився сумний фільм.", en_ex: "I watched a sad movie.", ru_ex: "Я посмотрел грустный фильм." },
            { t: "Емоції", no: "しんぱい", pron: "shinpai", uk: "занепокоєння", en: "worry", ru: "беспокойство", ex_no: "しんぱいしないでください。", ex_uk: "Не хвилюйтеся, будь ласка.", en_ex: "Please don't worry.", ru_ex: "Пожалуйста, не беспокойтесь." },
            { t: "Подорожі", no: "りょこう", pron: "ryokou", uk: "подорож", en: "trip", ru: "путешествие", ex_no: "らいねんりょこうします。", ex_uk: "Наступного року я подорожуватиму.", en_ex: "I will travel next year.", ru_ex: "В следующем году я буду путешествовать." },
            { t: "Подорожі", no: "くうこう", pron: "kuukou", uk: "аеропорт", en: "airport", ru: "аэропорт", ex_no: "くうこうまでタクシーでいきます。", ex_uk: "Я їду до аеропорту на таксі.", en_ex: "I go to the airport by taxi.", ru_ex: "Я еду в аэропорт на такси." },
            { t: "Ресторан", no: "レストラン", pron: "resutoran", uk: "ресторан", en: "restaurant", ru: "ресторан", ex_no: "レストランでたべましょう。", ex_uk: "Ходімо поїмо в ресторані.", en_ex: "Let's eat at a restaurant.", ru_ex: "Пойдём поедим в ресторане." },
            { t: "Ресторан", no: "メニュー", pron: "menyuu", uk: "меню", en: "menu", ru: "меню", ex_no: "メニューをみせてください。", ex_uk: "Покажіть, будь ласка, меню.", en_ex: "Please show me the menu.", ru_ex: "Покажите, пожалуйста, меню." },
            { t: "Освіта", no: "がっこう", pron: "gakkou", uk: "школа", en: "school", ru: "школа", ex_no: "がっこうでにほんごをべんきょうします。", ex_uk: "Я вивчаю японську в школі.", en_ex: "I study Japanese at school.", ru_ex: "Я изучаю японский в школе." },
            { t: "Освіта", no: "べんきょうします", pron: "benkyou shimasu", uk: "вчитися", en: "to study", ru: "учиться", ex_no: "まいにちべんきょうします。", ex_uk: "Я вчуся щодня.", en_ex: "I study every day.", ru_ex: "Я учусь каждый день." },
            { t: "Здоров'я", no: "びょういん", pron: "byouin", uk: "лікарня", en: "hospital", ru: "больница", ex_no: "びょういんにいきます。", ex_uk: "Я йду до лікарні.", en_ex: "I'm going to the hospital.", ru_ex: "Я иду в больницу." },
            { t: "Здоров'я", no: "くすり", pron: "kusuri", uk: "ліки", en: "medicine", ru: "лекарство", ex_no: "くすりをのみます。", ex_uk: "Я приймаю ліки.", en_ex: "I take medicine.", ru_ex: "Я принимаю лекарство." },
            { t: "Мінулий час", no: "たべました", pron: "tabemashita", uk: "з'їв(-ла)", en: "ate", ru: "съел(-а)", ex_no: "あさごはんをたべました。", ex_uk: "Я з'їв сніданок.", en_ex: "I ate breakfast.", ru_ex: "Я съел завтрак." },
            { t: "Мінулий час", no: "いきました", pron: "ikimashita", uk: "пішов(-ла)", en: "went", ru: "пошёл(-шла)", ex_no: "がっこうにいきました。", ex_uk: "Я пішов до школи.", en_ex: "I went to school.", ru_ex: "Я пошёл в школу." },
        ],
        // -------------------- B1 --------------------
        B1: [
            { t: "Подорожі", no: "旅行", pron: "ryokou", uk: "подорож (кандзі: りょこう)", en: "trip (kanji: ryokou)", ru: "путешествие (кандзи: рёкō)", ex_no: "来年、日本へ旅行します。", ex_uk: "Наступного року я подорожуватиму до Японії.", en_ex: "Next year, I will travel to Japan.", ru_ex: "В следующем году я поеду путешествовать в Японию." },
            { t: "Подорожі", no: "予約", pron: "yoyaku", uk: "бронювання (よやく)", en: "reservation (yoyaku)", ru: "бронирование (ёяку)", ex_no: "ホテルを予約しました。", ex_uk: "Я забронював готель.", en_ex: "I made a hotel reservation.", ru_ex: "Я забронировал отель." },
            { t: "Здоров'я", no: "健康", pron: "kenkou", uk: "здоров'я (けんこう)", en: "health (kenkou)", ru: "здоровье (кенкō)", ex_no: "健康のために運動します。", ex_uk: "Я тренуюся заради здоров'я.", en_ex: "I exercise for my health.", ru_ex: "Я тренируюсь ради здоровья." },
            { t: "Стосунки", no: "友達", pron: "tomodachi", uk: "друг (ともだち)", en: "friend (tomodachi)", ru: "друг (томодачи)", ex_no: "彼は大切な友達です。", ex_uk: "Він важливий друг.", en_ex: "He is an important friend.", ru_ex: "Он важный друг." },
            { t: "Стосунки", no: "結婚", pron: "kekkon", uk: "одруження (けっこん)", en: "marriage (kekkon)", ru: "брак (кеккон)", ex_no: "来年結婚します。", ex_uk: "Наступного року я одружуюся.", en_ex: "I'm getting married next year.", ru_ex: "В следующем году я женюсь." },
            { t: "Медіа", no: "新聞", pron: "shinbun", uk: "газета (しんぶん)", en: "newspaper (shinbun)", ru: "газета (симбун)", ex_no: "毎朝新聞を読みます。", ex_uk: "Я щоранку читаю газету.", en_ex: "I read the newspaper every morning.", ru_ex: "Я каждое утро читаю газету." },
            { t: "Медіа", no: "番組", pron: "bangumi", uk: "телепередача (ばんぐみ)", en: "TV program (bangumi)", ru: "телепередача (бангуми)", ex_no: "この番組が好きです。", ex_uk: "Мені подобається ця передача.", en_ex: "I like this program.", ru_ex: "Мне нравится эта передача." },
            { t: "Довкілля", no: "自然", pron: "shizen", uk: "природа (しぜん)", en: "nature (shizen)", ru: "природа (сидзен)", ex_no: "自然が好きです。", ex_uk: "Мені подобається природа.", en_ex: "I like nature.", ru_ex: "Мне нравится природа." },
            { t: "Довкілля", no: "環境", pron: "kankyou", uk: "довкілля (かんきょう)", en: "environment (kankyou)", ru: "окружающая среда (канкё:)", ex_no: "環境を守りましょう。", ex_uk: "Давайте берегти довкілля.", en_ex: "Let's protect the environment.", ru_ex: "Давайте беречь окружающую среду." },
            { t: "Кар'єра", no: "経験", pron: "keiken", uk: "досвід (けいけん)", en: "experience (keiken)", ru: "опыт (кейкен)", ex_no: "仕事の経験があります。", ex_uk: "У мене є досвід роботи.", en_ex: "I have work experience.", ru_ex: "У меня есть опыт работы." },
            { t: "Кар'єра", no: "面接", pron: "mensetsu", uk: "співбесіда (めんせつ)", en: "interview (mensetsu)", ru: "собеседование (мэнсэцу)", ex_no: "明日面接があります。", ex_uk: "Завтра в мене співбесіда.", en_ex: "I have an interview tomorrow.", ru_ex: "Завтра у меня собеседование." },
            { t: "Дієслова", no: "頑張ります", pron: "ganbarimasu", uk: "старатися (がんばります)", en: "to do one's best (ganbarimasu)", ru: "стараться (ганбаримасу)", ex_no: "試験のために頑張ります。", ex_uk: "Я старатимусь заради іспиту.", en_ex: "I'll do my best for the exam.", ru_ex: "Я буду стараться ради экзамена." },
            { t: "Дієслова", no: "考えます", pron: "kangaemasu", uk: "думати (かんがえます)", en: "to think (kangaemasu)", ru: "думать (кангаэмасу)", ex_no: "将来について考えます。", ex_uk: "Я думаю про майбутнє.", en_ex: "I think about the future.", ru_ex: "Я думаю о будущем." },
        ],
        // -------------------- B2 --------------------
        B2: [
            { t: "Політика", no: "政府", pron: "seifu", uk: "уряд (せいふ)", en: "government (seifu)", ru: "правительство (сэйфу)", ex_no: "政府は新しい政策を発表しました。", ex_uk: "Уряд оголосив нову політику.", en_ex: "The government announced a new policy.", ru_ex: "Правительство объявило новую политику." },
            { t: "Політика", no: "選挙", pron: "senkyo", uk: "вибори (せんきょ)", en: "election (senkyo)", ru: "выборы (сэнкё)", ex_no: "来月選挙があります。", ex_uk: "Наступного місяця будуть вибори.", en_ex: "There is an election next month.", ru_ex: "В следующем месяце будут выборы." },
            { t: "Економіка", no: "経済", pron: "keizai", uk: "економіка (けいざい)", en: "economy (keizai)", ru: "экономика (кэйдзай)", ex_no: "経済が成長しています。", ex_uk: "Економіка зростає.", en_ex: "The economy is growing.", ru_ex: "Экономика растёт." },
            { t: "Економіка", no: "貿易", pron: "boueki", uk: "торгівля (ぼうえき)", en: "trade (boueki)", ru: "торговля (боэки)", ex_no: "貿易が盛んな国です。", ex_uk: "Це країна з розвиненою торгівлею.", en_ex: "It's a country with thriving trade.", ru_ex: "Это страна с развитой торговлей." },
            { t: "Наука", no: "研究", pron: "kenkyuu", uk: "дослідження (けんきゅう)", en: "research (kenkyuu)", ru: "исследование (кэнкю:)", ex_no: "大学で研究をしています。", ex_uk: "Я займаюся дослідженнями в університеті.", en_ex: "I do research at university.", ru_ex: "Я занимаюсь исследованиями в университете." },
            { t: "Наука", no: "発見", pron: "hakken", uk: "відкриття (はっけん)", en: "discovery (hakken)", ru: "открытие (хаккэн)", ex_no: "新しい発見がありました。", ex_uk: "Було нове відкриття.", en_ex: "There was a new discovery.", ru_ex: "Было новое открытие." },
            { t: "Культура", no: "伝統", pron: "dentou", uk: "традиція (でんとう)", en: "tradition (dentou)", ru: "традиция (дэнто:)", ex_no: "これは日本の伝統です。", ex_uk: "Це японська традиція.", en_ex: "This is a Japanese tradition.", ru_ex: "Это японская традиция." },
            { t: "Бізнес", no: "契約", pron: "keiyaku", uk: "контракт (けいやく)", en: "contract (keiyaku)", ru: "контракт (кэйяку)", ex_no: "契約にサインしました。", ex_uk: "Я підписав контракт.", en_ex: "I signed the contract.", ru_ex: "Я подписал контракт." },
            { t: "Медицина", no: "治療", pron: "chiryou", uk: "лікування (ちりょう)", en: "treatment (chiryou)", ru: "лечение (тирё:)", ex_no: "治療を受けています。", ex_uk: "Я проходжу лікування.", en_ex: "I'm receiving treatment.", ru_ex: "Я прохожу лечение." },
        ],
        // -------------------- C1 --------------------
        C1: [
            { t: "Дискурс", no: "したがって", pron: "shitagatte", uk: "отже", en: "therefore", ru: "следовательно", ex_no: "彼は勉強しなかった。したがって、試験に失敗した。", ex_uk: "Він не вчився. Отже, провалив іспит.", en_ex: "He didn't study. Therefore, he failed the exam.", ru_ex: "Он не учился. Следовательно, он провалил экзамен." },
            { t: "Дискурс", no: "にもかかわらず", pron: "nimo kakawarazu", uk: "незважаючи на", en: "despite / nevertheless", ru: "несмотря на", ex_no: "雨にもかかわらず、出かけました。", ex_uk: "Незважаючи на дощ, я вийшов.", en_ex: "Despite the rain, I went out.", ru_ex: "Несмотря на дождь, я вышел." },
            { t: "Академічна", no: "分析", pron: "bunseki", uk: "аналіз (ぶんせき)", en: "analysis (bunseki)", ru: "анализ (бунсэки)", ex_no: "データを分析します。", ex_uk: "Я аналізую дані.", en_ex: "I analyze the data.", ru_ex: "Я анализирую данные." },
            { t: "Академічна", no: "仮説", pron: "kasetsu", uk: "гіпотеза (かせつ)", en: "hypothesis (kasetsu)", ru: "гипотеза (касэцу)", ex_no: "新しい仮説を立てました。", ex_uk: "Я висунув нову гіпотезу.", en_ex: "I proposed a new hypothesis.", ru_ex: "Я выдвинул новую гипотезу." },
            { t: "Філософія", no: "存在", pron: "sonzai", uk: "існування (そんざい)", en: "existence (sonzai)", ru: "существование (сондзай)", ex_no: "存在の意味を考えます。", ex_uk: "Я думаю про сенс існування.", en_ex: "I think about the meaning of existence.", ru_ex: "Я думаю о смысле существования." },
            { t: "Психологія", no: "無意識", pron: "muishiki", uk: "підсвідомість (むいしき)", en: "the unconscious (muishiki)", ru: "подсознание (муисики)", ex_no: "無意識の行動です。", ex_uk: "Це підсвідома дія.", en_ex: "It's an unconscious action.", ru_ex: "Это подсознательное действие." },
            { t: "Соціологія", no: "社会", pron: "shakai", uk: "суспільство (しゃかい)", en: "society (shakai)", ru: "общество (сякай)", ex_no: "現代社会について話します。", ex_uk: "Я говорю про сучасне суспільство.", en_ex: "I talk about modern society.", ru_ex: "Я говорю о современном обществе." },
        ],
        // -------------------- C2 --------------------
        C2: [
            { t: "Ідіоми", no: "猫の手も借りたい", pron: "neko no te mo karitai", uk: "дуже зайнятий (буквально: хотів би позичити навіть котячу лапу)", en: "extremely busy (lit. would even borrow a cat's paw)", ru: "очень занят (букв. занял бы даже кошачью лапу)", ex_no: "今日は猫の手も借りたいほど忙しいです。", ex_uk: "Сьогодні я неймовірно зайнятий.", en_ex: "Today I'm incredibly busy.", ru_ex: "Сегодня я невероятно занят." },
            { t: "Ідіоми", no: "石の上にも三年", pron: "ishi no ue nimo san'nen", uk: "терпіння і труд усе перетруть (буквально: три роки на камені)", en: "patience pays off (lit. three years on a stone)", ru: "терпение и труд всё перетрут (букв. три года на камне)", ex_no: "石の上にも三年というから、続けましょう。", ex_uk: "Кажуть, терпіння і труд усе перетруть, тож продовжимо.", en_ex: "They say patience pays off, so let's continue.", ru_ex: "Говорят, терпение и труд всё перетрут, так что продолжим." },
            { t: "Стилістика", no: "候文", pron: "souroubun", uk: "офіційно-архаїчний стиль (そうろうぶん)", en: "archaic formal writing style (souroubun)", ru: "архаичный официальный стиль (соробун)", ex_no: "候文は古い公式文書に使われました。", ex_uk: "Архаїчний стиль використовувався в старих офіційних документах.", en_ex: "The archaic style was used in old official documents.", ru_ex: "Архаичный стиль использовался в старых официальных документах." },
            { t: "Рідкісна лексика", no: "侘寂", pron: "wabi-sabi", uk: "естетика недосконалої краси (わびさび)", en: "aesthetic of imperfect beauty (wabi-sabi)", ru: "эстетика несовершенной красоты (ваби-саби)", ex_no: "侘寂は日本の美意識です。", ex_uk: "Вабі-сабі — це японська естетична концепція.", en_ex: "Wabi-sabi is a Japanese aesthetic concept.", ru_ex: "Ваби-саби — это японская эстетическая концепция." },
            { t: "Риторика", no: "婉曲表現", pron: "enkyoku hyougen", uk: "евфемізм (えんきょくひょうげん)", en: "euphemism (enkyoku hyougen)", ru: "эвфемизм (энкёку хёгэн)", ex_no: "日本語には婉曲表現が多いです。", ex_uk: "У японській мові багато евфемізмів.", en_ex: "Japanese has many euphemisms.", ru_ex: "В японском языке много эвфемизмов." },
            { t: "Абстрактне", no: "無常", pron: "mujou", uk: "тлінність усього сущого (むじょう)", en: "impermanence (mujou)", ru: "непостоянство всего сущего (мудзё)", ex_no: "無常は仏教の考え方です。", ex_uk: "Тлінність — буддистська концепція.", en_ex: "Impermanence is a Buddhist concept.", ru_ex: "Непостоянство — буддийская концепция." },
        ],
    };

    // =====================================================================
    //  GRAMMAR — ГРАМАТИЧНІ ПРАВИЛА (2 на кожен рівень)
    // =====================================================================
    const GRAMMAR = [
        // A1
        {
            id: "ja_gr1", level: "A1",
            title: "Частка は (wa) — тема речення",
            exp: "Частка は (читається як «ва», не «ха») позначає ТЕМУ речення — про що йдеться. Вона ставиться одразу після іменника-теми.",
            table: { head: ["Приклад", "Переклад"], rows: [["わたしは がくせいです。", "Я (що стосується мене) — студент."], ["これは ほんです。", "Це — книга."]] },
            ex: { q: "わたし___ がくせいです。", opts: ["は", "を", "が"], a: 0 },
            title_en: "The particle は (wa) — sentence topic",
            title_ru: "Частица は (wa) — тема предложения",
            exp_en: "The particle は (pronounced \"wa\", not \"ha\") marks the TOPIC of the sentence — what the sentence is about. It goes right after the topic noun.",
            exp_ru: "Частица は (читается как «ва», не «ха») обозначает ТЕМУ предложения — о чём идёт речь. Ставится сразу после существительного-темы.",
            head_en: ["Example", "Translation"],
            head_ru: ["Пример", "Перевод"],
            q_en: "わたし___ がくせいです。",
            q_ru: "わたし___ がくせいです。",
        },
        {
            id: "ja_gr1b", level: "A1",
            title: "Ввічлива форма です / ます",
            exp: "です — ввічливе закінчення для іменників і прикметників («є»/«бути»). ます — ввічливе закінчення для дієслів у теперішньому/майбутньому часі.",
            table: { head: ["Форма", "Приклад", "Переклад"], rows: [["です", "学生です。", "Це студент."], ["ます", "たべます。", "Я їм / їстиму."]] },
            ex: { q: "まいにち にほんごを べんきょう___。", opts: ["します", "です", "した"], a: 0 },
            title_en: "The polite forms です / ます",
            title_ru: "Вежливые формы です / ます",
            exp_en: "です is the polite ending for nouns and adjectives (\"is/am/are\"). ます is the polite ending for verbs in present/future tense.",
            exp_ru: "です — вежливое окончание для существительных и прилагательных («есть»/«быть»). ます — вежливое окончание для глаголов в настоящем/будущем времени.",
            head_en: ["Form", "Example", "Translation"],
            head_ru: ["Форма", "Пример", "Перевод"],
            q_en: "まいにち にほんごを べんきょう___。",
            q_ru: "まいにち にほんごを べんきょう___。",
        },
        // A2
        {
            id: "ja_gr2", level: "A2",
            title: "Частка を (o) — прямий додаток",
            exp: "Частка を (читається як «о») позначає прямий додаток дії — те, на що спрямована дія дієслова.",
            table: { head: ["Приклад", "Переклад"], rows: [["ごはん___たべます。", "Я їм їжу."], ["ほん___よみます。", "Я читаю книгу."]] },
            ex: { q: "みず___のみます。", opts: ["を", "は", "に"], a: 0 },
            title_en: "The particle を (o) — direct object",
            title_ru: "Частица を (o) — прямое дополнение",
            exp_en: "The particle を (pronounced \"o\") marks the direct object — what the verb's action is directed at.",
            exp_ru: "Частица を (читается как «о») обозначает прямое дополнение — то, на что направлено действие глагола.",
            head_en: ["Example", "Translation"],
            head_ru: ["Пример", "Перевод"],
            q_en: "みず___のみます。",
            q_ru: "みず___のみます。",
        },
        {
            id: "ja_gr2b", level: "A2",
            title: "Те-форма (て形) для з'єднання дій",
            exp: "Те-форма дієслова використовується, щоб з'єднати кілька дій в одному реченні («роблю це і те») або утворити прохання (~てください).",
            table: { head: ["Словникова форма", "Те-форма"], rows: [["たべる (їсти)", "たべて"], ["いく (йти)", "いって"], ["のむ (пити)", "のんで"]] },
            ex: { q: "まど を あけ___ください。", opts: ["て", "ます", "た"], a: 0 },
            title_en: "The te-form (て形) for connecting actions",
            title_ru: "Тэ-форма (て形) для соединения действий",
            exp_en: "The te-form of a verb is used to connect several actions in one sentence (\"I do this and that\") or to make a request (~てください).",
            exp_ru: "Тэ-форма глагола используется, чтобы соединить несколько действий в одном предложении («делаю это и то») или образовать просьбу (~てください).",
            head_en: ["Dictionary form", "Te-form"],
            head_ru: ["Словарная форма", "Тэ-форма"],
            q_en: "まど を あけ___ください。",
            q_ru: "まど を あけ___ください。",
        },
        // B1
        {
            id: "ja_gr3", level: "B1",
            title: "Минулий час た形",
            exp: "Форма た (та-форма) утворює минулий час дієслова у звичайному (не ввічливому) стилі. Утворюється так само, як і те-форма, але з た/だ замість て/で.",
            table: { head: ["Те-форма", "Та-форма (минулий час)"], rows: [["たべて", "たべた (з'їв)"], ["いって", "いった (пішов)"]] },
            ex: { q: "きのう えいがを み___。", opts: ["た", "ます", "て"], a: 0 },
            title_en: "The past tense た-form",
            title_ru: "Прошедшее время (форма た)",
            exp_en: "The た-form (ta-form) creates the past tense of a verb in the plain (non-polite) style. It's formed the same way as the te-form, but with た/だ instead of て/で.",
            exp_ru: "Форма た (та-форма) образует прошедшее время глагола в обычном (не вежливом) стиле. Образуется так же, как тэ-форма, но с た/だ вместо て/で.",
            head_en: ["Te-form", "Ta-form (past tense)"],
            head_ru: ["Тэ-форма", "Та-форма (прошедшее время)"],
            q_en: "きのう えいがを み___。",
            q_ru: "きのう えいがを み___。",
        },
        {
            id: "ja_gr3b", level: "B1",
            title: "~たい — «хочу зробити»",
            exp: "Щоб сказати «хочу зробити щось», беруть основу дієслова (форму на ます без ます) і додають たい.",
            table: { head: ["Форма ます", "~たい"], rows: [["たべます", "たべたい (хочу їсти)"], ["いきます", "いきたい (хочу піти)"]] },
            ex: { q: "にほんへ いき___です。", opts: ["たい", "ます", "たた"], a: 0 },
            title_en: "~たい — \"want to do\"",
            title_ru: "~たい — «хочу сделать»",
            exp_en: "To say \"I want to do something\", take the stem of the verb (the ます-form without ます) and add たい.",
            exp_ru: "Чтобы сказать «хочу сделать что-то», берут основу глагола (форму на ます без ます) и добавляют たい.",
            head_en: ["ます-form", "~たい"],
            head_ru: ["Форма ます", "~たい"],
            q_en: "にほんへ いき___です。",
            q_ru: "にほんへ いき___です。",
        },
        // B2
        {
            id: "ja_gr4", level: "B2",
            title: "Форма можливості (可能形)",
            exp: "Форма можливості виражає здатність щось робити («можу зробити»). Для дієслів на -る групи 2 замінюємо る на られる; для групи 1 змінюємо останній склад на -е + る.",
            table: { head: ["Словникова форма", "Форма можливості"], rows: [["たべる (їсти)", "たべられる (можу їсти)"], ["よむ (читати)", "よめる (можу читати)"]] },
            ex: { q: "にほんごが すこし はなし___。", opts: ["ます", "たい", "て"], a: 0 },
            title_en: "The potential form (可能形)",
            title_ru: "Форма возможности (可能形)",
            exp_en: "The potential form expresses ability to do something (\"can do\"). For ru-verbs (group 2), replace る with られる; for u-verbs (group 1), change the final syllable to the e-row + る.",
            exp_ru: "Форма возможности выражает способность что-то делать («могу сделать»). Для глаголов на -ru группы 2 меняем る на られる; для группы 1 меняем последний слог на -e + る.",
            head_en: ["Dictionary form", "Potential form"],
            head_ru: ["Словарная форма", "Форма возможности"],
            q_en: "にほんごが すこし はなし___。",
            q_ru: "にほんごが すこし はなし___。",
        },
        {
            id: "ja_gr4b", level: "B2",
            title: "Умовна форма ~ば",
            exp: "Умовна форма ~ば виражає «якщо». Для дієслів групи 1 останній склад -у змінюється на -е + ば; для прикметників на -い прибираємо い і додаємо ければ.",
            table: { head: ["Форма", "Умовна форма"], rows: [["よむ", "よめば (якщо читати)"], ["たかい", "たかければ (якщо дорого)"]] },
            ex: { q: "あめが ふ___、いえにいます。", opts: ["れば", "ます", "たい"], a: 0 },
            title_en: "The conditional form ~ば",
            title_ru: "Условная форма ~ば",
            exp_en: "The conditional form ~ば expresses \"if\". For group 1 verbs, the final -u syllable changes to -e + ば; for い-adjectives, drop い and add ければ.",
            exp_ru: "Условная форма ~ば выражает «если». Для глаголов группы 1 последний слог -у меняется на -е + ば; для прилагательных на -い убираем い и добавляем ければ.",
            head_en: ["Form", "Conditional form"],
            head_ru: ["Форма", "Условная форма"],
            q_en: "あめが ふ___、いえにいます。",
            q_ru: "あめが ふ___、いえにいます。",
        },
        // C1
        {
            id: "ja_gr5", level: "C1",
            title: "Пасивний стан (受身形)",
            exp: "Пасивний стан показує, що дія відбувається НАД підметом. Для дієслів групи 1 останній склад -у змінюється на -а + れる; для групи 2 る замінюється на られる.",
            table: { head: ["Активний стан", "Пасивний стан"], rows: [["ほめる (хвалити)", "ほめられる (бути похваленим)"], ["よむ (читати)", "よまれる (бути прочитаним)"]] },
            ex: { q: "この本は多くの人に読___います。", opts: ["まれて", "みます", "んで"], a: 0 },
            title_en: "The passive voice (受身形)",
            title_ru: "Страдательный залог (受身形)",
            exp_en: "The passive voice shows that the action happens TO the subject. For group 1 verbs, the final -u syllable changes to -a + れる; for group 2, る is replaced with られる.",
            exp_ru: "Страдательный залог показывает, что действие происходит НАД подлежащим. Для глаголов группы 1 последний слог -у меняется на -а + れる; для группы 2 る заменяется на られる.",
            head_en: ["Active voice", "Passive voice"],
            head_ru: ["Действительный залог", "Страдательный залог"],
            q_en: "この本は多くの人に読___います。",
            q_ru: "この本は多くの人に読___います。",
        },
        {
            id: "ja_gr5b", level: "C1",
            title: "Спонукальний стан (使役形)",
            exp: "Спонукальний стан виражає, що хтось змушує або дозволяє іншому зробити дію («змушувати», «дозволяти»). Утворюється заміною る на させる (група 2) або -у на -а + せる (група 1).",
            table: { head: ["Словникова форма", "Спонукальна форма"], rows: [["たべる", "たべさせる (змушувати їсти)"], ["いく", "いかせる (дозволяти піти)"]] },
            ex: { q: "先生は学生に本を読___。", opts: ["ませました", "みます", "んでいる"], a: 0 },
            title_en: "The causative form (使役形)",
            title_ru: "Побудительный залог (使役形)",
            exp_en: "The causative form expresses that someone makes or lets another person do an action (\"to make\", \"to let\"). Formed by replacing る with させる (group 2) or -u with -a + せる (group 1).",
            exp_ru: "Побудительный залог выражает, что кто-то заставляет или позволяет другому сделать действие («заставлять», «позволять»). Образуется заменой る на させる (группа 2) или -у на -а + せる (группа 1).",
            head_en: ["Dictionary form", "Causative form"],
            head_ru: ["Словарная форма", "Побудительная форма"],
            q_en: "先生は学生に本を読___。",
            q_ru: "先生は学生に本を読___。",
        },
        // C2
        {
            id: "ja_gr6", level: "C2",
            title: "Ввічлива мова кейго — форма поваги (尊敬語)",
            exp: "Сонкейго (尊敬語) — форма поваги, яку використовують, говорячи про дії співрозмовника чи третьої особи вищого статусу. Наприклад, замість いく («йти») кажуть いらっしゃる.",
            table: { head: ["Звичайне слово", "Сонкейго (форма поваги)"], rows: [["いく (йти)", "いらっしゃる"], ["いう (казати)", "おっしゃる"], ["みる (дивитись)", "ごらんになる"]] },
            ex: { q: "先生はもう___ましたか。", opts: ["いらっしゃい", "いき", "いって"], a: 0 },
            title_en: "Honorific keigo — respectful form (尊敬語)",
            title_ru: "Вежливая речь кэйго — форма уважения (尊敬語)",
            exp_en: "Sonkeigo (尊敬語) is the respectful form used when talking about the actions of the listener or a higher-status third person. For example, instead of いく (\"to go\"), one says いらっしゃる.",
            exp_ru: "Сонкэйго (尊敬語) — форма уважения, используемая при разговоре о действиях собеседника или третьего лица более высокого статуса. Например, вместо いく («идти») говорят いらっしゃる.",
            head_en: ["Plain word", "Sonkeigo (respectful form)"],
            head_ru: ["Обычное слово", "Сонкэйго (форма уважения)"],
            q_en: "先生はもう___ましたか。",
            q_ru: "先生はもう___ましたか。",
        },
        {
            id: "ja_gr6b", level: "C2",
            title: "Скромна форма кендзьоґо (謙譲語)",
            exp: "Кендзьоґо (謙譲語) — скромна форма, яку використовують, говорячи про власні дії, щоб виявити повагу до співрозмовника. Наприклад, замість いく кажуть まいる.",
            table: { head: ["Звичайне слово", "Кендзьоґо (скромна форма)"], rows: [["いく (йти)", "まいる"], ["する (робити)", "いたす"], ["いう (казати)", "もうす"]] },
            ex: { q: "明日、そちらへ___ます。", opts: ["まいり", "いき", "いって"], a: 0 },
            title_en: "Humble speech kenjougo (謙譲語)",
            title_ru: "Скромная речь кэндзёго (謙譲語)",
            exp_en: "Kenjougo (謙譲語) is the humble form used when talking about one's own actions, to show respect toward the listener. For example, instead of いく, one says まいる.",
            exp_ru: "Кэндзёго (謙譲語) — скромная форма, используемая при разговоре о собственных действиях, чтобы проявить уважение к собеседнику. Например, вместо いく говорят まいる.",
            head_en: ["Plain word", "Kenjougo (humble form)"],
            head_ru: ["Обычное слово", "Кэндзёго (скромная форма)"],
            q_en: "明日、そちらへ___ます。",
            q_ru: "明日、そちらへ___ます。",
        },
    ];

    // =====================================================================
    //  NORSKPROVE_TASKS — для японської не використовується (банк завдань є
    //  лише вбудований для норвезької; для решти мов джерело — AI, див.
    //  helpers.js norskTasksFor()). Лишаємо порожній об'єкт для сумісності
    //  зі схемою window.LANG_DATA.
    // =====================================================================
    const NORSKPROVE_TASKS = {};

    // =====================================================================
    //  LEVEL_TEST — вхідний тест на рівень (питання-переклад слова, по 5 на
    //  кожен рівень A1-C2, від найпростіших до найскладніших)
    // =====================================================================
    const LEVEL_TEST = [
        { lvl: "A1", q: "Як буде «дякую» японською?", opts: ["ありがとうございます", "すみません", "さようなら"], a: 0 },
        { lvl: "A1", q: "Що означає «こんにちは»?", opts: ["добрий день", "до побачення", "дякую"], a: 0 },
        { lvl: "A1", q: "Як буде «один» японською?", opts: ["いち", "に", "さん"], a: 0 },
        { lvl: "A1", q: "Що означає «みず»?", opts: ["вода", "чай", "рис"], a: 0 },
        { lvl: "A1", q: "Як буде «кіт» японською? (підказка: ねこ)", opts: ["ねこ", "いぬ", "とり"], a: 0 },
        { lvl: "A2", q: "Що означає «かいもの»?", opts: ["покупки", "робота", "школа"], a: 0 },
        { lvl: "A2", q: "Як буде «сумний» японською?", opts: ["かなしい", "うれしい", "たかい"], a: 0 },
        { lvl: "A2", q: "Що означає «りょこう»?", opts: ["подорож", "робота", "нарада"], a: 0 },
        { lvl: "A2", q: "Як буде «лікарня» японською?", opts: ["びょういん", "がっこう", "かいしゃ"], a: 0 },
        { lvl: "A2", q: "Що означає «たべました»?", opts: ["з'їв(-ла)", "піду", "їм"], a: 0 },
        { lvl: "B1", q: "Що означає «経験» (けいけん)?", opts: ["досвід", "співбесіда", "нарада"], a: 0 },
        { lvl: "B1", q: "Як буде «природа» японською (кандзі)?", opts: ["自然", "環境", "経済"], a: 0 },
        { lvl: "B1", q: "Що означає «結婚» (けっこん)?", opts: ["одруження", "дружба", "робота"], a: 0 },
        { lvl: "B1", q: "Як буде «здоров'я» кандзі?", opts: ["健康", "病院", "薬"], a: 0 },
        { lvl: "B1", q: "Що означає «頑張ります» (がんばります)?", opts: ["старатися", "думати", "втомлюватись"], a: 0 },
        { lvl: "B2", q: "Що означає «経済» (けいざい)?", opts: ["економіка", "політика", "торгівля"], a: 0 },
        { lvl: "B2", q: "Як буде «уряд» кандзі?", opts: ["政府", "選挙", "貿易"], a: 0 },
        { lvl: "B2", q: "Що означає «研究» (けんきゅう)?", opts: ["дослідження", "відкриття", "аналіз"], a: 0 },
        { lvl: "B2", q: "Як буде «контракт» кандзі?", opts: ["契約", "治療", "伝統"], a: 0 },
        { lvl: "B2", q: "Що означає «伝統» (でんとう)?", opts: ["традиція", "лікування", "суспільство"], a: 0 },
        { lvl: "C1", q: "Що означає «したがって»?", opts: ["отже", "незважаючи на", "тому що"], a: 0 },
        { lvl: "C1", q: "Як буде «аналіз» кандзі?", opts: ["分析", "仮説", "存在"], a: 0 },
        { lvl: "C1", q: "Що означає «にもかかわらず»?", opts: ["незважаючи на", "отже", "можливо"], a: 0 },
        { lvl: "C1", q: "Як буде «підсвідомість» кандзі?", opts: ["無意識", "社会", "存在"], a: 0 },
        { lvl: "C1", q: "Що означає «仮説» (かせつ)?", opts: ["гіпотеза", "аналіз", "суспільство"], a: 0 },
        { lvl: "C2", q: "Що означає ідіома «猫の手も借りたい»?", opts: ["дуже зайнятий", "дуже голодний", "дуже втомлений"], a: 0 },
        { lvl: "C2", q: "Що означає «侘寂» (わびさび)?", opts: ["естетика недосконалої краси", "офіційний стиль", "евфемізм"], a: 0 },
        { lvl: "C2", q: "Що означає ідіома «石の上にも三年»?", opts: ["терпіння і труд усе перетруть", "поспішиш — людей насмішиш", "не все золото, що блищить"], a: 0 },
        { lvl: "C2", q: "Що означає «無常» (むじょう)?", opts: ["тлінність усього сущого", "вічність", "гармонія"], a: 0 },
        { lvl: "C2", q: "Що означає «婉曲表現» (えんきょくひょうげん)?", opts: ["евфемізм", "метафора", "іронія"], a: 0 },
    ];

    // =====================================================================
    //  ALPHABET — ХІРАГАНА (46 базових знаків, ґодзюон)
    // =====================================================================
    const ALPHABET = [
        { name: "あ", sound: "a — читається як укр. «а»", example: "あさ", example_uk: "ранок" },
        { name: "い", sound: "i — читається як укр. «і»", example: "いぬ", example_uk: "собака" },
        { name: "う", sound: "u — читається як коротке «у»", example: "うみ", example_uk: "море" },
        { name: "え", sound: "e — читається як укр. «е»", example: "えき", example_uk: "станція" },
        { name: "お", sound: "o — читається як укр. «о»", example: "おちゃ", example_uk: "чай" },
        { name: "か", sound: "ka — «ка»", example: "かさ", example_uk: "парасолька" },
        { name: "き", sound: "ki — «кі»", example: "きた", example_uk: "північ" },
        { name: "く", sound: "ku — «ку»", example: "くつ", example_uk: "взуття" },
        { name: "け", sound: "ke — «ке»", example: "けさ", example_uk: "цей ранок" },
        { name: "こ", sound: "ko — «ко»", example: "こども", example_uk: "дитина" },
        { name: "さ", sound: "sa — «са»", example: "さかな", example_uk: "риба" },
        { name: "し", sound: "shi — «ші» (не «сі»!)", example: "しろ", example_uk: "білий" },
        { name: "す", sound: "su — «су»", example: "すし", example_uk: "суші" },
        { name: "せ", sound: "se — «се»", example: "せんせい", example_uk: "вчитель" },
        { name: "そ", sound: "so — «со»", example: "そら", example_uk: "небо" },
        { name: "た", sound: "ta — «та»", example: "たまご", example_uk: "яйце" },
        { name: "ち", sound: "chi — «чі» (не «ті»!)", example: "ちず", example_uk: "мапа" },
        { name: "つ", sound: "tsu — «цу», особливий звук, якого нема в українській", example: "つき", example_uk: "місяць" },
        { name: "て", sound: "te — «те»", example: "てがみ", example_uk: "лист" },
        { name: "と", sound: "to — «то»", example: "とけい", example_uk: "годинник" },
        { name: "な", sound: "na — «на»", example: "なつ", example_uk: "літо" },
        { name: "に", sound: "ni — «ні»", example: "にく", example_uk: "м'ясо" },
        { name: "ぬ", sound: "nu — «ну»", example: "ぬの", example_uk: "тканина" },
        { name: "ね", sound: "ne — «не»", example: "ねこ", example_uk: "кіт" },
        { name: "の", sound: "no — «но»", example: "のみもの", example_uk: "напій" },
        { name: "は", sound: "ha — «ха» (як частка теми читається «ва», див. граматику)", example: "はな", example_uk: "квітка" },
        { name: "ひ", sound: "hi — «хі»", example: "ひと", example_uk: "людина" },
        { name: "ふ", sound: "fu — м'яке «фу», щось середнє між «фу» і «ху»", example: "ふゆ", example_uk: "зима" },
        { name: "へ", sound: "he — «хе»", example: "へや", example_uk: "кімната" },
        { name: "ほ", sound: "ho — «хо»", example: "ほし", example_uk: "зірка" },
        { name: "ま", sound: "ma — «ма»", example: "まど", example_uk: "вікно" },
        { name: "み", sound: "mi — «мі»", example: "みず", example_uk: "вода" },
        { name: "む", sound: "mu — «му»", example: "むし", example_uk: "комаха" },
        { name: "め", sound: "me — «ме»", example: "めがね", example_uk: "окуляри" },
        { name: "も", sound: "mo — «мо»", example: "もり", example_uk: "ліс" },
        { name: "や", sound: "ya — «я»", example: "やま", example_uk: "гора" },
        { name: "ゆ", sound: "yu — «ю»", example: "ゆき", example_uk: "сніг" },
        { name: "よ", sound: "yo — «йо»", example: "よる", example_uk: "ніч" },
        { name: "ら", sound: "ra — щось середнє між укр. «ра» і «ла»", example: "らいねん", example_uk: "наступний рік" },
        { name: "り", sound: "ri — середнє між «рі» і «лі»", example: "りんご", example_uk: "яблуко" },
        { name: "る", sound: "ru — середнє між «ру» і «лу»", example: "るす", example_uk: "відсутність вдома" },
        { name: "れ", sound: "re — середнє між «ре» і «ле»", example: "れきし", example_uk: "історія" },
        { name: "ろ", sound: "ro — середнє між «ро» і «ло»", example: "ろうか", example_uk: "коридор" },
        { name: "わ", sound: "wa — «ва»", example: "わたし", example_uk: "я" },
        { name: "を", sound: "o — вимовляється як «о», використовується ЛИШЕ як частка прямого додатка (граматика)", example: "ほんを よみます", example_uk: "читаю книгу" },
        { name: "ん", sound: "n — носове «н», єдиний знак хірагани без голосного", example: "ほん", example_uk: "книга" },
    ];

    // =====================================================================
    //  LESSONS — УРОКИ
    // =====================================================================
    const LESSONS = [
        {
            id: 1,
            level: 'A1',
            title: 'Хірагана: перші кроки',
            title_en: 'Hiragana: first steps',
            title_ru: 'Хирагана: первые шаги',
            content: 'Японська мова використовує три системи письма одночасно: хірагану (ひらがな), катакану (カタカナ) і кандзі (漢字, ієрогліфи, запозичені з китайської). Почнемо з хірагани — вона потрібна для граматичних часток і слів, у яких ще не вживають кандзі.\n\nХірагана — це складова абетка: кожен знак означає ОДИН склад (не букву), наприклад か = "ка" цілим складом, а не "к" окремо.\n\n| あ (a) | い (i) | う (u) | え (e) | お (o) |\n\nЦі п\'ять голосних — основа всієї системи: решта складів (か, き, く, け, こ і так далі) — це приголосний + один з цих п\'яти голосних.\n\n> Порада: できょ на початку не намагайся вивчити всі 46 знаків одразу. Вивчай по 5-10 знаків на день у розділі "Абетка" на сайті — там кожен знак має приклад слова.\n\nПрактика: подивись розділ "Абетка" і спробуй прочитати вголос перші 10 знаків (あ-こ).',
            content_en: 'Japanese uses three writing systems at once: hiragana (ひらがな), katakana (カタカナ), and kanji (漢字, characters borrowed from Chinese). Let\'s start with hiragana — it\'s needed for grammatical particles and words that don\'t yet use kanji.\n\nHiragana is a syllabary: each character represents ONE syllable (not a letter), for example か = the whole syllable "ka", not just "k".\n\n| あ (a) | い (i) | う (u) | え (e) | お (o) |\n\nThese five vowels are the foundation of the whole system: the rest of the syllables (か, き, く, け, こ and so on) are a consonant + one of these five vowels.\n\n> Tip: don\'t try to learn all 46 characters at once. Learn 5-10 characters a day in the "Alphabet" section of the site — each character has an example word.\n\nPractice: check the "Alphabet" section and try reading the first 10 characters (あ-こ) out loud.',
            content_ru: 'Японский язык использует три системы письма одновременно: хирагану (ひらがな), катакану (カタカナ) и кандзи (漢字, иероглифы, заимствованные из китайского). Начнём с хираганы — она нужна для грамматических частиц и слов, в которых ещё не используют кандзи.\n\nХирагана — это слоговая азбука: каждый знак означает ОДИН слог (не букву), например か = "ка" целым слогом, а не "к" отдельно.\n\n| あ (a) | い (i) | う (u) | え (e) | お (o) |\n\nЭти пять гласных — основа всей системы: остальные слоги (か, き, く, け, こ и так далее) — это согласный + один из этих пяти гласных.\n\n> Совет: не пытайся выучить все 46 знаков сразу. Учи по 5-10 знаков в день в разделе "Алфавит" на сайте — там у каждого знака есть пример слова.\n\nПрактика: посмотри раздел "Алфавит" и попробуй прочитать вслух первые 10 знаков (あ-こ).',
            tasks: [
                { q: 'Скільки складів у хірагані потрібно вивчити для базового читання?', q_en: 'How many hiragana syllables are needed for basic reading?', opts: ['46', '10', '100'], a: 0 },
                { q: 'Що таке хірагана?', q_en: 'What is hiragana?', opts: ['складова абетка', 'набір ієрогліфів', 'латинська транслітерація'], a: 0 },
            ],
        },
        {
            id: 2,
            level: 'A1',
            title: 'Привітання і знайомство',
            title_en: 'Greetings and introductions',
            title_ru: 'Приветствия и знакомство',
            content: 'Японські привітання залежать від часу доби.\n\n| おはようございます | Доброго ранку (ввічливо) |\n| こんにちは | Добрий день |\n| こんばんは | Добрий вечір |\n| おやすみなさい | На добраніч |\n\nЩоб представитися, кажуть своє ім\'я і додають です:\n\n| はじめまして。 | Приємно познайомитись. |\n| わたしは...です。 | Я — ... |\n| よろしくおねがいします。 | Радий знайомству / прошу любити і жалувати. |\n\n> Порада: фраза よろしくおねがいします — одна з найважливіших у японській мові. Її кажуть при знайомстві, на початку співпраці, майже в будь-якій новій формальній ситуації — прямого відповідника в українській нема, це щось на кшталт "прошу вашого прихильного ставлення".\n\nПрактика: склади коротке знайомство з трьох фраз: привітання, ім\'я, よろしくおねがいします.',
            content_en: 'Japanese greetings depend on the time of day.\n\n| おはようございます | Good morning (polite) |\n| こんにちは | Good afternoon |\n| こんばんは | Good evening |\n| おやすみなさい | Good night |\n\nTo introduce yourself, you say your name and add です:\n\n| はじめまして。 | Nice to meet you. |\n| わたしは...です。 | I am ... |\n| よろしくおねがいします。 | A set phrase asking for good treatment/cooperation going forward. |\n\n> Tip: よろしくおねがいします is one of the most important phrases in Japanese. It\'s said when meeting someone, starting a collaboration, in almost any new formal situation — there\'s no direct equivalent in English, it\'s something like "please treat me well going forward".\n\nPractice: write a short three-phrase introduction: greeting, name, よろしくおねがいします.',
            content_ru: 'Японские приветствия зависят от времени суток.\n\n| おはようございます | Доброе утро (вежливо) |\n| こんにちは | Добрый день |\n| こんばんは | Добрый вечер |\n| おやすみなさい | Спокойной ночи |\n\nЧтобы представиться, называют своё имя и добавляют です:\n\n| はじめまして。 | Приятно познакомиться. |\n| わたしは...です。 | Я — ... |\n| よろしくおねがいします。 | Рад знакомству / прошу любить и жаловать. |\n\n> Совет: фраза よろしくおねがいします — одна из важнейших в японском языке. Её говорят при знакомстве, в начале сотрудничества, почти в любой новой формальной ситуации — прямого аналога в русском нет, это что-то вроде "прошу вашего благосклонного отношения".\n\nПрактика: составь короткое знакомство из трёх фраз: приветствие, имя, よろしくおねがいします.',
            tasks: [
                { q: 'Як сказати "приємно познайомитись"?', q_en: 'How do you say "nice to meet you"?', opts: ['はじめまして', 'こんにちは', 'さようなら'], a: 0 },
                { q: 'Коли кажуть "こんばんは"?', q_en: 'When do you say "こんばんは"?', opts: ['ввечері', 'вранці', 'вдень'], a: 0 },
            ],
        },
        {
            id: 3,
            level: 'A1',
            title: 'Частки は, を, が — основи структури речення',
            title_en: 'The particles は, を, が — sentence structure basics',
            title_ru: 'Частицы は, を, が — основы структуры предложения',
            content: 'На відміну від української, японське речення будується за порядком "підмет — додаток — присудок" (SOV), і роль кожного слова показують не закінчення, а маленькі службові слова — частки, які ставлять ПІСЛЯ слова.\n\n| は (wa) | позначає тему речення | わたしは学生です。(Я — студент.) |\n| を (o) | позначає прямий додаток | 本を読みます。(Читаю книгу.) |\n| が (ga) | позначає підмет (хто/що конкретно) | 猫がいます。(Є кіт.) |\n\n> Порада: різниця між は і が — одна з найскладніших тем навіть для просунутих учнів. Спрощено: は — коли говориш ЗАГАЛОМ про тему, が — коли підкреслюєш КОНКРЕТНО підмет чи відповідаєш на питання "хто/що?".\n\nПрактика: склади речення "Я їм рибу" (わたし, たべます, さかな) — постав частки を і は на правильні місця.',
            content_en: 'Unlike English, a Japanese sentence follows the order "subject — object — verb" (SOV), and the role of each word is shown not by endings but by small function words — particles, placed AFTER the word.\n\n| は (wa) | marks the topic of the sentence | わたしは学生です。(I am a student.) |\n| を (o) | marks the direct object | 本を読みます。(I read a book.) |\n| が (ga) | marks the subject (who/what specifically) | 猫がいます。(There is a cat.) |\n\n> Tip: the difference between は and が is one of the hardest topics even for advanced learners. Simplified: は — when speaking GENERALLY about the topic, が — when emphasizing the SPECIFIC subject or answering "who/what?".\n\nPractice: build the sentence "I eat fish" (わたし, たべます, さかな) — put the particles を and は in the right places.',
            content_ru: 'В отличие от русского, японское предложение строится по порядку "подлежащее — дополнение — сказуемое" (SOV), и роль каждого слова показывают не окончания, а маленькие служебные слова — частицы, которые ставят ПОСЛЕ слова.\n\n| は (wa) | обозначает тему предложения | わたしは学生です。(Я — студент.) |\n| を (o) | обозначает прямое дополнение | 本を読みます。(Читаю книгу.) |\n| が (ga) | обозначает подлежащее (кто/что конкретно) | 猫がいます。(Есть кот.) |\n\n> Совет: разница между は и が — одна из самых сложных тем даже для продвинутых учеников. Упрощённо: は — когда говоришь В ОБЩЕМ о теме, が — когда подчёркиваешь КОНКРЕТНО подлежащее или отвечаешь на вопрос "кто/что?".\n\nПрактика: составь предложение "Я ем рыбу" (わたし, たべます, さかな) — поставь частицы を и は на правильные места.',
            tasks: [
                { q: 'Яка частка позначає прямий додаток?', q_en: 'Which particle marks the direct object?', opts: ['を', 'は', 'が'], a: 0 },
                { q: 'Який порядок слів у японському реченні?', q_en: 'What is the word order in a Japanese sentence?', opts: ['підмет-додаток-присудок', 'підмет-присудок-додаток', 'присудок-підмет-додаток'], a: 0 },
            ],
        },
    ];

    // =====================================================================
    //  РЕЄСТРАЦІЯ ДАНИХ У ГЛОБАЛЬНИЙ ОБ'ЄКТ
    // =====================================================================
    window.LANG_DATA = window.LANG_DATA || {};
    window.LANG_DATA.ja = {
        VOCAB,
        GRAMMAR,
        NORSKPROVE_TASKS,
        LEVEL_TEST,
        ALPHABET,
        LESSONS,
    };
})();
