// =====================================================================
//  СЛОВНИК: Нідерландська (Nederlands) — data-nl.js
// =====================================================================
//  Формат ідентичний data.js (норвезька): поле `no` переносить слово
//  ЦІЛЬОВОЮ мовою (тут — Нідерландська (Nederlands)), `uk`/`en`/`ru` — переклади,
//  `ex_no`/`ex_uk`/`en_ex`/`ru_ex` — приклади речень.
//
//  СТАТУС: рівень A1 заповнено (270 слів, паритет з норвезьким A1).
//  Рівні A2–C2 — заготовки (порожні масиви), наповнити наступними.
// =====================================================================
(function () {
// =====================================================================
    //  VOCAB – СЛОВНИК ЗА РІВНЯМИ (A1-C2)
    // =====================================================================
    const VOCAB = {
        // -------------------- A1 --------------------

    
        A1: [
            { t: "Привітання", no: "hoi", uk: "привіт", ex_no: "Hoi, hoe gaat het met je?", ex_uk: "Привіт, як справи?", en: "hi", en_ex: "Hi, how are you?", ru: "привет", ru_ex: "Привет, как дела?" },
            { t: "Привітання", no: "goedemorgen", uk: "добрий ранок", ex_no: "Goedemorgen, heb je goed geslapen?", ex_uk: "Добрий ранок, ти добре спав?", en: "good morning", en_ex: "Good morning, did you sleep well?", ru: "доброе утро", ru_ex: "Доброе утро, ты хорошо спал?" },
            { t: "Привітання", no: "goedendag", uk: "добрий день", ex_no: "Goedendag, kan ik je helpen?", ex_uk: "Добрий день, можу я вам допомогти?", en: "good day", en_ex: "Good day, can I help you?", ru: "добрый день", ru_ex: "Добрый день, могу я вам помочь?" },
            { t: "Привітання", no: "goedenavond", uk: "добрий вечір", ex_no: "Goedenavond, welkom thuis.", ex_uk: "Добрий вечір, ласкаво просимо додому.", en: "good evening", en_ex: "Good evening, welcome home.", ru: "добрый вечер", ru_ex: "Добрый вечер, добро пожаловать домой." },
            { t: "Привітання", no: "welterusten", uk: "на добраніч", ex_no: "Welterusten, slaap lekker!", ex_uk: "На добраніч, солодких снів!", en: "good night", en_ex: "Good night, sleep well!", ru: "спокойной ночи", ru_ex: "Спокойной ночи, сладких снов!" },
            { t: "Привітання", no: "tot ziens", uk: "бувай", ex_no: "Tot ziens, tot morgen!", ex_uk: "Бувай, побачимось завтра.", en: "bye", en_ex: "Bye, see you tomorrow.", ru: "пока", ru_ex: "Пока, увидимся завтра." },
            { t: "Привітання", no: "dank je", uk: "дякую", ex_no: "Dank je voor de hulp.", ex_uk: "Дякую за допомогу.", en: "thanks", en_ex: "Thanks for the help.", ru: "спасибо", ru_ex: "Спасибо за помощь." },
            { t: "Привітання", no: "alsjeblieft", uk: "будь ласка", ex_no: "Kun je me helpen, alsjeblieft?", ex_uk: "Можеш допомогти мені, будь ласка?", en: "please", en_ex: "Can you help me, please?", ru: "пожалуйста", ru_ex: "Можешь помочь мне, пожалуйста?" },
            { t: "Привітання", no: "pardon", uk: "вибачте", ex_no: "Pardon, waar is het station?", ex_uk: "Вибачте, де вокзал?", en: "excuse me", en_ex: "Excuse me, where is the station?", ru: "извините", ru_ex: "Извините, где вокзал?" },
            { t: "Привітання", no: "ja", uk: "так", ex_no: "Ja, dat klopt.", ex_uk: "Так, це правда.", en: "yes", en_ex: "Yes, that's right.", ru: "да", ru_ex: "Да, это правда." },
            { t: "Привітання", no: "nee", uk: "ні", ex_no: "Nee, ik weet het niet.", ex_uk: "Ні, я не знаю.", en: "no", en_ex: "No, I don't know.", ru: "нет", ru_ex: "Нет, я не знаю." },
            { t: "Привітання", no: "welkom", uk: "ласкаво просимо", ex_nl: "Welkom in Nederland!", ex_uk: "Ласкаво просимо до Норвегії!", en: "welcome", en_ex: "Welcome to Norway!", ru: "добро пожаловать", ru_ex: "Добро пожаловать в Норвегию!" },
            { t: "Привітання", no: "hoi (ochtend)", uk: "привіт (ранок)", ex_nl: "Hoi, hoe gaat het met je?", ex_uk: "Привіт, як ся маєш?", en: "morning (greeting)", en_ex: "Morning, how are you?", ru: "доброе утро (привет)", ru_ex: "Доброе утро, как ты?" },
            { t: "Числа", no: "nul", uk: "нуль", ex_no: "We beginnen bij nul.", ex_uk: "Ми починаємо з нуля.", en: "zero", en_ex: "We start from zero.", ru: "ноль", ru_ex: "Мы начинаем с нуля." },
            { t: "Числа", no: "een", uk: "один", ex_no: "Ik heb een kat.", ex_uk: "У мене є один кіт.", en: "one", en_ex: "I have one cat.", ru: "один", ru_ex: "У меня есть один кот." },
            { t: "Числа", no: "twee", uk: "два", ex_no: "Het is twee uur.", ex_uk: "Зараз друга година.", en: "two", en_ex: "It's two o'clock.", ru: "два", ru_ex: "Сейчас два часа." },
            { t: "Числа", no: "drie", uk: "три", ex_no: "Ik heb drie broers en zussen.", ex_uk: "У мене троє братів і сестер.", en: "three", en_ex: "I have three siblings.", ru: "три", ru_ex: "У меня трое братьев и сестёр." },
            { t: "Числа", no: "vier", uk: "чотири", ex_no: "De tafel heeft vier stoelen.", ex_uk: "У стола чотири стільці.", en: "four", en_ex: "The table has four chairs.", ru: "четыре", ru_ex: "У стола четыре стула." },
            { t: "Числа", no: "vijf", uk: "п'ять", ex_no: "De winkel opent om vijf uur.", ex_uk: "Магазин відкривається о п'ятій.", en: "five", en_ex: "The shop opens at five.", ru: "пять", ru_ex: "Магазин открывается в пять." },
            { t: "Числа", no: "zes", uk: "шість", ex_no: "We ontmoeten elkaar om zes uur.", ex_uk: "Ми зустрічаємось о шостій.", en: "six", en_ex: "We meet at six.", ru: "шесть", ru_ex: "Мы встречаемся в шесть." },
            { t: "Числа", no: "zeven", uk: "сім", ex_no: "De week heeft zeven dagen.", ex_uk: "У тижні сім днів.", en: "seven", en_ex: "The week has seven days.", ru: "семь", ru_ex: "В неделе семь дней." },
            { t: "Числа", no: "acht", uk: "вісім", ex_no: "Ik werk acht uur.", ex_uk: "Я працюю вісім годин.", en: "eight", en_ex: "I work eight hours.", ru: "восемь", ru_ex: "Я работаю восемь часов." },
            { t: "Числа", no: "negen", uk: "дев'ять", ex_no: "De film begint om negen uur.", ex_uk: "Фільм починається о дев'ятій.", en: "nine", en_ex: "The movie starts at nine.", ru: "девять", ru_ex: "Фильм начинается в девять." },
            { t: "Числа", no: "tien", uk: "десять", ex_no: "Hij telt tot tien.", ex_uk: "Він рахує до десяти.", en: "ten", en_ex: "He counts to ten.", ru: "десять", ru_ex: "Он считает до десяти." },
            { t: "Числа", no: "elf", uk: "одинадцять", ex_no: "De trein vertrekt om elf uur.", ex_uk: "Поїзд відправляється об одинадцятій.", en: "eleven", en_ex: "The train leaves at eleven.", ru: "одиннадцать", ru_ex: "Поезд отправляется в одиннадцать." },
            { t: "Числа", no: "twaalf", uk: "дванадцять", ex_no: "Het is nu twaalf uur.", ex_uk: "Зараз дванадцята година.", en: "twelve", en_ex: "It's twelve o'clock now.", ru: "двенадцать", ru_ex: "Сейчас двенадцать часов." },
            { t: "Числа", no: "dertien", uk: "тринадцять", ex_no: "Ik ben dertien jaar.", ex_uk: "Мені тринадцять років.", en: "thirteen", en_ex: "I am thirteen years old.", ru: "тринадцать", ru_ex: "Мне тринадцать лет." },
            { t: "Числа", no: "veertien", uk: "чотирнадцять", ex_no: "Er zijn nog veertien dagen over.", ex_uk: "Залишилось чотирнадцять днів.", en: "fourteen", en_ex: "There are fourteen days left.", ru: "четырнадцать", ru_ex: "Осталось четырнадцать дней." },
            { t: "Числа", no: "vijftien", uk: "п'ятнадцять", ex_no: "Zij heeft vijftien boeken.", ex_uk: "У неї п'ятнадцять книг.", en: "fifteen", en_ex: "She has fifteen books.", ru: "пятнадцать", ru_ex: "У неё пятнадцать книг." },
            { t: "Числа", no: "zestien", uk: "шістнадцять", ex_no: "We zijn met zestien personen.", ex_uk: "Нас шістнадцять осіб.", en: "sixteen", en_ex: "We are sixteen people.", ru: "шестнадцать", ru_ex: "Нас шестнадцать человек." },
            { t: "Числа", no: "zeventien", uk: "сімнадцять", ex_no: "De trein vertrekt om zeventien uur.", ex_uk: "Поїзд відправляється о сімнадцятій.", en: "seventeen", en_ex: "The train leaves at seventeen.", ru: "семнадцать", ru_ex: "Поезд отправляется в семнадцать часов." },
            { t: "Числа", no: "achttien", uk: "вісімнадцять", ex_no: "Ze is achttien jaar oud.", ex_uk: "Їй вісімнадцять років.", en: "eighteen", en_ex: "She is eighteen years old.", ru: "восемнадцать", ru_ex: "Ей восемнадцать лет." },
            { t: "Числа", no: "negentien", uk: "дев'ятнадцять", ex_no: "Het is negentien uur.", ex_uk: "Зараз дев'ятнадцята година.", en: "nineteen", en_ex: "It's nineteen o'clock.", ru: "девятнадцать", ru_ex: "Сейчас девятнадцать часов." },
            { t: "Числа", no: "twintig", uk: "двадцять", ex_no: "We hebben twintig minuten.", ex_uk: "Їй двадцять років.", en: "twenty", en_ex: "She is twenty years old.", ru: "двадцать", ru_ex: "Ей двадцать лет." },
            { t: "Числа", no: "dertig", uk: "тридцять", ex_no: "We hebben nog dertig minuten.", ex_uk: "У нас лишилось тридцять хвилин.", en: "thirty", en_ex: "We have thirty minutes left.", ru: "тридцать", ru_ex: "У нас осталось тридцать минут." },
            { t: "Числа", no: "veertig", uk: "сорок", ex_no: "Hij wordt vandaag veertig jaar.", ex_uk: "Йому сьогодні сорок років.", en: "forty", en_ex: "He turns forty today.", ru: "сорок", ru_ex: "Ему сегодня исполняется сорок." },
            { t: "Числа", no: "vijftig", uk: "п'ятдесят", ex_no: "Het kost vijftig euro.", ex_uk: "Це коштує п'ятдесят крон.", en: "fifty", en_ex: "It costs fifty kroner.", ru: "пятьдесят", ru_ex: "Это стоит пятьдесят крон." },
            { t: "Числа", no: "zestig", uk: "шістдесят", ex_no: "Zij is zestig jaar oud.", ex_uk: "Їй шістдесят років.", en: "sixty", en_ex: "She is sixty years old.", ru: "шестьдесят", ru_ex: "Ей шестьдесят лет." },
            { t: "Числа", no: "zeventig", uk: "сімдесят", ex_no: "Mijn opa is zeventig.", ex_uk: "Моєму дідусеві сімдесят.", en: "seventy", en_ex: "My grandfather is seventy.", ru: "семьдесят", ru_ex: "Моему дедушке семьдесят." },
            { t: "Числа", no: "tachtig", uk: "вісімдесят", ex_no: "Er zijn tachtig leerlingen op school.", ex_uk: "У школі вісімдесят учнів.", en: "eighty", en_ex: "There are eighty students at school.", ru: "восемьдесят", ru_ex: "В школе восемьдесят учеников." },
            { t: "Числа", no: "negentig", uk: "дев'яносто", ex_no: "De prijs is negentig euro.", ex_uk: "Ціна — дев'яносто крон.", en: "ninety", en_ex: "The price is ninety kroner.", ru: "девяносто", ru_ex: "Цена — девяносто крон." },
            { t: "Числа", no: "honderd", uk: "сто", ex_no: "Het kost honderd euro.", ex_uk: "Це коштує сто крон.", en: "hundred", en_ex: "It costs a hundred kroner.", ru: "сто", ru_ex: "Это стоит сто крон." },
            { t: "Числа", no: "duizend", uk: "тисяча", ex_no: "De stad heeft duizend inwoners.", ex_uk: "У місті тисяча жителів.", en: "thousand", en_ex: "The city has a thousand residents.", ru: "тысяча", ru_ex: "В городе тысяча жителей." },
            { t: "Родина", no: "moeder", uk: "мати", ex_no: "Mijn moeder woont in Amsterdam.", ex_uk: "Моя мати живе в Осло.", en: "mother", en_ex: "My mother lives in Oslo.", ru: "мать", ru_ex: "Моя мать живёт в Осло." },
            { t: "Родина", no: "vader", uk: "батько", ex_no: "Mijn vader houdt van vis.", ex_uk: "Мій батько любить рибу.", en: "father", en_ex: "My father likes fish.", ru: "отец", ru_ex: "Мой отец любит рыбу." },
            { t: "Родина", no: "zus", uk: "сестра", ex_no: "Ik heb een zus.", ex_uk: "У мене є сестра.", en: "sister", en_ex: "I have a sister.", ru: "сестра", ru_ex: "У меня есть сестра." },
            { t: "Родина", no: "broer", uk: "брат", ex_no: "Mijn broer studeert in Utrecht.", ex_uk: "Мій брат навчається в Бергені.", en: "brother", en_ex: "My brother studies in Bergen.", ru: "брат", ru_ex: "Мой брат учится в Бергене." },
            { t: "Родина", no: "dochter", uk: "дочка", ex_no: "Hun dochter is lerares.", ex_uk: "Їхня дочка — вчителька.", en: "daughter", en_ex: "Their daughter is a teacher.", ru: "дочь", ru_ex: "Их дочь — учительница." },
            { t: "Родина", no: "zoon", uk: "син", ex_no: "Mijn zoon speelt voetbal.", ex_uk: "Мій син грає в футбол.", en: "son", en_ex: "My son plays football.", ru: "сын", ru_ex: "Мой сын играет в футбол." },
            { t: "Родина", no: "oma", uk: "бабуся", ex_no: "Oma bakt een taart.", ex_uk: "Бабуся пече пиріг.", en: "grandmother", en_ex: "Grandmother bakes a cake.", ru: "бабушка", ru_ex: "Бабушка печёт пирог." },
            { t: "Родина", no: "opa", uk: "дідусь", ex_no: "Opa vist vaak.", ex_uk: "Дідусь часто рибалить.", en: "grandfather", en_ex: "Grandfather often goes fishing.", ru: "дедушка", ru_ex: "Дедушка часто рыбачит." },
            { t: "Родина", no: "vrouw", uk: "дружина", ex_no: "Zijn vrouw werkt in het ziekenhuis.", ex_uk: "Його дружина працює в лікарні.", en: "wife", en_ex: "His wife works at the hospital.", ru: "жена", ru_ex: "Его жена работает в больнице." },
            { t: "Родина", no: "man", uk: "чоловік", ex_no: "Haar man is arts.", ex_uk: "Її чоловік — лікар.", en: "husband", en_ex: "Her husband is a doctor.", ru: "муж", ru_ex: "Её муж — врач." },
            { t: "Родина", no: "kind", uk: "дитина", ex_no: "Ze hebben twee kinderen.", ex_uk: "У них двоє дітей.", en: "child", en_ex: "They have two children.", ru: "ребёнок", ru_ex: "У них двое детей." },
            { t: "Родина", no: "oom", uk: "дядько", ex_no: "Mijn oom woont in Rotterdam.", ex_uk: "Мій дядько живе в Тронгеймі.", en: "uncle", en_ex: "My uncle lives in Trondheim.", ru: "дядя", ru_ex: "Мой дядя живёт в Тронхейме." },
            { t: "Родина", no: "tante", uk: "тітка", ex_no: "Mijn tante kookt heerlijk eten.", ex_uk: "Моя тітка готує смачну їжу.", en: "aunt", en_ex: "My aunt cooks good food.", ru: "тётя", ru_ex: "Моя тётя готовит вкусную еду." },
            { t: "Родина", no: "neef", uk: "племінник", ex_no: "Mijn neef is erg aardig.", ex_uk: "Мій племінник дуже добрий.", en: "nephew", en_ex: "My nephew is very kind.", ru: "племянник", ru_ex: "Мой племянник очень добрый." },
            { t: "Родина", no: "nicht", uk: "племінниця", ex_no: "Mijn nicht houdt van zingen.", ex_uk: "Моя племінниця любить співати.", en: "niece", en_ex: "My niece likes to sing.", ru: "племянница", ru_ex: "Моя племянница любит петь." },
            { t: "Їжа", no: "brood", uk: "хліб", ex_no: "Ik koop elke dag brood.", ex_uk: "Я купую хліб щодня.", en: "bread", en_ex: "I buy bread every day.", ru: "хлеб", ru_ex: "Я покупаю хлеб каждый день." },
            { t: "Їжа", no: "melk", uk: "молоко", ex_no: "Het kind drinkt melk.", ex_uk: "Дитина п'є молоко.", en: "milk", en_ex: "The child drinks milk.", ru: "молоко", ru_ex: "Ребёнок пьёт молоко." },
            { t: "Їжа", no: "water", uk: "вода", ex_no: "Mag ik wat water?", ex_uk: "Можна мені трохи води?", en: "water", en_ex: "Can I have some water?", ru: "вода", ru_ex: "Можно мне немного воды?" },
            { t: "Їжа", no: "koffie", uk: "кава", ex_no: "Ik drink elke ochtend koffie.", ex_uk: "Я п'ю каву щоранку.", en: "coffee", en_ex: "I drink coffee every morning.", ru: "кофе", ru_ex: "Я пью кофе каждое утро." },
            { t: "Їжа", no: "thee", uk: "чай", ex_no: "Wil je thee of koffie?", ex_uk: "Хочеш чай чи каву?", en: "tea", en_ex: "Do you want tea or coffee?", ru: "чай", ru_ex: "Хочешь чай или кофе?" },
            { t: "Їжа", no: "vis", uk: "риба", ex_no: "We eten vis voor het avondeten.", ex_uk: "Ми їмо рибу на обід.", en: "fish", en_ex: "We eat fish for dinner.", ru: "рыба", ru_ex: "Мы едим рыбу на обед." },
            { t: "Їжа", no: "vlees", uk: "м'ясо", ex_no: "Hij eet geen vlees.", ex_uk: "Він не їсть м'яса.", en: "meat", en_ex: "He doesn't eat meat.", ru: "мясо", ru_ex: "Он не ест мясо." },
            { t: "Їжа", no: "ei", uk: "яйце", ex_no: "Ik maak eieren voor het ontbijt.", ex_uk: "Я готую яйця на сніданок.", en: "egg", en_ex: "I make eggs for breakfast.", ru: "яйцо", ru_ex: "Я готовлю яйца на завтрак." },
            { t: "Їжа", no: "kaas", uk: "сир", ex_no: "Deze kaas is lekker.", ex_uk: "Цей сир смачний.", en: "cheese", en_ex: "This cheese is good.", ru: "сыр", ru_ex: "Этот сыр вкусный." },
            { t: "Їжа", no: "boter", uk: "масло", ex_no: "Ze smeert boter op het brood.", ex_uk: "Вона мастить хліб маслом.", en: "butter", en_ex: "She spreads bread with butter.", ru: "масло", ru_ex: "Она мажет хлеб маслом." },
            { t: "Їжа", no: "appel", uk: "яблуко", ex_no: "Ik eet een appel als toetje.", ex_uk: "Одне яблуко на день.", en: "apple", en_ex: "An apple a day.", ru: "яблоко", ru_ex: "Одно яблоко в день." },
            { t: "Їжа", no: "aardappel", uk: "картопля", ex_no: "Ik kook aardappels voor het avondeten.", ex_uk: "Ми варимо картоплю на обід.", en: "potato", en_ex: "We boil potatoes for dinner.", ru: "картофель", ru_ex: "Мы варим картофель на обед." },
            { t: "Їжа", no: "rijst", uk: "рис", ex_no: "Ik hou van rijst met groenten.", ex_uk: "Ми їмо рис із куркою.", en: "rice", en_ex: "We eat rice with chicken.", ru: "рис", ru_ex: "Мы едим рис с курицей." },
            { t: "Їжа", no: "soep", uk: "суп", ex_no: "Ik eet soep bij de lunch.", ex_uk: "Суп гарячий.", en: "soup", en_ex: "The soup is hot.", ru: "суп", ru_ex: "Суп горячий." },
            { t: "Їжа", no: "taart", uk: "торт / пиріг", ex_no: "Oma bakt een taart.", ex_uk: "Ми печемо торт на день народження.", en: "cake", en_ex: "We bake a cake for the birthday.", ru: "торт", ru_ex: "Мы печём торт на день рождения." },
            { t: "Їжа", no: "suiker", uk: "цукор", ex_no: "Ik doe geen suiker in de koffie.", ex_uk: "Я додаю трохи цукру в каву.", en: "sugar", en_ex: "I take a bit of sugar in my coffee.", ru: "сахар", ru_ex: "Я кладу немного сахара в кофе." },
            { t: "Їжа", no: "zout", uk: "сіль", ex_no: "De soep heeft wat zout nodig.", ex_uk: "Можеш подати мені сіль?", en: "salt", en_ex: "Can you pass me the salt?", ru: "соль", ru_ex: "Можешь передать мне соль?" },
            { t: "Їжа", no: "peper", uk: "перець", ex_no: "Voeg wat peper toe.", ex_uk: "Можеш подати мені перець?", en: "pepper", en_ex: "Can you pass me the pepper?", ru: "перец", ru_ex: "Можешь передать мне перец?" },
            { t: "Їжа", no: "kip", uk: "курка", ex_no: "We eten kip voor het avondeten.", ex_uk: "Ми їмо курку сьогодні ввечері.", en: "chicken", en_ex: "We're eating chicken tonight.", ru: "курица", ru_ex: "Сегодня вечером мы едим курицу." },
            { t: "Їжа", no: "pasta", uk: "паста", ex_no: "Ik hou van pasta met tomatensaus.", ex_uk: "Я готую пасту на обід.", en: "pasta", en_ex: "I make pasta for dinner.", ru: "паста", ru_ex: "Я готовлю пасту на обед." },
            { t: "Їжа", no: "pizza", uk: "піца", ex_no: "Vandaag bestellen we pizza.", ex_uk: "У п'ятницю ми замовляємо піцу.", en: "pizza", en_ex: "We order pizza on Friday.", ru: "пицца", ru_ex: "В пятницу мы заказываем пиццу." },
            { t: "Їжа", no: "boterham", uk: "бутерброд", ex_no: "Ik maak een boterham voor het ontbijt.", ex_uk: "Я їм бутерброд на обід.", en: "sandwich", en_ex: "I eat a sandwich for lunch.", ru: "бутерброд", ru_ex: "Я ем бутерброд на обед." },
            { t: "Погода", no: "zon", uk: "сонце", ex_no: "Vandaag schijnt de zon.", ex_uk: "Сьогодні світить сонце.", en: "sun", en_ex: "The sun is shining today.", ru: "солнце", ru_ex: "Сегодня светит солнце." },
            { t: "Погода", no: "regen", uk: "дощ", ex_no: "Het regent.", ex_uk: "Завтра буде дощ.", en: "rain", en_ex: "It will rain tomorrow.", ru: "дождь", ru_ex: "Завтра будет дождь." },
            { t: "Погода", no: "sneeuw", uk: "сніг", ex_no: "'s Winters sneeuwt het.", ex_uk: "У горах іде сніг.", en: "snow", en_ex: "It's snowing in the mountains.", ru: "снег", ru_ex: "В горах идёт снег." },
            { t: "Погода", no: "wind", uk: "вітер", ex_no: "Vandaag waait het hard.", ex_uk: "Сьогодні сильний вітер.", en: "wind", en_ex: "It's very windy today.", ru: "ветер", ru_ex: "Сегодня сильный ветер." },
            { t: "Погода", no: "wolk", uk: "хмара", ex_no: "Er is een grote wolk aan de hemel.", ex_uk: "Небо повне хмар.", en: "cloud", en_ex: "The sky is full of clouds.", ru: "облако", ru_ex: "Небо полно облаков." },
            { t: "Погода", no: "koud", uk: "холодно", ex_no: "Vandaag is het erg koud.", ex_uk: "На вулиці холодно.", en: "cold", en_ex: "It's cold outside.", ru: "холодно", ru_ex: "На улице холодно." },
            { t: "Погода", no: "warm", uk: "тепло", ex_no: "'s Zomers is het warm.", ex_uk: "Влітку тепло.", en: "warm", en_ex: "It's warm in summer.", ru: "тепло", ru_ex: "Летом тепло." },
            { t: "Погода", no: "mist", uk: "туман", ex_no: "'s Ochtends was er dichte mist.", ex_uk: "Уздовж узбережжя туман.", en: "fog", en_ex: "There's fog along the coast.", ru: "туман", ru_ex: "Вдоль побережья туман." },
            { t: "Погода", no: "vorst", uk: "мороз", ex_no: "'s Nachts was er vorst.", ex_uk: "Вночі буде мороз.", en: "frost", en_ex: "There will be frost tonight.", ru: "мороз", ru_ex: "Ночью будет мороз." },
            { t: "Кольори", no: "rood", uk: "червоний", ex_no: "Ik heb een rood overhemd.", ex_uk: "Машина червона.", en: "red", en_ex: "The car is red.", ru: "красный", ru_ex: "Машина красная." },
            { t: "Кольори", no: "blauw", uk: "синій", ex_no: "De lucht is blauw.", ex_uk: "Небо синє.", en: "blue", en_ex: "The sky is blue.", ru: "синий", ru_ex: "Небо синее." },
            { t: "Кольори", no: "groen", uk: "зелений", ex_no: "Het gras is groen.", ex_uk: "Трава зелена.", en: "green", en_ex: "The grass is green.", ru: "зелёный", ru_ex: "Трава зелёная." },
            { t: "Кольори", no: "geel", uk: "жовтий", ex_no: "De zon is geel.", ex_uk: "Соняшник жовтий.", en: "yellow", en_ex: "The sunflower is yellow.", ru: "жёлтый", ru_ex: "Подсолнух жёлтый." },
            { t: "Кольори", no: "wit", uk: "білий", ex_no: "De sneeuw is wit.", ex_uk: "Сніг білий.", en: "white", en_ex: "The snow is white.", ru: "белый", ru_ex: "Снег белый." },
            { t: "Кольори", no: "zwart", uk: "чорний", ex_no: "Ik heb een zwarte auto.", ex_uk: "Кіт чорний.", en: "black", en_ex: "The cat is black.", ru: "чёрный", ru_ex: "Кот чёрный." },
            { t: "Кольори", no: "bruin", uk: "коричневий", ex_no: "Haar ogen zijn bruin.", ex_uk: "Взуття коричневе.", en: "brown", en_ex: "The shoes are brown.", ru: "коричневый", ru_ex: "Обувь коричневая." },
            { t: "Кольори", no: "roze", uk: "рожевий", ex_no: "Ik kocht een roze jurk.", ex_uk: "Її светр рожевий.", en: "pink", en_ex: "Her sweater is pink.", ru: "розовый", ru_ex: "Её свитер розовый." },
            { t: "Кольори", no: "oranje", uk: "помаранчевий", ex_no: "De sinaasappel is oranje.", ex_uk: "Сонце помаранчеве на заході.", en: "orange", en_ex: "The sun is orange at sunset.", ru: "оранжевый", ru_ex: "Солнце оранжевое на закате." },
            { t: "Кольори", no: "paars", uk: "фіолетовий", ex_no: "Ik hou van de kleur paars.", ex_uk: "Квітка фіолетова.", en: "purple", en_ex: "The flower is purple.", ru: "фиолетовый", ru_ex: "Цветок фиолетовый." },
            { t: "Тіло", no: "hoofd", uk: "голова", ex_no: "Ik heb hoofdpijn.", ex_uk: "У мене болить голова.", en: "head", en_ex: "My head hurts.", ru: "голова", ru_ex: "У меня болит голова." },
            { t: "Тіло", no: "oog", uk: "око", ex_no: "Zij heeft blauwe ogen.", ex_uk: "У неї сині очі.", en: "eye", en_ex: "She has blue eyes.", ru: "глаз", ru_ex: "У неё голубые глаза." },
            { t: "Тіло", no: "oor", uk: "вухо", ex_no: "De olifant heeft grote oren.", ex_uk: "Він погано чує на одне вухо.", en: "ear", en_ex: "He hears poorly in one ear.", ru: "ухо", ru_ex: "Он плохо слышит на одно ухо." },
            { t: "Тіло", no: "neus", uk: "ніс", ex_no: "Ik heb een kleine neus.", ex_uk: "У дитини маленький ніс.", en: "nose", en_ex: "The child has a small nose.", ru: "нос", ru_ex: "У ребёнка маленький нос." },
            { t: "Тіло", no: "mond", uk: "рот", ex_no: "Doe je mond open, alsjeblieft.", ex_uk: "Закрий рота.", en: "mouth", en_ex: "Close your mouth.", ru: "рот", ru_ex: "Закрой рот." },
            { t: "Тіло", no: "hand", uk: "рука (кисть)", ex_no: "Was je handen voor het eten.", ex_uk: "Дай мені свою руку.", en: "hand", en_ex: "Give me your hand.", ru: "рука (кисть)", ru_ex: "Дай мне свою руку." },
            { t: "Тіло", no: "voet", uk: "нога (ступня)", ex_no: "Mijn voet doet pijn.", ex_uk: "У мене болить нога.", en: "foot", en_ex: "My foot hurts.", ru: "нога (ступня)", ru_ex: "У меня болит нога." },
            { t: "Тіло", no: "buik", uk: "живіт", ex_no: "Mijn buik doet pijn.", ex_uk: "У мене болить живіт.", en: "stomach", en_ex: "My stomach hurts.", ru: "живот", ru_ex: "У меня болит живот." },
            { t: "Тіло", no: "hart", uk: "серце", ex_no: "Zijn hart klopt snel.", ex_uk: "Його серце б'ється швидко.", en: "heart", en_ex: "His heart beats fast.", ru: "сердце", ru_ex: "Его сердце бьётся быстро." },
            { t: "Дім", no: "huis", uk: "будинок", ex_no: "Ik woon in een groot huis.", ex_uk: "Вони живуть у великому будинку.", en: "house", en_ex: "They live in a big house.", ru: "дом", ru_ex: "Они живут в большом доме." },
            { t: "Дім", no: "appartement", uk: "квартира", ex_no: "Ik heb een nieuw appartement.", ex_uk: "Ми орендуємо квартиру.", en: "apartment", en_ex: "We rent an apartment.", ru: "квартира", ru_ex: "Мы снимаем квартиру." },
            { t: "Дім", no: "keuken", uk: "кухня", ex_no: "Ik kook in de keuken.", ex_uk: "Кухня маленька.", en: "kitchen", en_ex: "The kitchen is small.", ru: "кухня", ru_ex: "Кухня маленькая." },
            { t: "Дім", no: "slaapkamer", uk: "спальня", ex_no: "Mijn slaapkamer is klein.", ex_uk: "Моя спальня синя.", en: "bedroom", en_ex: "My bedroom is blue.", ru: "спальня", ru_ex: "Моя спальня синяя." },
            { t: "Дім", no: "badkamer", uk: "ванна кімната", ex_no: "De badkamer is boven.", ex_uk: "Ванна кімната нещодавно відремонтована.", en: "bathroom", en_ex: "The bathroom was recently renovated.", ru: "ванная комната", ru_ex: "Ванная комната недавно отремонтирована." },
            { t: "Дім", no: "woonkamer", uk: "вітальня", ex_no: "We kijken tv in de woonkamer.", ex_uk: "Ми дивимось телевізор у вітальні.", en: "living room", en_ex: "We watch TV in the living room.", ru: "гостиная", ru_ex: "Мы смотрим телевизор в гостиной." },
            { t: "Дім", no: "deur", uk: "двері", ex_no: "Doe de deur dicht, alsjeblieft.", ex_uk: "Зачини двері, будь ласка.", en: "door", en_ex: "Close the door, please.", ru: "дверь", ru_ex: "Закрой дверь, пожалуйста." },
            { t: "Дім", no: "raam", uk: "вікно", ex_no: "Doe het raam open.", ex_uk: "Вікно відчинене.", en: "window", en_ex: "The window is open.", ru: "окно", ru_ex: "Окно открыто." },
            { t: "Дім", no: "tafel", uk: "стіл", ex_no: "Zet de borden op tafel.", ex_uk: "Їжа на столі.", en: "table", en_ex: "The food is on the table.", ru: "стол", ru_ex: "Еда на столе." },
            { t: "Дім", no: "stoel", uk: "стілець", ex_no: "Ga op de stoel zitten.", ex_uk: "Сідай на стілець.", en: "chair", en_ex: "Sit on the chair.", ru: "стул", ru_ex: "Садись на стул." },
            { t: "Транспорт", no: "auto", uk: "машина", ex_no: "Ik heb een nieuwe auto.", ex_uk: "Ми їздимо на роботу машиною.", en: "car", en_ex: "We drive to work by car.", ru: "машина", ru_ex: "Мы ездим на работу на машине." },
            { t: "Транспорт", no: "fiets", uk: "велосипед", ex_no: "Ik fiets naar mijn werk.", ex_uk: "Він їде на велосипеді до школи.", en: "bicycle", en_ex: "He rides his bike to school.", ru: "велосипед", ru_ex: "Он едет на велосипеде в школу." },
            { t: "Транспорт", no: "vliegtuig", uk: "літак", ex_no: "Het vliegtuig vliegt hoog.", ex_uk: "Літак приземляється о десятій.", en: "airplane", en_ex: "The plane lands at ten.", ru: "самолёт", ru_ex: "Самолёт приземляется в десять." },
            { t: "Транспорт", no: "boot", uk: "човен", ex_no: "We varen met de boot op het meer.", ex_uk: "Ми пливемо човном через фіорд.", en: "boat", en_ex: "We take the boat across the fjord.", ru: "лодка", ru_ex: "Мы плывём на лодке через фьорд." },
            { t: "Транспорт", no: "trein", uk: "поїзд", ex_no: "De trein vertrekt om acht uur.", ex_uk: "Поїзд відправляється о восьмій.", en: "train", en_ex: "The train leaves at eight.", ru: "поезд", ru_ex: "Поезд отправляется в восемь." },
            { t: "Транспорт", no: "bus", uk: "автобус", ex_no: "Ik ga met de bus naar mijn werk.", ex_uk: "Автобус запізнюється.", en: "bus", en_ex: "The bus is late.", ru: "автобус", ru_ex: "Автобус опаздывает." },
            { t: "Дієслова", no: "zijn", uk: "бути", ex_no: "Ik wil arts zijn.", ex_uk: "Я студент.", en: "to be", en_ex: "I am a student.", ru: "быть", ru_ex: "Я студент." },
            { t: "Дієслова", no: "hebben", uk: "мати", ex_no: "Ik heb twee honden.", ex_uk: "У мене є брат.", en: "to have", en_ex: "I have a brother.", ru: "иметь", ru_ex: "У меня есть брат." },
            { t: "Дієслова", no: "doen", uk: "робити", ex_no: "Wat doe je nu?", ex_uk: "Що ти робиш?", en: "to do", en_ex: "What are you doing?", ru: "делать", ru_ex: "Что ты делаешь?" },
            { t: "Дієслова", no: "lopen", uk: "йти", ex_no: "Ik loop naar school.", ex_uk: "Ми йдемо до магазину.", en: "to go/walk", en_ex: "We're walking to the shop.", ru: "идти", ru_ex: "Мы идём в магазин." },
            { t: "Дієслова", no: "komen", uk: "приходити", ex_no: "Kom morgen naar mij toe.", ex_uk: "Коли ти прийдеш?", en: "to come", en_ex: "When are you coming?", ru: "приходить", ru_ex: "Когда ты придёшь?" },
            { t: "Дієслова", no: "zien", uk: "бачити", ex_no: "Ik zie de berg.", ex_uk: "Я бачу птаха.", en: "to see", en_ex: "I see a bird.", ru: "видеть", ru_ex: "Я вижу птицу." },
            { t: "Дієслова", no: "horen", uk: "чути", ex_no: "Ik hoor muziek.", ex_uk: "Ти мене чуєш?", en: "to hear", en_ex: "Can you hear me?", ru: "слышать", ru_ex: "Ты меня слышишь?" },
            { t: "Дієслова", no: "eten", uk: "їсти", ex_no: "We eten thuis.", ex_uk: "Ми снідаємо о восьмій.", en: "to eat", en_ex: "We eat breakfast at eight.", ru: "есть", ru_ex: "Мы завтракаем в восемь." },
            { t: "Дієслова", no: "drinken", uk: "пити", ex_no: "Ik drink elke dag water.", ex_uk: "Вона п'є воду.", en: "to drink", en_ex: "She drinks water.", ru: "пить", ru_ex: "Она пьёт воду." },
            { t: "Дієслова", no: "slapen", uk: "спати", ex_no: "Ik slaap acht uur.", ex_uk: "Дитина добре спить.", en: "to sleep", en_ex: "The child sleeps well.", ru: "спать", ru_ex: "Ребёнок хорошо спит." },
            { t: "Дієслова", no: "werken", uk: "працювати", ex_no: "Ik werk op een kantoor.", ex_uk: "Я працюю в офісі.", en: "to work", en_ex: "I work at the office.", ru: "работать", ru_ex: "Я работаю в офисе." },
            { t: "Дієслова", no: "wonen", uk: "жити", ex_no: "Ik woon in Amsterdam.", ex_uk: "Ми живемо в Бергені.", en: "to live", en_ex: "We live in Bergen.", ru: "жить", ru_ex: "Мы живём в Бергене." },
            { t: "Дієслова", no: "heten", uk: "звати (на ім'я)", ex_no: "Ik heet Anna.", ex_uk: "Мене звати Анна.", en: "to be called", en_ex: "My name is Anna.", ru: "зваться", ru_ex: "Меня зовут Анна." },
            { t: "Прикметники", no: "groot", uk: "великий", ex_no: "Dit is een groot huis.", ex_uk: "Будинок великий.", en: "big", en_ex: "The house is big.", ru: "большой", ru_ex: "Дом большой." },
            { t: "Прикметники", no: "klein", uk: "маленький", ex_no: "Ik heb een kleine hond.", ex_uk: "Кіт маленький.", en: "small", en_ex: "The cat is small.", ru: "маленький", ru_ex: "Кот маленький." },
            { t: "Прикметники", no: "lekker", uk: "добрий / смачний", ex_no: "Deze soep is lekker.", ex_uk: "Їжа смачна.", en: "good/tasty", en_ex: "The food is good.", ru: "хороший/вкусный", ru_ex: "Еда вкусная." },
            { t: "Прикметники", no: "slecht", uk: "поганий", ex_no: "Ik heb vandaag een slechte dag.", ex_uk: "Сьогодні погана погода.", en: "bad", en_ex: "The weather is bad today.", ru: "плохой", ru_ex: "Сегодня плохая погода." },
            { t: "Прикметники", no: "nieuw", uk: "новий", ex_no: "Ik heb een nieuwe telefoon gekocht.", ex_uk: "У мене нова робота.", en: "new", en_ex: "I have a new job.", ru: "новый", ru_ex: "У меня новая работа." },
            { t: "Прикметники", no: "oud", uk: "старий", ex_no: "Dit is een oud kasteel.", ex_uk: "Він старий, але активний.", en: "old", en_ex: "He is old but active.", ru: "старый", ru_ex: "Он старый, но активный." },
            { t: "Прикметники", no: "mooi", uk: "гарний", ex_no: "Zij heeft een mooie jurk.", ex_uk: "Сьогодні гарний день.", en: "nice/pretty", en_ex: "It's a nice day.", ru: "красивый", ru_ex: "Сегодня хороший день." },
            { t: "Прикметники", no: "blij", uk: "щасливий", ex_no: "Ik ben vandaag blij.", ex_uk: "Я тебе люблю (радий тобі).", en: "happy", en_ex: "I'm happy/fond of you.", ru: "счастливый", ru_ex: "Я тебя люблю (рад тебе)." },
            { t: "Прикметники", no: "verdrietig", uk: "сумний", ex_no: "Waarom ben je verdrietig?", ex_uk: "Вона сьогодні сумна.", en: "sad", en_ex: "She is sad today.", ru: "грустный", ru_ex: "Сегодня она грустная." },
            { t: "Прикметники", no: "lang", uk: "високий", ex_no: "Hij is erg lang.", ex_uk: "Гора дуже висока.", en: "tall/high", en_ex: "The mountain is very high.", ru: "высокий", ru_ex: "Гора очень высокая." },
            { t: "Прикметники", no: "laag", uk: "низький", ex_no: "Deze tafel is laag.", ex_uk: "Стіл низький.", en: "low", en_ex: "The table is low.", ru: "низкий", ru_ex: "Стол низкий." },
            { t: "Прикметники", no: "snel", uk: "швидкий", ex_no: "Deze auto is snel.", ex_uk: "Машина швидка.", en: "fast", en_ex: "The car is fast.", ru: "быстрый", ru_ex: "Машина быстрая." },
            { t: "Прикметники", no: "traag", uk: "повільний", ex_no: "Het internet is vandaag traag.", ex_uk: "Сьогодні інтернет повільний.", en: "slow", en_ex: "The internet is slow today.", ru: "медленный", ru_ex: "Сегодня интернет медленный." },
            { t: "Прикметники", no: "zwaar", uk: "важкий", ex_no: "Deze koffer is zwaar.", ex_uk: "Багаж важкий.", en: "heavy", en_ex: "The luggage is heavy.", ru: "тяжёлый", ru_ex: "Багаж тяжёлый." },
            { t: "Прикметники", no: "licht", uk: "легкий", ex_no: "Deze rugzak is licht.", ex_uk: "Завдання було легким.", en: "light/easy", en_ex: "The task was easy.", ru: "лёгкий", ru_ex: "Задание было лёгким." },
            { t: "Прикметники", no: "hongerig", uk: "голодний", ex_no: "Ik heb erg veel honger.", ex_uk: "Я зараз дуже голодний.", en: "hungry", en_ex: "I'm very hungry now.", ru: "голодный", ru_ex: "Я сейчас очень голодный." },
            { t: "Прикметники", no: "dorstig", uk: "спраглий", ex_no: "Ik heb dorst, ik wil water.", ex_uk: "Дитина хоче пити після пробіжки.", en: "thirsty", en_ex: "The child is thirsty after the run.", ru: "хочет пить", ru_ex: "Ребёнок хочет пить после пробежки." },
            { t: "Прикметники", no: "moe", uk: "втомлений", ex_no: "Ik ben vandaag moe.", ex_uk: "Я втомлений після роботи.", en: "tired", en_ex: "I'm tired after work.", ru: "уставший", ru_ex: "Я устал после работы." },
            { t: "Числа", no: "eerste", uk: "перший", ex_no: "Het is mijn eerste werkdag.", ex_uk: "Це мій перший день на роботі.", en: "first", en_ex: "This is my first day at work.", ru: "первый", ru_ex: "Это мой первый день на работе." },
            { t: "Числа", no: "tweede", uk: "другий", ex_no: "Dit is de tweede verdieping.", ex_uk: "Вона зайняла друге місце.", en: "second", en_ex: "She came in second place.", ru: "второй", ru_ex: "Она заняла второе место." },
            { t: "Числа", no: "derde", uk: "третій", ex_no: "Hij eindigde op de derde plaats.", ex_uk: "Ми живемо на третьому поверсі.", en: "third", en_ex: "We live on the third floor.", ru: "третий", ru_ex: "Мы живём на третьем этаже." },
            { t: "Числа", no: "vierde", uk: "четвертий", ex_no: "Dit is het vierde hoofdstuk.", ex_uk: "Він посів четверте місце в забігу.", en: "fourth", en_ex: "He took fourth place in the race.", ru: "четвёртый", ru_ex: "Он занял четвёртое место в забеге." },
            { t: "Числа", no: "vijfde", uk: "п'ятий", ex_no: "Ik woon op de vijfde verdieping.", ex_uk: "Зустріч п'ятого числа цього місяця.", en: "fifth", en_ex: "The meeting is on the fifth of the month.", ru: "пятый", ru_ex: "Встреча пятого числа месяца." },
            { t: "Свята", no: "Kerstmis", uk: "Різдво", ex_no: "Kerstmis is mijn favoriete feest.", ex_uk: "Ми святкуємо Різдво в грудні.", en: "Christmas", en_ex: "We celebrate Christmas in December.", ru: "Рождество", ru_ex: "Мы празднуем Рождество в декабре." },
            { t: "Свята", no: "Pasen", uk: "Великдень", ex_no: "Pasen valt in de lente.", ex_uk: "Великдень навесні.", en: "Easter", en_ex: "Easter is in spring.", ru: "Пасха", ru_ex: "Пасха весной." },
            { t: "Свята", no: "Nieuwjaar", uk: "Новий рік", ex_no: "We vieren Nieuwjaar samen.", ex_uk: "Ми запускаємо феєрверки на Новий рік.", en: "New Year", en_ex: "We set off fireworks on New Year.", ru: "Новый год", ru_ex: "Мы запускаем фейерверки на Новый год." },
            { t: "Свята", no: "verjaardag", uk: "день народження", ex_no: "Vandaag is mijn verjaardag.", ex_uk: "Коли в тебе день народження?", en: "birthday", en_ex: "When is your birthday?", ru: "день рождения", ru_ex: "Когда у тебя день рождения?" },
            { t: "Професії", no: "leraar", uk: "вчитель", ex_no: "Mijn broer is leraar.", ex_uk: "Вчитель пояснює граматику.", en: "teacher", en_ex: "The teacher explains grammar.", ru: "учитель", ru_ex: "Учитель объясняет грамматику." },
            { t: "Професії", no: "arts", uk: "лікар", ex_no: "Zij is een goede arts.", ex_uk: "Лікар оглядає пацієнта.", en: "doctor", en_ex: "The doctor examines the patient.", ru: "врач", ru_ex: "Врач осматривает пациента." },
            { t: "Професії", no: "verpleegster", uk: "медсестра", ex_no: "Mijn zus is verpleegster.", ex_uk: "Медсестра дає пацієнтові ліки.", en: "nurse", en_ex: "The nurse gives the patient medicine.", ru: "медсестра", ru_ex: "Медсестра даёт пациенту лекарство." },
            { t: "Професії", no: "ingenieur", uk: "інженер", ex_no: "Hij werkt als ingenieur.", ex_uk: "Інженер проектує міст.", en: "engineer", en_ex: "The engineer designs the bridge.", ru: "инженер", ru_ex: "Инженер проектирует мост." },
            { t: "Професії", no: "advocaat", uk: "адвокат", ex_no: "Mijn vader is advocaat.", ex_uk: "Адвокат захищає клієнта.", en: "lawyer", en_ex: "The lawyer defends the client.", ru: "адвокат", ru_ex: "Адвокат защищает клиента." },
            { t: "Професії", no: "architect", uk: "архітектор", ex_no: "Zij is architect.", ex_uk: "Архітектор малює будинок.", en: "architect", en_ex: "The architect draws the house.", ru: "архитектор", ru_ex: "Архитектор проектирует дом." },
            { t: "Професії", no: "chauffeur", uk: "водій", ex_no: "Mijn oom is buschauffeur.", ex_uk: "Водій керує автобусом.", en: "driver", en_ex: "The driver drives the bus.", ru: "водитель", ru_ex: "Водитель ведёт автобус." },
            { t: "Професії", no: "kapper", uk: "перукар", ex_no: "Ik ga morgen naar de kapper.", ex_uk: "Перукар стриже моє волосся.", en: "hairdresser", en_ex: "The hairdresser cuts my hair.", ru: "парикмахер", ru_ex: "Парикмахер стрижёт мои волосы." },
            { t: "Професії", no: "kok", uk: "кухар", ex_no: "Hij is kok in een restaurant.", ex_uk: "Кухар готує їжу в ресторані.", en: "cook/chef", en_ex: "The cook prepares food at the restaurant.", ru: "повар", ru_ex: "Повар готовит еду в ресторане." },
            { t: "Професії", no: "politieagent", uk: "поліцейський", ex_no: "Mijn buurman is politieagent.", ex_uk: "Поліцейський патрулює місто.", en: "police officer", en_ex: "The police officer patrols the city.", ru: "полицейский", ru_ex: "Полицейский патрулирует город." },
            { t: "Одяг", no: "overhemd", uk: "сорочка", ex_no: "Ik draag een wit overhemd.", ex_uk: "На мені біла сорочка.", en: "shirt", en_ex: "I'm wearing a white shirt.", ru: "рубашка", ru_ex: "На мне белая рубашка." },
            { t: "Одяг", no: "broek", uk: "штани", ex_no: "Ik heb een nieuwe broek gekocht.", ex_uk: "Штани задовгі.", en: "pants", en_ex: "The pants are too long.", ru: "штаны", ru_ex: "Штаны слишком длинные." },
            { t: "Одяг", no: "jas", uk: "куртка", ex_no: "Doe je jas aan, het is koud.", ex_uk: "Надягни куртку, на вулиці холодно.", en: "jacket", en_ex: "Put on your jacket, it's cold outside.", ru: "куртка", ru_ex: "Надень куртку, на улице холодно." },
            { t: "Одяг", no: "schoenen", uk: "взуття", ex_no: "Mijn schoenen zijn nieuw.", ex_uk: "Де моє взуття?", en: "shoes", en_ex: "Where are my shoes?", ru: "обувь", ru_ex: "Где моя обувь?" },
            { t: "Одяг", no: "muts", uk: "шапка", ex_no: "Doe je muts op, het is koud.", ex_uk: "Дитина в червоній шапці.", en: "hat/beanie", en_ex: "The child is wearing a red hat.", ru: "шапка", ru_ex: "Ребёнок в красной шапке." },
            { t: "Одяг", no: "handschoenen", uk: "рукавички", ex_no: "Ik ben mijn handschoenen thuis vergeten.", ex_uk: "Взимку мені потрібні теплі рукавички.", en: "gloves", en_ex: "I need warm gloves in winter.", ru: "перчатки", ru_ex: "Зимой мне нужны тёплые перчатки." },
            { t: "Одяг", no: "trui", uk: "светр", ex_no: "Deze trui is erg warm.", ex_uk: "Мій светр вовняний.", en: "sweater", en_ex: "My sweater is wool.", ru: "свитер", ru_ex: "Мой свитер шерстяной." },
            { t: "Тіло", no: "arm", uk: "рука (від плеча до кисті)", ex_no: "Ik heb mijn arm gebroken.", ex_uk: "Він зламав руку в аварії.", en: "arm", en_ex: "He broke his arm in an accident.", ru: "рука (от плеча)", ru_ex: "Он сломал руку в аварии." },
            { t: "Тіло", no: "been", uk: "нога (від стегна до ступні)", ex_no: "Mijn been doet pijn.", ex_uk: "У неї болить нога.", en: "leg", en_ex: "Her leg hurts.", ru: "нога (от бедра)", ru_ex: "У неё болит нога." },
            { t: "Тіло", no: "vinger", uk: "палець", ex_no: "Ik heb mijn vinger gesneden.", ex_uk: "У мене п'ять пальців на кожній руці.", en: "finger", en_ex: "I have five fingers on each hand.", ru: "палец", ru_ex: "У меня пять пальцев на каждой руке." },
            { t: "Тіло", no: "schouder", uk: "плече", ex_no: "Mijn schouder doet pijn.", ex_uk: "Він взяв її за плече.", en: "shoulder", en_ex: "He touched her on the shoulder.", ru: "плечо", ru_ex: "Он коснулся её плеча." },
            { t: "Тіло", no: "elleboog", uk: "лікоть", ex_no: "Ik stootte mijn elleboog.", ex_uk: "Я вперся ліктем у стіл.", en: "elbow", en_ex: "I bumped my elbow on the table.", ru: "локоть", ru_ex: "Я ударился локтем о стол." },
            { t: "Їжа", no: "sap", uk: "сік", ex_no: "Ik drink sinaasappelsap.", ex_uk: "Я п'ю апельсиновий сік на сніданок.", en: "juice", en_ex: "I drink orange juice for breakfast.", ru: "сок", ru_ex: "Я пью апельсиновый сок на завтрак." },
            { t: "Їжа", no: "boterham", uk: "бутерброд (скибка хліба з начинкою)", ex_no: "Ik at een boterham voor het ontbijt.", ex_uk: "Я їм бутерброд із сиром.", en: "open sandwich", en_ex: "I eat an open sandwich with cheese.", ru: "бутерброд", ru_ex: "Я ем бутерброд с сыром." },
            { t: "Їжа", no: "yoghurt", uk: "йогурт", ex_no: "'s Ochtends eet ik yoghurt met fruit.", ex_uk: "Дитина любить йогурт із ягодами.", en: "yogurt", en_ex: "The child likes yogurt with berries.", ru: "йогурт", ru_ex: "Ребёнок любит йогурт с ягодами." },
            { t: "Прикметники", no: "jong", uk: "молодий", ex_no: "Hij is nog jong.", ex_uk: "Вона молода і енергійна.", en: "young", en_ex: "She is young and energetic.", ru: "молодой", ru_ex: "Она молодая и энергичная." },
            { t: "Прикметники", no: "sterk", uk: "сильний", ex_no: "Hij is erg sterk.", ex_uk: "Він достатньо сильний, щоб підняти машину.", en: "strong", en_ex: "He is strong enough to lift the car.", ru: "сильный", ru_ex: "Он достаточно сильный, чтобы поднять машину." },
            { t: "Прикметники", no: "zwak", uk: "слабкий", ex_no: "Het signaal is zwak.", ex_uk: "Вона почувалася слабкою після хвороби.", en: "weak", en_ex: "She felt weak after the illness.", ru: "слабый", ru_ex: "Она чувствовала себя слабой после болезни." },
            { t: "Прикметники", no: "aardig", uk: "добрий (вже є, але додамо)", ex_no: "Zij is erg aardig.", ex_uk: "Вона добра вчителька.", en: "kind", en_ex: "She is a kind teacher.", ru: "добрый", ru_ex: "Она добрая учительница." },
            { t: "Дієслова", no: "lezen", uk: "читати", ex_no: "Ik hou van boeken lezen.", ex_uk: "Я люблю читати книги.", en: "to read", en_ex: "I like reading books.", ru: "читать", ru_ex: "Я люблю читать книги." },
            { t: "Дієслова", no: "schrijven", uk: "писати", ex_no: "Ik schrijf een brief aan een vriend.", ex_uk: "Вона пише листа.", en: "to write", en_ex: "She writes a letter.", ru: "писать", ru_ex: "Она пишет письмо." },
            { t: "Дієслова", no: "tekenen", uk: "малювати", ex_no: "Kinderen houden van tekenen.", ex_uk: "Дитина малює будинок.", en: "to draw", en_ex: "The child draws a house.", ru: "рисовать", ru_ex: "Ребёнок рисует дом." },
            { t: "Тварини", no: "hond", uk: "собака", ex_no: "Ik heb een kleine hond.", ex_uk: "Собака дружелюбна.", en: "dog", en_ex: "The dog is friendly.", ru: "собака", ru_ex: "Собака дружелюбная." },
            { t: "Тварини", no: "kat", uk: "кіт", ex_no: "De kat slaapt op de stoel.", ex_uk: "Кіт спить на дивані.", en: "cat", en_ex: "The cat sleeps on the sofa.", ru: "кот", ru_ex: "Кот спит на диване." },
            { t: "Тварини", no: "paard", uk: "кінь", ex_no: "Het paard rent snel.", ex_uk: "Кінь біжить швидко.", en: "horse", en_ex: "The horse runs fast.", ru: "лошадь", ru_ex: "Лошадь быстро бежит." },
            { t: "Тварини", no: "koe", uk: "корова", ex_no: "De koe eet gras.", ex_uk: "Корова дає молоко.", en: "cow", en_ex: "The cow gives milk.", ru: "корова", ru_ex: "Корова даёт молоко." },
            { t: "Дні тижня", no: "maandag", uk: "понеділок", ex_no: "Op maandag ga ik werken.", ex_uk: "Понеділок – перший день тижня.", en: "Monday", en_ex: "Monday is the first day of the week.", ru: "понедельник", ru_ex: "Понедельник — первый день недели." },
            { t: "Дні тижня", no: "dinsdag", uk: "вівторок", ex_no: "Op dinsdag heb ik training.", ex_uk: "У вівторок у нас нарада.", en: "Tuesday", en_ex: "We have a meeting on Tuesday.", ru: "вторник", ru_ex: "Во вторник у нас совещание." },
            { t: "Дні тижня", no: "woensdag", uk: "середа", ex_no: "Woensdag is midden in de week.", ex_uk: "Середа – середина тижня.", en: "Wednesday", en_ex: "Wednesday is the middle of the week.", ru: "среда", ru_ex: "Среда — середина недели." },
            { t: "Дні тижня", no: "donderdag", uk: "четвер", ex_no: "Op donderdag heb ik een vergadering.", ex_uk: "У четвер я працюю вдома.", en: "Thursday", en_ex: "On Thursday I work from home.", ru: "четверг", ru_ex: "В четверг я работаю дома." },
            { t: "Дні тижня", no: "vrijdag", uk: "п'ятниця", ex_no: "Vrijdag is mijn favoriete dag.", ex_uk: "П'ятниця – останній робочий день.", en: "Friday", en_ex: "Friday is the last work day.", ru: "пятница", ru_ex: "Пятница — последний рабочий день." },
            { t: "Дні тижня", no: "zaterdag", uk: "субота", ex_no: "Op zaterdag rust ik uit.", ex_uk: "Субота – ми відпочиваємо.", en: "Saturday", en_ex: "On Saturday we relax.", ru: "суббота", ru_ex: "В субботу мы отдыхаем." },
            { t: "Дні тижня", no: "zondag", uk: "неділя", ex_no: "Op zondag gaan we naar de kerk.", ex_uk: "У неділю ми йдемо в похід.", en: "Sunday", en_ex: "On Sunday we go on a trip.", ru: "воскресенье", ru_ex: "В воскресенье мы едем в поход." },
            { t: "Місяці", no: "januari", uk: "січень", ex_no: "Januari is de eerste maand.", ex_uk: "Січень – найхолодніший місяць.", en: "January", en_ex: "January is the coldest month.", ru: "январь", ru_ex: "Январь — самый холодный месяц." },
            { t: "Місяці", no: "februari", uk: "лютий", ex_no: "Februari is een korte maand.", ex_uk: "У лютому 28 днів.", en: "February", en_ex: "February has 28 days.", ru: "февраль", ru_ex: "В феврале 28 дней." },
            { t: "Місяці", no: "maart", uk: "березень", ex_no: "De lente begint in maart.", ex_uk: "Березень – весняний місяць.", en: "March", en_ex: "March is a spring month.", ru: "март", ru_ex: "Март — весенний месяц." },
            { t: "Місяці", no: "april", uk: "квітень", ex_no: "In april is het warm.", ex_uk: "Погода в квітні нестабільна.", en: "April", en_ex: "The weather in April is unstable.", ru: "апрель", ru_ex: "Погода в апреле нестабильна." },
            { t: "Місяці", no: "mei", uk: "травень", ex_no: "Mei is mooi.", ex_uk: "Травень – гарний місяць.", en: "May", en_ex: "May is a nice month.", ru: "май", ru_ex: "Май — хороший месяц." },
            { t: "Місяці", no: "juni", uk: "червень", ex_no: "De vakantie begint in juni.", ex_uk: "Червень – початок літа.", en: "June", en_ex: "June is the start of summer.", ru: "июнь", ru_ex: "Июнь — начало лета." },
            { t: "Місяці", no: "juli", uk: "липень", ex_no: "Juli is erg warm.", ex_uk: "Липень – найтепліший місяць.", en: "July", en_ex: "July is the warmest month.", ru: "июль", ru_ex: "Июль — самый тёплый месяц." },
            { t: "Місяці", no: "augustus", uk: "серпень", ex_no: "In augustus gaan we naar zee.", ex_uk: "Серпень – гарний місяць для відпустки.", en: "August", en_ex: "August is a nice vacation month.", ru: "август", ru_ex: "Август — хороший месяц для отпуска." },
            { t: "Місяці", no: "september", uk: "вересень", ex_no: "In september begint de school.", ex_uk: "Вересень – осінній місяць.", en: "September", en_ex: "September is an autumn month.", ru: "сентябрь", ru_ex: "Сентябрь — осенний месяц." },
            { t: "Місяці", no: "oktober", uk: "жовтень", ex_no: "Oktober is een kleurrijk seizoen.", ex_uk: "Жовтень барвистий.", en: "October", en_ex: "October is colorful.", ru: "октябрь", ru_ex: "Октябрь красочный." },
            { t: "Місяці", no: "november", uk: "листопад", ex_no: "November is koud en regenachtig.", ex_uk: "Листопад сірий і холодний.", en: "November", en_ex: "November is gray and cold.", ru: "ноябрь", ru_ex: "Ноябрь серый и холодный." },
            { t: "Місяці", no: "december", uk: "грудень", ex_no: "December sluit het jaar af.", ex_uk: "Грудень – місяць Різдва.", en: "December", en_ex: "December is the month of Christmas.", ru: "декабрь", ru_ex: "Декабрь — месяц Рождества." },
            { t: "Прийменники", no: "in", uk: "в / у", ex_no: "Ik woon in Amsterdam.", ex_uk: "Я живу в Осло.", en: "in", en_ex: "I live in Oslo.", ru: "в", ru_ex: "Я живу в Осло." },
            { t: "Прийменники", no: "op", uk: "на", ex_no: "Het boek ligt op de tafel.", ex_uk: "Книга лежить на столі.", en: "on", en_ex: "The book is on the table.", ru: "на", ru_ex: "Книга лежит на столе." },
            { t: "Прийменники", no: "onder", uk: "під", ex_no: "De kat slaapt onder de tafel.", ex_uk: "Кіт під ліжком.", en: "under", en_ex: "The cat is under the bed.", ru: "под", ru_ex: "Кот под кроватью." },
            { t: "Кухня", no: "mes", uk: "ніж", ex_no: "Snijd het brood met het mes.", ex_uk: "Ніж гострий.", en: "knife", en_ex: "The knife is sharp.", ru: "нож", ru_ex: "Нож острый." },
            { t: "Кухня", no: "vork", uk: "виделка", ex_no: "Eet de pasta met de vork.", ex_uk: "Я їм виделкою.", en: "fork", en_ex: "I eat with a fork.", ru: "вилка", ru_ex: "Я ем вилкой." },
            { t: "Кухня", no: "lepel", uk: "ложка", ex_no: "Eet de soep met de lepel.", ex_uk: "Дай мені ложку, будь ласка.", en: "spoon", en_ex: "Give me a spoon, please.", ru: "ложка", ru_ex: "Дай мне ложку, пожалуйста." },
            { t: "Кухня", no: "bord", uk: "тарілка", ex_no: "Zet het bord op de tafel.", ex_uk: "Тарілка порожня.", en: "plate", en_ex: "The plate is empty.", ru: "тарелка", ru_ex: "Тарелка пустая." },
            { t: "Кухня", no: "kopje", uk: "чашка", ex_no: "Giet koffie in het kopje.", ex_uk: "Чашка повна чаю.", en: "cup", en_ex: "The cup is full of tea.", ru: "чашка", ru_ex: "Чашка полна чая." },
            { t: "Кухня", no: "glas", uk: "склянка", ex_no: "Giet water in het glas.", ex_uk: "Він п'є зі склянки.", en: "glass", en_ex: "He drinks from a glass.", ru: "стакан", ru_ex: "Он пьёт из стакана." },
            { t: "Кухня", no: "koekenpan", uk: "сковорода", ex_no: "Ik bak eieren in de koekenpan.", ex_uk: "Я смажу яйця на сковороді.", en: "frying pan", en_ex: "I fry eggs in the pan.", ru: "сковорода", ru_ex: "Я жарю яйца на сковороде." },
            { t: "Кухня", no: "pan", uk: "каструля", ex_no: "Ik kook soep in de pan.", ex_uk: "Суп вариться в каструлі.", en: "pot", en_ex: "The soup is cooking in the pot.", ru: "кастрюля", ru_ex: "Суп варится в кастрюле." },
            { t: "Кухня", no: "oven", uk: "духовка", ex_no: "Ik bak een taart in de oven.", ex_uk: "Пиріг у духовці.", en: "oven", en_ex: "The cake is in the oven.", ru: "духовка", ru_ex: "Пирог в духовке." },
            { t: "Кухня", no: "koelkast", uk: "холодильник", ex_no: "De melk staat in de koelkast.", ex_uk: "Молоко стоїть у холодильнику.", en: "fridge", en_ex: "The milk is in the fridge.", ru: "холодильник", ru_ex: "Молоко стоит в холодильнике." },
            { t: "Меблі", no: "bed", uk: "ліжко", ex_no: "Ik slaap in een comfortabel bed.", ex_uk: "Я лягаю спати о десятій.", en: "bed", en_ex: "I go to bed at ten.", ru: "кровать", ru_ex: "Я ложусь спать в десять." },
            { t: "Меблі", no: "kast", uk: "шафа", ex_no: "De kleren zitten in de kast.", ex_uk: "Одяг висить у шафі.", en: "cupboard/wardrobe", en_ex: "The clothes hang in the wardrobe.", ru: "шкаф", ru_ex: "Одежда висит в шкафу." },
            { t: "Меблі", no: "plank", uk: "полиця", ex_no: "De boeken staan op de plank.", ex_uk: "Книги стоять на полиці.", en: "shelf", en_ex: "The books are on the shelf.", ru: "полка", ru_ex: "Книги стоят на полке." },
            { t: "Меблі", no: "spiegel", uk: "дзеркало", ex_no: "Kijk in de spiegel.", ex_uk: "Вона дивиться на себе в дзеркало.", en: "mirror", en_ex: "She looks at herself in the mirror.", ru: "зеркало", ru_ex: "Она смотрит на себя в зеркало." },
            { t: "Меблі", no: "lamp", uk: "лампа", ex_no: "Doe de lamp aan, het is donker.", ex_uk: "Можеш увімкнути лампу?", en: "lamp", en_ex: "Can you turn on the lamp?", ru: "лампа", ru_ex: "Можешь включить лампу?" },
            { t: "Меблі", no: "tapijt", uk: "килим / ковдра", ex_no: "De kat slaapt op het tapijt.", ex_uk: "Килим лежить на підлозі.", en: "carpet/blanket", en_ex: "The carpet is on the floor.", ru: "ковёр", ru_ex: "Ковёр лежит на полу." },
            { t: "Меблі", no: "kussen", uk: "подушка", ex_no: "Ik slaap op een zacht kussen.", ex_uk: "Подушка м'яка.", en: "pillow", en_ex: "The pillow is soft.", ru: "подушка", ru_ex: "Подушка мягкая." },
            { t: "Природа", no: "ster", uk: "зірка", ex_no: "Ik zie een ster aan de hemel.", ex_uk: "Уночі світять зірки.", en: "star", en_ex: "The stars shine at night.", ru: "звезда", ru_ex: "Ночью светят звёзды." },
            { t: "Природа", no: "maan", uk: "місяць (небесне тіло)", ex_no: "Vandaag is het volle maan.", ex_uk: "Сьогодні повний місяць.", en: "moon", en_ex: "The moon is full tonight.", ru: "луна", ru_ex: "Сегодня полнолуние." },
            { t: "Природа", no: "hemel", uk: "небо", ex_no: "De hemel is vandaag blauw.", ex_uk: "Сьогодні небо синє.", en: "sky", en_ex: "The sky is blue today.", ru: "небо", ru_ex: "Сегодня небо синее." },
            { t: "Природа", no: "aarde", uk: "земля", ex_no: "We planten bloemen in de aarde.", ex_uk: "Квіти ростуть у землі.", en: "earth/soil", en_ex: "Flowers grow in the soil.", ru: "земля", ru_ex: "Цветы растут в земле." },
            { t: "Природа", no: "ijs", uk: "лід", ex_no: "Water bevriest tot ijs.", ex_uk: "Вода перетворилась на лід.", en: "ice", en_ex: "The water turned to ice.", ru: "лёд", ru_ex: "Вода превратилась в лёд." },
            { t: "Природа", no: "bliksem", uk: "блискавка", ex_no: "We zagen bliksem aan de hemel.", ex_uk: "Блискавка освітила небо.", en: "lightning", en_ex: "The lightning lit up the sky.", ru: "молния", ru_ex: "Молния осветила небо." },
            { t: "Дієслова", no: "springen", uk: "стрибати", ex_no: "Kinderen houden van springen.", ex_uk: "Діти стрибають у воду.", en: "to jump", en_ex: "The children jump in the water.", ru: "прыгать", ru_ex: "Дети прыгают в воду." },
            { t: "Дієслова", no: "zwemmen", uk: "плавати", ex_no: "Ik kan zwemmen.", ex_uk: "Я плаваю щоранку.", en: "to swim", en_ex: "I swim every morning.", ru: "плавать", ru_ex: "Я плаваю каждое утро." },
            { t: "Дієслова", no: "vallen", uk: "падати", ex_no: "Pas op dat je niet valt.", ex_uk: "Восени опадає листя.", en: "to fall", en_ex: "Leaves fall in autumn.", ru: "падать", ru_ex: "Осенью опадают листья." },
            { t: "Дієслова", no: "opstaan", uk: "вставати", ex_no: "Ik sta vroeg op in de ochtend.", ex_uk: "Він рано встає.", en: "to get up", en_ex: "He gets up early.", ru: "вставать", ru_ex: "Он рано встаёт." },
            { t: "Дієслова", no: "gaan zitten", uk: "сідати", ex_no: "Ga zitten, alsjeblieft.", ex_uk: "Сідай тут, будь ласка.", en: "to sit down", en_ex: "Sit down here, please.", ru: "садиться", ru_ex: "Садись сюда, пожалуйста." },
            { t: "Прикметники", no: "vol", uk: "повний", ex_no: "De bus is vol.", ex_uk: "Склянка повна.", en: "full", en_ex: "The glass is full.", ru: "полный", ru_ex: "Стакан полный." },
            { t: "Прикметники", no: "leeg", uk: "порожній", ex_no: "De koelkast is leeg.", ex_uk: "Кімната порожня.", en: "empty", en_ex: "The room is empty.", ru: "пустой", ru_ex: "Комната пустая." },
            { t: "Прикметники", no: "schoon", uk: "чистий", ex_no: "De keuken is schoon.", ex_uk: "Кухня чиста.", en: "clean", en_ex: "The kitchen is clean.", ru: "чистый", ru_ex: "Кухня чистая." },
            { t: "Прикметники", no: "vies", uk: "брудний", ex_no: "Mijn schoenen zijn vies.", ex_uk: "Взуття брудне.", en: "dirty", en_ex: "The shoes are dirty.", ru: "грязный", ru_ex: "Обувь грязная." },
            { t: "Прикметники", no: "nat", uk: "мокрий", ex_no: "Mijn kleren zijn nat.", ex_uk: "Моє волосся мокре.", en: "wet", en_ex: "My hair is wet.", ru: "мокрый", ru_ex: "Мои волосы мокрые." },
            { t: "Прикметники", no: "droog", uk: "сухий", ex_no: "De lucht is vandaag droog.", ex_uk: "Рушник сухий.", en: "dry", en_ex: "The towel is dry.", ru: "сухой", ru_ex: "Полотенце сухое." },
            { t: "Прикметники", no: "zacht", uk: "м'який", ex_no: "Dit kussen is zacht.", ex_uk: "Диван м'який.", en: "soft", en_ex: "The sofa is soft.", ru: "мягкий", ru_ex: "Диван мягкий." },
            { t: "Прикметники", no: "hard", uk: "твердий", ex_no: "Deze stoel is hard.", ex_uk: "Хліб твердий.", en: "hard", en_ex: "The bread is hard.", ru: "твёрдый", ru_ex: "Хлеб твёрдый." },
            { t: "Прикметники", no: "open", uk: "відкритий", ex_no: "De winkel is nog open.", ex_uk: "Магазин зараз відкритий.", en: "open", en_ex: "The shop is open now.", ru: "открытый", ru_ex: "Магазин сейчас открыт." },
            { t: "Родина", no: "schoonmoeder", uk: "теща / свекруха", ex_no: "Mijn schoonmoeder woont dichtbij.", ex_uk: "Моя теща приємна.", en: "mother-in-law", en_ex: "My mother-in-law is nice.", ru: "тёща/свекровь", ru_ex: "Моя тёща приятная." },
            { t: "Родина", no: "schoonvader", uk: "тесть / свекор", ex_no: "Mijn schoonvader houdt van tuinieren.", ex_uk: "Мій тесть живе за містом.", en: "father-in-law", en_ex: "My father-in-law lives in the countryside.", ru: "тесть/свёкор", ru_ex: "Мой тесть живёт за городом." },
            { t: "Школа", no: "pen", uk: "ручка", ex_no: "Ik schrijf met een pen.", ex_uk: "Можна позичити ручку?", en: "pen", en_ex: "Can I borrow a pen?", ru: "ручка", ru_ex: "Можно позаимствовать ручку?" },
            { t: "Школа", no: "potlood", uk: "олівець", ex_no: "Ik teken met een potlood.", ex_uk: "Я малюю олівцем.", en: "pencil", en_ex: "I draw with a pencil.", ru: "карандаш", ru_ex: "Я рисую карандашом." },
            { t: "Школа", no: "gum", uk: "гумка (для стирання)", ex_no: "Ik heb een gum nodig om de fout uit te vegen.", ex_uk: "У тебе є гумка?", en: "eraser", en_ex: "Do you have an eraser?", ru: "ластик", ru_ex: "У тебя есть ластик?" },
            { t: "Школа", no: "rugzak", uk: "рюкзак", ex_no: "Ik draag de boeken in mijn rugzak.", ex_uk: "Книга лежить у рюкзаку.", en: "backpack", en_ex: "The book is in the backpack.", ru: "рюкзак", ru_ex: "Книга лежит в рюкзаке." },
            { t: "Школа", no: "boek", uk: "книга", ex_no: "Ik lees een interessant boek.", ex_uk: "Я читаю цікаву книгу.", en: "book", en_ex: "I'm reading an exciting book.", ru: "книга", ru_ex: "Я читаю интересную книгу." },
            { t: "Тіло", no: "haar", uk: "волосся", ex_no: "Zij heeft lang haar.", ex_uk: "У неї довге волосся.", en: "hair", en_ex: "She has long hair.", ru: "волосы", ru_ex: "У неё длинные волосы." },
            { t: "Тіло", no: "tand", uk: "зуб", ex_no: "Ik heb kiespijn.", ex_uk: "Я чищу зуби.", en: "tooth", en_ex: "I brush my teeth.", ru: "зуб", ru_ex: "Я чищу зубы." },
            { t: "Тіло", no: "nek", uk: "шия", ex_no: "Ik heb een stijve nek.", ex_uk: "У мене болить шия.", en: "neck/throat", en_ex: "My neck hurts.", ru: "шея", ru_ex: "У меня болит шея." },
            { t: "Тіло", no: "knie", uk: "коліно", ex_no: "Ik stootte mijn knie.", ex_uk: "Я впав і забив коліно.", en: "knee", en_ex: "I fell and hit my knee.", ru: "колено", ru_ex: "Я упал и ударил колено." },
        ],
        A2: [],
        B1: [],
        B2: [],
        C1: [],
        C2: [],
    };

    // =====================================================================
    //  GRAMMAR – ГРАМАТИКА (поки порожня, можна заповнити пізніше)
    // =====================================================================
    const GRAMMAR = [];

    // =====================================================================
    //  NORSKPROVE_TASKS – ЗАВДАННЯ ДЛЯ ПРАКТИКИ (поки порожні)
    // =====================================================================
    const NORSKPROVE_TASKS = {
        A1: { reading: [], listening: [], writing: [], speaking: [] },
        A2: { reading: [], listening: [], writing: [], speaking: [] },
        B1: { reading: [], listening: [], writing: [], speaking: [] },
        B2: { reading: [], listening: [], writing: [], speaking: [] },
        C1: { reading: [], listening: [], writing: [], speaking: [] },
        C2: { reading: [], listening: [], writing: [], speaking: [] },
    };

    // =====================================================================
    //  LEVEL_TEST – ТЕСТ НА РІВЕНЬ (поки порожній)
    // =====================================================================
    const LEVEL_TEST = [];

    // =====================================================================
    //  ALPHABET – АБЕТКА (поки порожня)
    // =====================================================================
    const ALPHABET = [];

    // =====================================================================
    //  LESSONS – УРОКИ (поки порожні)
    // =====================================================================
    const LESSONS = [];

    // =====================================================================
    //  РЕЄСТРАЦІЯ ДАНИХ У ГЛОБАЛЬНИЙ ОБ'ЄКТ
    // =====================================================================
    window.LANG_DATA = window.LANG_DATA || {};
    window.LANG_DATA.nl = {
        VOCAB,
        GRAMMAR,
        NORSKPROVE_TASKS,
        LEVEL_TEST,
        ALPHABET,
        LESSONS,
    };

})();
